### ISSUE TITLE
Issue a check execution request

### ISSUE THREAD

**Issue by palourde** [sensu/uchiwa#141]
According to the API documentation (http://sensuapp.org/docs/latest/api_checks), we could call /request with a payload in order to request a check execution.

It could easily be added on the checks view.

**Comment by nicholascapo** [comment]
+1 We have some once-a-day checks, if the check fails, we try and fix it and then wait a day before we know if it works (through sensu).

Really, this feature would be nice for any check with an interval over 1 minute :-)

**Comment by bjwschaap** [comment]
+1 We'd love this feature as well
