### ISSUE TITLE
Set the default theme

### ISSUE THREAD

**Issue by palourde** [sensu/uchiwa#164]
In case someone use a custom theme for his organization, it would be easier if this theme could be easily set as the default one.

**Comment by ROunofF** [comment]
You could easily set the cookie to expire 1 year+ starting at angular 1.4+...

diff --git a/js/directives.js b/js/directives.js
index 9b99a83..98c8bc2 100644
--- a/js/directives.js
+++ b/js/directives.js
@@ -60,7 +60,9 @@ directiveModule.directive('siteTheme', ['conf', '$cookieStore', '$rootScope', fu
         var name = scope.currentTheme.name;
         var enterprise = scope.currentTheme.enterprise || false;

-        $cookieStore.put('uchiwa_theme', name);
+        var oneYearExpiration = new Date();
+        oneYearExpiration.setYear(oneYearExpiration.getFullYear()+1);
+        $cookieStore.put('uchiwa_theme', name, { "expires": oneYearExpiration });

         var path = enterprise ? 'css/' : 'bower_components/uchiwa-web/css/';
         element.attr('href', path + name + '/' + name + '.css');

**Comment by ReneVolution** [comment]
It would be great to choose a theme by query string and/or setting a default with an environment variable.

**Comment by palourde** [comment]
Fixed by https://github.com/sensu/uchiwa-web/pull/125

**Comment by vishalud** [comment]
This PR dosent exist any more and 404's ?? @palourde

**Comment by palourde** [comment]
@vishalud See the [Uchiwa docs] for instructions on how to set a default theme for your users: https://docs.uchiwa.io/getting-started/configuration/#users-options
