### ISSUE TITLE
Customize the main logo

### ISSUE THREAD

**Issue by palourde** [sensu/uchiwa#165]
In order to offer a white-label dashboard, it would be easier if the top-left logo could be easily replaced with a custom one.

**Comment by reiven** [comment]
+1

**Comment by pgporada** [comment]
I just had a team member mention this to me as well.

**Comment by Pryz** [comment]
+1

**Comment by palourde** [comment]
Fixed by https://github.com/sensu/uchiwa-web/pull/125
