### ISSUE TITLE
API call to "http://localhost:<port>/stashes" returned: 401 Unauthorized

### ISSUE THREAD

**Issue by tugayac** [sensu/uchiwa#172]
Using the latest version of Uchiwa (with the Go Server), I get a 401 Unauthorized error after a call to the Sensu API. I've triple-checked the host, port, username, and password in api.json for the Sensu API and config.json for Uchiwa and they match. None of the logs provide any useful information as to why this is the case When I get a 401 Unauthorized error, nothing gets logged in the Sensu API log, but if I don't use a username and password on either the API or Uchiwa, all calls get logged.

I was able to overcome this issue by removing the username and password requirement for Sensu API.

All the Sensu components are located on the same machine.

**Comment by arukaen** [comment]
I installed uchiwa via the sensu repos and still see the bug there.

**Comment by schlagify** [comment]
this issue still exists as of debian 7.8, sensu 0.17.0-1, uchiwa 0.7.0-1
