### ISSUE TITLE
Support multiple APIs for the same data center

### ISSUE THREAD

**Issue by amdprophet** [sensu/uchiwa#173]
Redundancy is a good thing. We should investigate implementing support for multiple APIs within the same data center so that Uchiwa can failover to another API & support rudimentary load balancing.

**Comment by chiriaev** [comment]
Guys, Hi. On a slightly different not, I would add distinction between GET and PUT/POST/DELETE API calls and let the administrator decide which API instance to query. It would help reading, for example, from an API connected to a local REDIS slave, and writing to a "master" on a different server. (i.e.: across the Atlantic perhaps)

Regards, Andrei

**Comment by palourde** [comment]
Added with 0.11.0

**Comment by palourde** [comment]
Wrong issue, my bad!
