### ISSUE TITLE
no output when a check is correctly done

### ISSUE THREAD

**Issue by VMF214** [sensu/uchiwa#178]
hello!

i made a check on a client, and this check exit 0, so no problem, and on the client i see the check in green, but i the output is blank.
Uchiwa only display outputs when warning, alert or uknow.

**Comment by warmfusion** [comment]
I too have found this to be somewhat frustrating, and while it may not go anywhere, I have raised a ticket in Sensu to store only the last message from the monitors such that it becomes viable to display that information in Uchiwa.

https://github.com/sensu/sensu/issues/860

**Comment by portertech** [comment]
Client check history (e.g. /clients/:client/history) will soon include the last check result (even if OK). https://github.com/sensu/sensu/blob/master/CHANGELOG.md#0180---tbd

**Comment by andytinycat** [comment]
Sensu 0.18 has been released - any plans to include "green light" checks in Uchiwa's views using this new feature?

**Comment by palourde** [comment]
@andytinycat I created https://github.com/sensu/uchiwa/issues/322 in order to support this new feature in Uchiwa
