### ISSUE TITLE
Separate get_sensu request into categorized requests

### ISSUE THREAD

**Issue by amdprophet** [sensu/uchiwa#220]
This is more of a request to start a discussion around potential changes to the way Uchiwa fetches information.

Currently, Uchiwa is fetching all its data from the Go API using `GET /get_sensu`. I'd like to suggest implementing individual RESTful routes for events, clients, stashes, etc. (eg. `GET /events`, `GET /clients`, etc.).

Advantages to this approach:
* Less time to update events/clients/stashes after performing an action on them
  * Current `GET /get_sensu` request can be quite bulky which can potentially cause slowdowns with large Sensu installs
* Separates concerns 
* Enables us to use Restangular
  * Can simplify our way of fetching, updating, and deleting resources
  * Supports collections that can be updated without overwriting dirty attributes
    * Can eliminate our usage of  `_.extend()` to keep dirty attributes which only applies  to top-level attributes
      * https://github.com/sensu/uchiwa/blob/master/public/js/controllers.js#L54

There are a few disadvantages to this approach that I can think of:
* Complexities in implementing it
  * eg. The DC field would have to be supported
* More requests = more TCP overhead
  * Probably not _that_ much of a performance hit overall

@palourde have any thoughts on this? Is there anything that I'm missing?

**Comment by rmc3** [comment]
@amdprophet Would separating the events and stashes endpoints lead to computing the ```acknowledged``` field on events on the browser client-side? Doing so makes more sense to me, as it would allow some computational load to be offloaded to the client.

**Comment by rmc3** [comment]
Also +1 to this, makes architectural sense to me. Another Sensu dashboard project I've worked on took the monolithic data source approach that Uchiwa currently uses with ```/get_sensu```, and it caused many headaches.

**Comment by amdprophet** [comment]
@rmc3 silencing will be coming to Sensu core at some point as an event & client attribute if I'm not mistaken. It may be best to wait until then before making any large changes like this.

If for some reason silencing doesn't make it to Sensu core I'll have to reinvestigate. The old Sensu dashboard had helper methods within the event and client models that would return whether or not a stash existed for the event or client.

**Comment by palourde** [comment]
Added with 0.11.0
