### ISSUE TITLE
Support for filtering by status name

### ISSUE THREAD

**Issue by amdprophet** [sensu/uchiwa#221]
I'm not entirely sure if there's a way to do this already but it would be nice to be able to filter by critical, warning & unknown status names.

An easy way of doing this would be to implement a new attribute on each event (eg. status_name) which has the name of the status as the value. Filtering this way will have a downside of including events of other status types if "warning, unknown, etc." are in the output or any other searchable fields.

A proper method of only showing events for a specific status will require a more sophisticated search feature. Perhaps search overhaul should be it's own issue that can be worked on over a longer term.

**Comment by palourde** [comment]
Clients & Events views now have a status filter!

**Comment by roobert** [comment]
This feature is great but it would be even better if there was a filter for 'unhealthy' checks too, e.g: status >0.

Cheers!
