### ISSUE TITLE
accept graphana "graph" into uchiwa

### ISSUE THREAD

**Issue by jcmartins** [sensu/uchiwa#242]
I would like to see graphana metrics per host in Uchiwa

**Comment by portertech** [comment]
You could add chart image links to your Sensu client data.

**Comment by palourde** [comment]
As Sean proposed, you could have the graphs embedded. Here's a blog post about it: http://roobert.github.io/2014/11/03/Sensu-with-Embedded-Graphite-Graphs/

It would be an awesome feature to have the graphs automatically pulled out however it requires a considerable amount of work and there's already a work-around available (see above) so it won't be something I'll work on it soon.

**Comment by deepakhj** [comment]
Is there any easy way to create a link to an embedded graph? So we can display the thumbnail on either the client or check, then if you click on it, we can link to the Grafana dashboard containing that graph.
