### ISSUE TITLE
Displaying checks on Uchiwa

### ISSUE THREAD

**Issue by xlr-8** [sensu/uchiwa#243]
Hello,

I run through an interesting 'issue' recently. Let's say I have 2 servers that I monitor:
* The monitoring itself - called M
* And a random remote server - called A

If I have **standalone checks** with the same names on M and A (e.g. check_disk_slash), but different parameters (handlers, occurences, mutators, etc), then Uchiwa will display on the interface the check and the description of M's server and not of A.

I did not expect Uchiwa to know about the parameters of A's checks (though I think it could, as remote servers are returning every parameters/outputs as Json), but only the latest run and history of results.

Once I renamed the checks on the server M and restarted the services, I was able to have the view I expected and see the history/last check on A.

To give a better illustration, I attached:
* check_M: which is what I was seeing on server's A checks when clicking on the check
![check_m](https://cloud.githubusercontent.com/assets/1583638/5680535/c60dd01a-980e-11e4-8027-66c9d8ee70fc.png)
* and check_A: which was what I saw after the renaming, and what I was expecting to see.
![check_a](https://cloud.githubusercontent.com/assets/1583638/5680444/bdafb4ca-980d-11e4-92aa-5804d1351c27.png)

So this issue is to try:
* Having the display of the check of A and not the one on M server
* Having if possible the same description of M and A's checks

If I am not clear on my description, please let me know, as I did my best to be.

Finally the versions I'm using:
-uchiwa => 0.2.6-1
-sensu => 0.16.0-1
-librabbitmq0 => 0.0.1.hg216-1
-rabbitmq-server => 3.3.5-1
-redis-server => 2:2.4.14-1

Thank you,

**Comment by solarkennedy** [comment]
This is a "known" issue. The checks in the "checks" view are the server-defined checks. Not standalone:
https://uchiwa.io/#/faq

@palourde what if we just called that view "Server Checks"?

**Comment by palourde** [comment]
Hi @xlr-8 

Thanks for opening this issue. Part of the explanation is available [here](https://uchiwa.io/#/faq), under the *The checks list is incomplete; my standalone check won't appear!* section.

We also have an open discussion [here](https://github.com/sensu/uchiwa/issues/230) about the fact whether we should rename this section or remove it.

**Comment by xlr-8** [comment]
Thank your for the quick feedback, sorry for not checking https://uchiwa.io/#/faq, only thought of checking issues on github but pass through https://github.com/sensu/uchiwa/issues/230.

Cheers!
