### ISSUE TITLE
Feature to allow user to remove check history

### ISSUE THREAD

**Issue by dblessing** [sensu/uchiwa#246]
Related to #112 

Allow a user to 'delete' a defunct check by deleting the history. Currently if a check is removed from a client it will stay in dashboard indefinitely unless you remove the entire node and let all the valid checks re-establish themselves. This is bad though because then we lose all history for other checks.

**Comment by palourde** [comment]
Hi @dblessing 

Since the client history is stored on redis, we would need Sensu API to expose an endpoint to perform such operation. Otherwise, Uchiwa would have to connect directly to Redis, which isn't something we want.

Unfortunately, unless this feature is first added to the API, it won't be a feature available in Uchiwa.

Thanks for your suggestion!

**Comment by dblessing** [comment]
Hi @palourde. Thanks for your insight. What about implementing this by deleting the client itself via the API. This seems to be possible based on https://github.com/sensu/sensu/blob/497f317d8e85bdad0436b0c76f7654e6cb9f69cd/lib/sensu/api.rb#L368
I can't guarantee without testing but I would be surprised if the history wasn't removed with the client.

**Comment by palourde** [comment]
Hi @dblessing 

Maybe I didn't properly understood your suggestion but you can already delete a client from Uchiwa, just like this:

![capture d ecran 2015-01-15 a 22 10 41](https://cloud.githubusercontent.com/assets/4105580/5771054/95110316-9d03-11e4-83ab-5651befe59fc.png)

However, as you said, it will also delete the history of all other checks of this client.

**Comment by dblessing** [comment]
:stuck_out_tongue_closed_eyes: Wow sorry. Yes, you're right. Leave it to me to forget the actual reason I put in the request. I will pursue this feature with Sensu first.
