### ISSUE TITLE
js errors after creating stash

### ISSUE THREAD

**Issue by benh57** [sensu/uchiwa#247]
0. Open js console (ie firebug)
1. Click a client on the clients page
2. Click the speaker to create a stash
3. Click submit

--> Lots of JS errors appear:
Error: h.match is not a function
@http://localhost/bower_components/angular-sanitize/angular-sanitize.min.js:14:41
@http://localhost/js/filters.js:173:23
gb.prototype.filter/e@http://localhost/bower_components/angular/angular.min.js:173:86
hb["|"]@http://localhost/bower_components/angular/angular.min.js:162:41
gb.prototype.binaryFn/<@http://localhost/bower_components/angular/angular.min.js:171:1
jd</<.compile/</<@http://localhost/bower_components/angular/angular.min.js:194:191
Yd/this.$get</h.prototype.$digest@http://localhost/bower_components/angular/angular.min.js:110:236
Yd/this.$get</h.prototype.$apply@http://localhost/bower_components/angular/angular.min.js:113:360
m@http://localhost/bower_components/angular/angular.min.js:72:452
w@http://localhost/bower_components/angular/angular.min.js:77:463
ye/</B.onreadystatechange@http://localhost/bower_components/angular/angular.min.js:79:24

http://localhost/bower_components/angular/angular.min.js
Line 92

**Comment by palourde** [comment]
Hi @benh57 

Thanks for reporting this issue. I've been able to reproduce it. It seems that the stash is still submitted so it shouldn't break anything. I'll try to have a fix pushed as soon as possible.

Thanks for reporting this issue!
