### ISSUE TITLE
Creating a client silence stash does not set events associated with that client to acknowledged

### ISSUE THREAD

**Issue by rmc3** [sensu/uchiwa#250]
Creating a client silence stash does not set events associated with that client to acknowledged.

Steps to reproduce:

1. Silence a client with events in a non-OK state.
2. Events in a non-OK state for that client are still displayed on the dashboard and have ```"acknowledged": false```

It looks like the ```isAcknowledged()``` function in uchiwa/helpers.go just needs a conditional to check if a stash exists for the client (in addition to the check). If there's interest in having this implemented, I'm happy to put together a PR for this. However, if I'm reading https://github.com/sensu/uchiwa/issues/220 correctly, it sounds like splitting events and stashes into different endpoints may be being considered. Such a change may lead to the computation of which events are acknowledged happening on the client side, which would make this fix moot.

**Comment by palourde** [comment]
Hi @rmc3 

This behaviour is expected since silencing a client does not create a stash for every check. Showing associated events as acknowledged would prevent us to create additional stash for a particular check (I might want, for example, to silence the client for 15 minutes but have a check silenced for 24 hours).

Thanks

**Comment by rmc3** [comment]
Thanks for the clarification. This is a bit of a design disconnect for us as Sensu Dashboard (I believe, it's been a while since I used it) suppressed all events for silenced clients, so we expected Uchiwa would behave similarly. Are there any plans to implement a workflow in Uchiwa for easily suppressing all events from the event dashboard for a given client?

**Comment by amdprophet** [comment]
@rmc3 Sensu Dashboard showed whether or not a client was silenced on the events page. Perhaps we should implement something similar in Uchiwa.

![sensu_dashboard](https://cloud.githubusercontent.com/assets/120659/5843497/cd80a4ec-a161-11e4-9092-cccc3869b2c0.png)

**Comment by rmc3** [comment]
@amdprophet Thanks for the refresher! :)

My understanding of @palourde 's comment is that, since an event only has a single ```acknowledged``` field, Uchiwa would have no way of knowing whether the event was acknowledged because there was an event stash or a client stash. As a result, this would prevent Uchiwa from working with an event stash if the client was stashed, preventing the functionality he mentioned.

Would it be possible to add a second field indicating whether the client was stashed, in addition to the current field indicating whether the event is stashed? This might be a solution to this conflict between event and client stashes, and allow events from stashed clients to be filtered out of the event view.
