### ISSUE TITLE
Client list does not indicate that it is truncated/paginated

### ISSUE THREAD

**Issue by gwaldo** [sensu/uchiwa#252]
The client page (<code>/#/clients</code>) does not indicate that there are more clients than are currently listed.

It would be appreciated if a "more" or "next set" button were provided toward the bottom of the page, and an indication along the lines of "showing 50 of approximately 300 clients" was shown at the top

**Comment by zarry** [comment]
:+1:  Wouldn't hurt if searching covered all pages as well.

**Comment by dcws** [comment]
Yes, this.

**Comment by palourde** [comment]
This enhancement is available since 0.6.0 so I'll close this issue!

**Comment by gwaldo** [comment]
:+1:
