### ISSUE TITLE
Filtered events remain selected after being hidden

### ISSUE THREAD

**Issue by rmc3** [sensu/uchiwa#258]
Filtered events remain selected after being hidden. This results in operations (such as silencing an event) potentially being executed against events that are hidden. 

Steps to reproduce:

1. Set Hide => Silenced Checks to filter silenced checks.
2. Select an unsilenced event on the Events view by clicking its checkbox.
3. Silence the event via Actions => Silence/Unsilence At this point, the event will disappear from the view as it is filtered.
4. Select another unsilenced event by clicking its checkbox. 
5. Silence the event via Actions => Silence/Unsilence. Since the event silenced in step 3 is still selected (though hidden), this will unsilence that event while silencing the event selected in step 4.

**Comment by amdprophet** [comment]
@rmc3 good catch - I think this can be fixed by setting the `selected` attribute to false when an action is successfully performed on it. (ex. silence/unsilence, resolve)
