### ISSUE TITLE
clients view: "onclick" instead of "a href"

### ISSUE THREAD

**Issue by winks** [sensu/uchiwa#262]
Despite being a minor thing, this is my #1 pet peeve with Uchiwa:

Clients on `/#/clients` have this HTML code:
```html
<td class="main ng-binding">host-01.xyz.example.org</td>
```

and just selecting the hostname to copy it triggers visiting the client page (most probably some `onclick` event for the table cell.

Is there any good reason for not using `<a href` and behave like a normal web page?
If not, would you accept a PR doing that? Don't want to waste time going all over the code for this if it's not wanted.

**Comment by behrendsj** [comment]
I run into this issue also doing the same thing!

+1

**Comment by rmc3** [comment]
+1 as well

**Comment by palourde** [comment]
@winks I'm pretty sure we could replace the ng-click directive with the ng-href one (https://docs.angularjs.org/api/ng/directive/ngHref) by doing something like `ng-href="{{go(path)}}"` on all views.

I would gladly accept a PR!

**Comment by winks** [comment]
\o/ Thank you. And sorry I never followed up on this :/
