### ISSUE TITLE
Events page shows client events if is whole client is silenced

### ISSUE THREAD

**Issue by jaxxstorm** [sensu/uchiwa#264]
I'm not sure best way to describe this, but I'll try.

Instead of silencing an individual check, I silence a whole client. When I visit the events page and hide silenced checks, events for silenced CLIENTS still appear. I have to silence an individual check before it disappears from this page.

It would be awesome if I could silence a whole client, and have any check that fails be hidden from the events page

**Comment by rmc3** [comment]
This looks like it's related to https://github.com/sensu/uchiwa/issues/250

**Comment by amdprophet** [comment]
What do you think about having a second option, "Hide checks for silenced clients". cc @palourde

**Comment by rmc3** [comment]
@amdprophet, @palourde 's comment on #250 was 

> This behaviour is expected since silencing a client does not create a stash for every check. Showing associated events as acknowledged would prevent us to create additional stash for a particular check (I might want, for example, to silence the client for 15 minutes but have a check silenced for 24 hours).

I'm still very interested in adding an option for hiding events for silenced clients, but we'd still need to figure out how to implement that given that there's two potential sources for silencing but only one ```acknowledged``` field on events returned from ```/get_sensu```.

**Comment by amdprophet** [comment]
@rmc3 @palourde we should be able to add an acknowledged field to the client hash within an event and adjust templates to visually show if a client is silenced (and an option to hide silenced clients in this case).

**Comment by rmc3** [comment]
@amdprophet +1, an ```acknowledged``` field in the client hash seems like an elegant solution to me.

**Comment by palourde** [comment]
+1 for the acknowledged field in the client hash and the "Hide checks for silenced clients" option @amdprophet proposed!

**Comment by rmc3** [comment]
I'm working on a PR for this. @amdprophet, what sort of visual indicator were you thinking of when you said the following?

> adjust templates to visually show if a client is silenced

I've been thinking of a second muted/unmuted speaker icon in a column next to the event name. Thus, the column to the left of the client name would be repurposed to show whether the client is stashed, and the column to the left of the event name would show whether the event is stashed.

**Comment by amdprophet** [comment]
Didn't mean to assign this to myself, whoops.

@rmc3 yes - I like that idea.

**Comment by rmc3** [comment]
https://github.com/sensu/uchiwa-web/pull/12 and https://github.com/sensu/uchiwa/pull/268 should address this issue.

**Comment by rmc3** [comment]
Is there any interest in merging those PRs? If there are any issues that make them unsuitable, please let me know so I can fix them. Looking forward to seeing this feature in Uchiwa!

**Comment by palourde** [comment]
Hi @rmc3 

Sorry for the delay, everything looks good, simply didn't had time to test it. I'll try to have them merged today.

Thanks!

**Comment by rmc3** [comment]
@palourde Not a problem, thanks!

**Comment by rmc3** [comment]
The PRs have been merged. I believe they fix this issue.

**Comment by palourde** [comment]
Thanks to @rmc3 for adding this feature!
