### ISSUE TITLE
Check output throw angular parse exception

### ISSUE THREAD

**Issue by caparisi** [sensu/uchiwa#266]
Hello,

When a sensu client do a check which return a JSON object with URL encoded data in output field, the browser freeze and this JS error is thrown: 

![bug-uchiwa](https://cloud.githubusercontent.com/assets/8227938/6149118/c9c8f5b0-b206-11e4-8fc8-8ada7daf6511.jpg)

**Comment by palourde** [comment]
@caparisi Could you let us know which version of Uchiwa you are running?

**Comment by caparisi** [comment]
Uchiwa : 0.4.0
Sensu : 0.16.0

**Comment by palourde** [comment]
@caparisi Could you provide me an example of a JSON object that cause this particular issue? Thanks!

**Comment by caparisi** [comment]
Of course : 

{"request":[{"url":"http://test.com","name":"Nom de ma requete comme 'Test de l'injecteur'","user":"user","password":"password","input":"inputTest.xml","input_encoded":"%3C%3Fxml+version%3D%221.0%22+encoding%3D%22ISO-8859-1%22%3F%3E%0A%3Cy%3Ainput+xmlns%3Ay%3D%22http%3A%2F%2Fwww.yseop.com%2Fengine%2F3%22+xmlns%3Ai18n%3D%22http%3A%2F%2Fapache.org%2Fcocoon%2Fi18n%2F2.1%22+xmlns%3Aft%3D%22http%3A%2F%2Fapache.org%2Fcocoon%2Fforms%2F1.0%23template%22+xmlns%3Afi%3D%22http%3A%2F%2Fapache.org%2Fcocoon%2Fforms%2F1.0%23instance%22+xmlns%3Afd%3D%22http%3A%2F%2Fapache.org%2Fcocoon%2Fforms%2F1.0%23definition%22+xmlns%3Afb%3D%22http%3A%2F%2Fapache.org%2Fcocoon%2Fforms%2F1.0%23binding%22+%3E%0A++%3C%2Fy%3Ainput%3E%0A","keyword":"mot clé a rechercher dans la page","http_code":"code http attendu"}],"Message":"Mon Message de sortie"}

When sensu client send it, I can see on my browser console : 
![image](https://cloud.githubusercontent.com/assets/8227938/6185766/97449c12-b372-11e4-965d-41c6d1d667ac.png)

**Comment by palourde** [comment]
Hi @caparisi 

This issue was probably fixed with the upgrade to AngularJS 1.3 we made, I'm now able to show the input_encoded property without any issue:

![screen shot 2015-03-30 at 12 38 19](https://cloud.githubusercontent.com/assets/4105580/6901215/d7330d9c-d6d9-11e4-9cb2-62aec2d38edb.png)

You'll need to upgrade to at least Uchiwa 0.6.0. Let me know if you still have any issue!

Thanks
