### ISSUE TITLE
Ensure sorting of Clients lists is enabled by default

### ISSUE THREAD

**Issue by warmfusion** [sensu/uchiwa#267]
Each time I view the uchiwa clients dashboard the list of clients is unsorted which makes quickly finding a host (without using search obviously) a little harder than it needs to be.

In addition, when using a HAProxy to balance between two Sensu-API services to enable high-availability this unsorted list problem has the additional symptom of frequently re-ordering the list of clients after each callback between the api servers.

I think it'd be useful for the Clients table to start sorted by Name, such that the table view is always consistent, irrespective of the number of backends, and helps quickly locate servers in the list.

**Comment by palourde** [comment]
Hello @warmfusion 

The clients are sorted by default using their status. What we would probably need to do is to sort again using the client name, however I'm not sure how easily it can be done.

**Comment by robbydyer** [comment]
+1 I would vote for default alphabetical sorting in just about any list. Clients, checks, etc.

**Comment by warmfusion** [comment]
What if the table defaulted to using something like ``` orderBy:['status','host'] ``` it'd order by status (as it does now) but also the hostname?

If users then click the table headers to sort they'd overwrite the orderBy and only sort on a single column, but that would be what I (as a user) would expect - eg if i sort by the last-time column I don't expect to have other sorting involved.

**Comment by stefanandres** [comment]
+1 sort sorting alphabetically clients and checks. It's pretty hard to find any service if you have >10 checks.

**Comment by palourde** [comment]
It seems that this issue has been resolved with https://github.com/sensu/uchiwa-web/pull/21.
