### ISSUE TITLE
Feature Request: Mobile App

### ISSUE THREAD

**Issue by palourde** [sensu/uchiwa#269]

**Comment by shearn89** [comment]
Or, failing that, support for decent mobile rendering! :+1:

**Comment by amdprophet** [comment]
More mobile-friendly views are something we are planning on looking into down the road. Native apps (with the exception of WebView apps) are probably outside of the scope of this project.

**Comment by jtyr** [comment]
Responsive web design (adaptive layout) for Uchiwa would be really very useful. I hope this gets prioritized in the near future.

**Comment by erchn** [comment]
+1

**Comment by johntdyer** [comment]
+1

**Comment by jjuarez** [comment]
+1

**Comment by nsulistiyawan** [comment]
i have created (really) simple hybrid mobile app using sensu api, maybe you're interested :smile: 
https://github.com/nsulistiyawan/sensu-monitoring-app

**Comment by jtyr** [comment]
@nsulistiyawan We need app for Android, not for iOS ;o)

**Comment by johntdyer** [comment]
@nsulistiyawan  - Looks super cool !

**Comment by nsulistiyawan** [comment]
@jtyr : it's build on hybrid mobile application framework, so it can be build for ios or for android version.
maybe, it's still developed, currently the default style it's quite look an ios app. 

@johntdyer : thanks :smile:

**Comment by christianparpart** [comment]
any update or alternative resolution on this one? I'd vote this ticket up though. :-)

**Comment by kovvik** [comment]
+1

**Comment by nhooey** [comment]
@kovvik Please use GitHub's new "reaction" feature so we don't get notified.

**Comment by karottenreibe** [comment]
If you're still interested in a mobile dashboard for Sensu, I have created a free app: https://play.google.com/store/apps/details?id=be.rottenrei.sensuclient

**Comment by palourde** [comment]
Just a quick update regarding this feature.

We just released a new responsive web design included in 0.22 that should make Uchiwa usable on mobile devices.

From this point, I will not focus on building a dedicated native application but rather keep working on a responsive design and even look into progressive web apps stuff.

Because of that, I'll close this issue and I welcome anyone to create an issue if you have a suggestion on how to make Uchiwa responsive design better!
