### ISSUE TITLE
White screen when load uchiwa

### ISSUE THREAD

**Issue by jcmartins** [sensu/uchiwa#273]
Please,

move the directory of bower_componets  from /opt/uchiwa/src/bower_components to /opt/uchiwa/src/public/bower_components

tks
joao

**Comment by palourde** [comment]
Hi @jcmartins 

Did you installed Uchiwa 0.5.0 from the packages? If so, I recommend you to downgrade to 0.4.0 until new packages are available (we found an issue within the uchiwa-build cookbook that provoked this exact problem, which has just been fixed).

Sorry for the inconvenient.

**Comment by palourde** [comment]
0.5.1 packages are now available. Thank you for reporting this issue.
