### ISSUE TITLE
uchiwa debian packages repository

### ISSUE THREAD

**Issue by kosli** [sensu/uchiwa#274]
Until now i have used the following repository to install uchiwa:
deb     http://repos.sensuapp.org/apt sensu main
but it doesn't seem to get updated anymore, than the latest version of the uchiwa package is 0.4.0.

Is there an apt-repository of the debian packe on https://uchiwa.io/#/download or is something planned?

**Comment by Seraf** [comment]
+1 on this issue !

**Comment by palourde** [comment]
Hi! You should be able to grab the latest packages on the Sensu repositories within the next few days. I do not have direct access to these so once a new version of Uchiwa is released, it may take some time before the packages are uploaded.

**Comment by kosli** [comment]
Uchiwa 0.6.0 has been released, but in the repo there is still 0.4.0 .... whom could i contact? who is managing the repo?

**Comment by palourde** [comment]
@kosli  All packages are now available in the Sensu repository.

**Comment by kosli** [comment]
thanks. works fine!

**Comment by kosli** [comment]
@palourde the latest debian packages in the repo are 0.22. Could this be updated to the latest release 0.23.1 please? 
I see that the URL in the documentation (https://docs.uchiwa.io/getting-started/installation/) has changed now to a fastly.net URL?

**Comment by palourde** [comment]
Hi @kosli,

Yes the Sensu repositories have been updated, you should use the new URLs provided in the documentation.

Thanks,

**Comment by kosli** [comment]
thanks. i found the "problem" on my side. i haven't changed the URL properly, i used
 deb     https://sensu.global.ssl.fastly.net/apt sensu main
instead of
 deb     https://sensu.global.ssl.fastly.net/apt wheezy main

anywas, why does there exist a distribution called "sensu"? (which has only the version 0.22 package listed...)
