### ISSUE TITLE
Stash expiration value shown should be based on current time + stash.expire

### ISSUE THREAD

**Issue by rmc3** [sensu/uchiwa#278]
Currently, the getExpireTimestamp filter [calculates the expiration time](https://github.com/sensu/uchiwa-web/blob/master/js/filters.js#L104) by adding the expiration returned from the Sensu API for the stash to the time stamp in the stash's contents. At least on Sensu 0.13 (this may have changed in more recent versions, but I don't see appreciable changes in Sensu::API::Process), the expire TTL returned from the API is the number of seconds until the stash key expires in Redis. 

As a result, the value that is returned does not match the actual time when the stash should be expected to expire, since the value of the expiration returned from the Sensu API is constantly decrementing as time passes, while the time stamp stays the same. Additionally, the dependence on a "timestamp" key in the stash's value prevents Uchiwa from properly rendering the expiration time stamp for stashes that do not have that key.

To rectify it, it seems like it would be simplest to change that code to:

```
var expiration = (moment.now().valueOf() + stash.expire) * 1000;
```

Thoughts?

**Comment by rmc3** [comment]
I neglected that moment.now().valueOf() returns milliseconds, so it should be something more along the lines of:

```
var expiration = moment.now().valueOf() + (stash.expire * 1000);

**Comment by rmc3** [comment]
```moment().unix()``` would probably work too.

**Comment by rmc3** [comment]
Will have a PR out for this in a moment. Would love if someone could confirm my assumptions about this applying to Sensu > 0.13.1 :)

**Comment by palourde** [comment]
The PR has been merged. Thanks you!

**Comment by kaos** [comment]
There is one major miscalculation here, and that is that this is only correct at the time the stash was fetched from the server... if you poll every 30 seconds, you still get a moving expiration time.. 

I propose to instead calculate a fixed expiration time, once, when the data is fetched from sensu api by the uchiwa backend process.
