### ISSUE TITLE
Feature request: Client display names

### ISSUE THREAD

**Issue by neilprosser** [sensu/uchiwa#280]
I wanted to create an issue to see whether this idea was something that might be welcome.

My justification for this is that Sensu wants us to use a unique name for API operations (like deleting clients) but actually we might want to use something more descriptive when displaying clients in Uchiwa (for example `application-environment-01` when the best unique identifier is the IP address). It looks like it's easier for Uchiwa to be able to prefer a `displayName` property (or similar if there's a preferred name) over the existing `name` property over tweaking the Sensu APIs.. The `name` property would still be used for interacting with the API by Uchiwa but every time we see the client it would use the `displayName` (if it exists). As users of Sensu we'd just add a `displayName` property to our clients which Sensu would ignore and pass to Uchiwa, which would then use it.

I've identified how I might go about doing this. It basically looks like going through the front end partials and replacing `{{ client.name }}` with `{{ name(client) }}` where the `name(client)` function returns `client.displayName` if present, otherwise `client.name`.

Is this something that's likely to be accepted? Is there a better way of doing this? My Angular is rusty but I'm happy to have a go if it's likely to be useful to people.

**Comment by palourde** [comment]
Hi @neilprosser

We already implemented [something similar](https://github.com/sensu/uchiwa/pull/134) for the the events view since there was a [clear need](https://github.com/sensu/sensu/issues/541) for it.

I'm not convinced of the need for other views but I'm still open to it if there's a strong desire from the community for such feature.

**Comment by hashbrowncipher** [comment]
Yelp would appreciate this feature.  Our hostnames are often semantically meaningless, but we enrich them to create 'display names'.  Display names can change, so they are unsuitable for use as a Sensu client name, which must not change during a client's lifetime.  As a result, we define a stable Sensu client name, and then use the [display name](https://github.com/Yelp/sensu_handlers/blob/2a2ba7fc8b3637ce0586515f81e02663052d978d/files/base.rb#L72) within our handlers to provide maximal context to the user.

**Comment by joerayme** [comment]
I'd like to +1 this – we have a similar situation to Yelp and are using a custom attribute as the client identifier in our handlers. It would be really useful to be able to use this in the dashboard view as well.

**Comment by annaplotkin** [comment]
Thanks for the suggestion! This functionality will be reviewed for inclusion in Sensu Go.
