### ISSUE TITLE
Having a sensu-client named "client" generates an error on Uchiwa

### ISSUE THREAD

**Issue by epierotto** [sensu/uchiwa#287]
Testing the sensu-client config I realized that having a client with the name "client" generates an error on Uchiwa.

On the sensu-client config.json
![image](https://cloud.githubusercontent.com/assets/5226270/6634396/1f73beba-c958-11e4-8bc0-097db85a7013.png)

The sensu-api response
![image](https://cloud.githubusercontent.com/assets/5226270/6634411/5dd43ce8-c958-11e4-8bd9-8af5e74447a7.png)

Error on Uchiwa 0.5.1
![image](https://cloud.githubusercontent.com/assets/5226270/6634446/fe0311c6-c958-11e4-8ce2-ce3826857573.png)

Error on Uchiwa 0.6.0
![image](https://cloud.githubusercontent.com/assets/5226270/6634438/cdd96fb8-c958-11e4-88fe-2730ac3b97c8.png)

**Comment by epierotto** [comment]
It is not a major issue, it's just a heads up.

**Comment by palourde** [comment]
Hi @epierotto, it looks like it's actually an issue with the Sensu API itself:

```
# curl -I http://10.73.0.10:4567/clients/client
HTTP/1.1 200 OK
Content-Type: application/json;charset=utf-8
Content-Length: 115
Connection: keep-alive
Server: thin 1.5.0 codename Knife

# curl -I http://10.73.0.10:4567/clients/client/history
HTTP/1.1 404 Not Found
Content-Type: application/json;charset=utf-8
Content-Length: 0
Connection: keep-alive
```

I recommend you to open an issue directly on [sensu/sensu](https://github.com/sensu/sensu).

Thanks!

**Comment by epierotto** [comment]
Done!
Thanks for your time @palourde
