### ISSUE TITLE
Issue with datacenter alert badges due to invalid json

### ISSUE THREAD

**Issue by dtest** [sensu/uchiwa#291]
The current implementation of adding alerts based on the /sensu/health/sensu API call breaks if the result is not JSON.

I had an issue with my NGINX proxy that caused /sensu/health/sensu to redirect to the events page. The result was something like this:

![screen shot 2015-03-17 at 5 29 18 pm](https://cloud.githubusercontent.com/assets/700224/6698018/2e13372c-cccb-11e4-861a-6eaf3b4c825c.png)

I might expect a single alert indicating there's a problem with API call if it's not JSON.

**Comment by palourde** [comment]
Hi @dtest 

This bug has been resolved and the fix will be available within the next release.
