### ISSUE TITLE
Disable autocapitalize and autocorrect in login username input

### ISSUE THREAD

**Issue by kobayaashi** [sensu/uchiwa#296]
Most mobile device browsers autocapitalize and autocorrect form text inputs unless disabled in the input tag. As a result, "admin" entered in a mobile browser like Safari on an iphone gets sent as "Admin", and we see "Authentication failed: invalid user 'Admin' or invalid password" entries in uchiwa.log

**Comment by palourde** [comment]
Reference: http://sja.co.uk/controlling-which-ios-keyboard-is-shown
