### ISSUE TITLE
Silence checks according subscription name

### ISSUE THREAD

**Issue by panda87** [sensu/uchiwa#297]
I think it would be nice to add a page with a list of all the checks, but with the ability to silence them according their subscription name, like did in the clients page.

For example, I have 3 nodes of DB and each node has 2 subscriptions, 1. for CPU etc. 2. for DB checks.
I want to silence the all the DB checks for my 3 nodes - according their subscription name, but keep the first subscription name open (unsilenced).

Another way is to silence only a specific subscription which will silence all the contains checks - just choose the subscription and the node names.

it's very useful for version upgrade and when you want to silence a specific subscription for more than one node.

Thanks,
D.

**Comment by palourde** [comment]
This has been introduced with the new Sensu built-in silencing and is available within Uchiwa since the 0.18 release!
