### ISSUE TITLE
Bypass authentication

### ISSUE THREAD

**Issue by NicolasLM** [sensu/uchiwa#299]
Unlike issue #35 I'm trying to completely bypass the way Uchiwa handles users. I manage authentication myself on the proxy using HTTP Auth basic.

One quick solution would be to share a dummy user/password with all the already authenticated users. However this breaks because Uchiwa expects the header "Authorization" to have a certain value which is already used by the proxy.

I've checked the auth library, trying to turn off authentication by setting `"auth": "None"` in Uchiwa config. This seems to not bypass auth, but just forbid login.

**Comment by palourde** [comment]
Hi @NicolasLM 

You simply have to leave empty the admin & pass values or remove them from the *uchiwa* object on your configuration file, as shown on the first example [here](http://docs.uchiwa.io/en/latest/configuration/uchiwa/). Thanks!

**Comment by NicolasLM** [comment]
How could I miss that? Thank you very much, it works.
