### ISSUE TITLE
Scheduled stash

### ISSUE THREAD

**Issue by palourde** [sensu/uchiwa#3]
Add a crontab like scheduler to add temporary stash every x.

**Comment by xlr-8** [comment]
Hello,

I was wondering why this issue has been closed?
I believe that would be a great feature to have planned stash/downtime; rather than taking the current timestamp.

Is this a Sensu limitation, or Uchiwa?

Cheers,

**Comment by palourde** [comment]
Hi @xlr-8 

This issue has been closed in favor of https://github.com/sensu/uchiwa/issues/4

**Comment by xlr-8** [comment]
Indeed, thank you for the heads up
