### ISSUE TITLE
Display standalone checks details

### ISSUE THREAD

**Issue by jaimegago** [sensu/uchiwa#302]
Currently standalone checks only get "last execution" and "history" whereas it seems "regular" checks get all the attributes, including the "command" one which I found very useful when troubleshooting. It'd be great to have all the check attributes whereas it's a standalone or not.

![screen shot 2015-04-06 at 4 27 10 pm](https://cloud.githubusercontent.com/assets/1704368/7014450/d8bdc134-dc79-11e4-89db-f0635466321a.png)

**Comment by palourde** [comment]
Hi @jaimegago 

Unfortunately it isn't possible, as explained on the *Why can't I see the details of a standalone check?* entry of the FAQ, that you can consult [here](http://docs.uchiwa.io/en/latest/faq/faq/#checks). Let me know if you have any question.

Thanks
