### ISSUE TITLE
Datacenter link is broken at 0.7.1

### ISSUE THREAD

**Issue by sumit-sngpt** [sensu/uchiwa#303]
I have installed the latest Uchiwa 0.7.1 and it seems the "Datacenter" panel at the left of dashboard is broken though I have configured around Four Datacenters.

**Comment by palourde** [comment]
Hi @sumit-sngpt 

Did you installed 0.7.1 from the source or the packages? Also, did you tried to clear your browser cache?

**Comment by sumit-sngpt** [comment]
I installed it from the RPM packages. I cleared the cache and it works fine now. Thanks!
