### ISSUE TITLE
Feature request: Snapshot of current active alerts

### ISSUE THREAD

**Issue by sumit-sngpt** [sensu/uchiwa#304]
New Feature: It would be nice to get a snapshot of current Active alerts and Silenced alerts, may be inform of doc which can be downloaded through Dashboard.

**Comment by amdprophet** [comment]
@sumit-sngpt this is something we're working on adding to Sensu Enterprise Dashboard which will be shipping with Sensu Enterprise. We are open to accepting pull requests that will add this functionality to Uchiwa.
