### ISSUE TITLE
Resolved events not clearing from clients view

### ISSUE THREAD

**Issue by poolski** [sensu/uchiwa#309]
Running the latest Uchiwa and Sensu version, checks that have alerted and subsequently cleared remain in the Events list. 

They're listed green and the "occurrences" just ticks up with each run of the check as though to inform me that "I've been OK for X amount of time". Is this supposed to happen?

![selection_103](https://cloud.githubusercontent.com/assets/1942093/7178172/a090fb5c-e424-11e4-8e40-b3b914a0861f.png)

**Comment by roobert** [comment]
+1

**Comment by roobert** [comment]
Screenshot:
![uchiwa](https://cloud.githubusercontent.com/assets/226654/7250968/861237f2-e81e-11e4-8a8e-2619b9f3db2b.png)

**Comment by poolski** [comment]
Still a problem in 0.8.1 I fear.

![selection_106](https://cloud.githubusercontent.com/assets/1942093/7591268/ca43b638-f8c4-11e4-93fa-63533abdcd8c.png)

**Comment by palourde** [comment]
@poolski

Please make sure to restart the Uchiwa process and clear your browser cache after the upgrade.

Thanks

**Comment by poolski** [comment]
Will try it and let you know the results tomorrow!

**Comment by poolski** [comment]
No, still doing it. Restarted uchiwa, restarted sensu-api and cleared all cache/cookies/etc on multiple browsers.
