### ISSUE TITLE
Remove metrics from "Checks" section

### ISSUE THREAD

**Issue by luisdalves** [sensu/uchiwa#310]
Hi,

I think should be a nice if all metrics are placed in a new side button on the left. So we will see only checks in the checks sections and only the metrics in the metrics section.

Regards

**Comment by palourde** [comment]
I tend to believe that we should add some additional filters to the checks view instead, so you can easily switch from non-metrics to metrics checks.

**Comment by portertech** [comment]
Important to note that a single check can ship metrics and compare those metrics to static alert thresholds.

**Comment by luisdalves** [comment]
I'm asking for this because when you have a lot of metrics and checks, uchiwa ui is not clear.
![uchiwa_example](https://cloud.githubusercontent.com/assets/11091389/8085459/a6a604ca-0f66-11e5-9694-b098b1dfe0ac.png)

**Comment by alexgear** [comment]
Checks section is all messed up when you have more than 30 checks+metrics definitions, so some kind of filtering or metrics separation would be really helpful.

**Comment by goriparthi** [comment]
+1 This would be very useful.

**Comment by p1hr** [comment]
Also looking forward to this feature.
Is there any plan on implementing it in the near feature ?

**Comment by calebhailey** [comment]
Related improvement coming in Sensu 0.24: https://github.com/sensu/sensu/issues/1025

**Comment by luisdalves** [comment]
great!
