### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by adem82** [sensu/uchiwa#311]
Hi,

Sensu - uchiwa - checks - clients or everything was working perfectly. Something happened and the server stoped working. Then, I restarted the server and checked that all the services/servers are running. But, I don't seem getings alert e-mails from sensu monitoring system. I checked the log files, and finally found that uchiwa log file gives the following error: 
{"name":"uchiwa","hostname":"fiweb06","pid":2172,"level":50,"msg":"Processing Sensu API Sensu returned \"Error: socket hang up\"","time":"2015-04-21T08:13:30.407Z","src":{"file":"/opt/uchiwa/usr/src/uchiwa/lib/dc.js","line":85},"v":0}

I check out the internet that i have not found any concrete solution for the issue. 

Have you guys faced the same kind of issue before?

br,

**Comment by palourde** [comment]
Hi @adem82 

It looks like you are using an older version of Uchiwa (<= 0.2.6) which was written in Node. I highly recommend you to upgrade to the latest Uchiwa version, if possible, since we now have a much more stable codebase.

Thanks!

**Comment by adem82** [comment]
Thank you palourde! 

I will upgrade the whole things possibly. 
Great that you released the stable version. 

Regards!
