### ISSUE TITLE
dashboard page

### ISSUE THREAD

**Issue by chromerobv** [sensu/uchiwa#312]
one of the things that caught my eye with uchiwa was a dash page i saw when searching around.
a couple reviews and google searches show a front page with very obvious alert columns.
it can be seen here.

https://beingasysadmin.files.wordpress.com/2014/05/uchiwa1.png?w=696

does this exist anywhere? is there someway to see it i am not seeing myself?

thanks in advance!!!

**Comment by southwolf** [comment]
Sadly, it's an old version of Uchiwa... Current version of uchiwa hasn't done that yet.

**Comment by chromerobv** [comment]
that is unfortunate. the plan was to have that on a monitor on the wall. the current screen doesn't really work well for that. anyone know of a noc type dash that can be used with sensu ?

**Comment by palourde** [comment]
See https://github.com/sensu/uchiwa/issues/75
