### ISSUE TITLE
Events not being rendered properly

### ISSUE THREAD

**Issue by codesplicer** [sensu/uchiwa#318]
Hi,

I'm seeing a lot of these errors in the uchiwa logs:

```{"Date":"2015-04-30T14:05:39.814933251Z","Level":"warning","Src":{"Func":"github.com/sensu/uchiwa/uchiwa.BuildEvents","Line":48},"Output":"Could not assert event's client name from map[name:\u003cnil\u003e]"}```

And the events tab in uchiwa doesn't render any events as a result. The rest of the views appear fine.

OS: Ubuntu 12.04
Sensu Server/API: v0.16.0-1

**Comment by palourde** [comment]
Hi @codesplicer

Thanks for reporting this issue. Could you let me know the version of Uchiwa you are running and also, do you see any error messages within the Sensu API log?

Thanks

**Comment by codesplicer** [comment]
Hi @palourde, I managed to resolve this. Turns out that when upgrading sensu versions, in my case going from 0.12.x to 0.17.x, the event format had changed slightly. I flushed the redis DB and let it repopulate, which resolved this issue.

**Comment by palourde** [comment]
Thanks for the update, I'm glad you were able to resolve this problem!
