### ISSUE TITLE
Display the last check result for all checks

### ISSUE THREAD

**Issue by palourde** [sensu/uchiwa#322]
Since Sensu 0.18.0, the last check result is provided even if the check status `== 0`, which isn't supported by Uchiwa.

**Comment by krmcbride** [comment]
+1

**Comment by LeonLee88** [comment]
Hi guys, could you please tell me how to config it to show all outputs. At this moment I can't find any documents about this feature.

**Comment by palourde** [comment]
Hi @LeonLee88 

You simply need Sensu >= 0.18.0 and Uchiwa >= 0.9.0 to automatically see all outputs. Also make sure to restart Uchiwa if you just upgraded. Let me know if you still have any trouble.

**Comment by LeonLee88** [comment]
Hi @palourde , it works! Thank you. But it seems the outputs only show up when I am on the page of the checks list of a client, and it won't if I click on a specific one. That would not be a problem when it's a simple and short output, but sometimes I do have a long output which I want to show and see the details. It would be more preferable if you guys would like to do some enhancement for it in the future.

**Comment by danielpondruff** [comment]
OK output on check detail site was nice... please add :)

**Comment by mnguyen1289** [comment]
Any update on this?  It would be great to get the check output to show up on actual check info page.
