### ISSUE TITLE
404's for all requested content

### ISSUE THREAD

**Issue by cmacrae** [sensu/uchiwa#323]
Hey there, it's me again, the reporter of #272 :)

I finally got some time to revisit the Ansible role I'd been writing for the deployment of Sensu & Uchiwa on SmartOS.

Unfortunately, it seems there are some issues with the latest code-base.
My deployment code hasn't changed, so these must have been introduced at some point between the closing of #272 and now.

I appreciate Uchiwa probably isn't tested much (if at all) on SmartOS, so, I'm here to help expose these issues - hopefully we can work towards a resolution!

Cool, so, enough blabbering, onto the issue report:

When attempting to visit Uchiwa on the host that I've spun up, I simply get a blank page.
You can see that a site is being served, because the browser loads it, and I'm able to establish a TCP session:
```
$ telnet sensu.cmacr.ae 3000
Trying 10.19.3.18...
Connected to sensu.cmacr.ae.
Escape character is '^]'.
  
HTTP/1.1 400 Bad Request

Connection closed by foreign host.
```
Not to mention, the process is up and running fine - `ps` & `netstat` confirm it's running and listening, and there are no issues reported in the logs.

Upon inspection of my browser's web console, I can see the following:
```
GET http://sensu.cmacr.ae:3000/bower_components/angular-gravatar/build/angular-gravatar.js       [HTTP/1.1 404 Not Found 1ms]
GET http://sensu.cmacr.ae:3000/bower_components/uchiwa-web/js/app.js      [HTTP/1.1 404 Not Found 1ms]
GET http://sensu.cmacr.ae:3000/bower_components/uchiwa-web/js/constants.js      [HTTP/1.1 404 Not Found 1ms]
GET http://sensu.cmacr.ae:3000/bower_components/uchiwa-web/js/controllers.js     [HTTP/1.1 404 Not Found 0ms]
................
```
There are a bunch more, but no point including them.

My `etc/config.json`
``` json
{
    "sensu": [
        {
            "name": "dc_name",
            "host": "localhost",
            "ssl": false,
            "port": 4567,
            "user": "admin",
            "pass": "********",
            "timeout": 5000
        }
    ],
    "uchiwa": {
        "user": "admin",
        "pass": "********",
        "port": 3000,
        "stats": 10,
        "refresh": 10000
    }
}
```
I've tried with node versions `v0.10.33` & `v0.10.38`.
Go version is `go1.3.2`

If inspection of messages from a web console will help, you can reach my test instance at: https://sensu.cmacr.ae (sorry, self-signed cert :))

Thanks in advance for any help with this at all, I'd really appreciate it!

**Comment by palourde** [comment]
Hi @cmacrae

What do you see when you run `bower list`? 

I assume you also upgraded uchiwa-web to 0.8.1 so you should see the file `public/bower_components/angular-gravatar/build/angular-gravatar.js` from the uchiwa folder?

**Comment by cmacrae** [comment]
Hey @palourde :)

This is all running from fresh code.
Here's a quick summary answer to your questions above:
```
[root@sensu /opt/uchiwa/go/src/github.com/sensu/uchiwa]# ls public/
index.html

[root@sensu /opt/uchiwa/go/src/github.com/sensu/uchiwa]# sudo -u sensu node_modules/bower/bin/bower list
bower check-new     Checking for new versions of the project dependencies..
uchiwa /opt/uchiwa/go/src/github.com/sensu/uchiwa
└── uchiwa-web not installed
```
So it doesn't appear uchiwa-web is installed.

I'm using the same snippet of Ansible code I'd been using before to build/deploy uchiwa:
``` yaml
  - name: Build and deploy Uchiwa
    npm: path={{ uchiwa_path }}/go/src/github.com/sensu/uchiwa
         production=yes ignore_scripts=no
```

**Comment by palourde** [comment]
I would suggest you to investigate the *npm* command by running it manually. It might be related to a temporarily outage with the bower registry, hard to say.

The *deb* and *rpm* packages are built with the [npm command](https://github.com/sensu/uchiwa-build/blob/master/recipes/build.rb#L73) on a fresh machine so I'm pretty confident that the uchiwa-web 0.8.1 bower package is available and working.

Let me know if you find anything!

**Comment by cmacrae** [comment]
Sure, sounds like the right direction to go in. It's how I'd been debugging/developing before: do it in the shell first, replicate it in Ansible.

I should get some time to play with this today, so I'll let you know the outcome :)

**Comment by cmacrae** [comment]
Whelp... after switching to doing a simple shell execution from Ansible, instead of using their `npm` module, this works. Though, the same behaviour is exhibited through the first run: an execution of `npm install --production` is run, this results in the initial behaviour reported in this issue. Following a second run through, the deployment seems to run successfully and I'm able to access Uchiwa.

Fortunately, Ansible's `shell` module has a param `creates` which I have set to the `public/bowercomponents`, which means the execution will happen until that directory exists.
This works for now, but I'll want to tackle getting it to deploy in one run.

Nonetheless: this clearly isn't an issue with your code, simply my deployment.
Thanks for helping me track this down! :) 

I'll be sharing my Ansible stuff on my GitHub soon, just a few more things to implement.

**Comment by palourde** [comment]
Awesome, thanks for the update!
