### ISSUE TITLE
Something is cached for too long on the Info page

### ISSUE THREAD

**Issue by FlorinAndrei** [sensu/uchiwa#324]
Upgraded from 0.7.x to 0.8.0

Restarted the uchiwa service on the server.

Logged into the uchiwa site again. On the Info page, the version displayed was still 0.7.x.

I've tried to logout / log back in, stop the service / start the service, close browser tab / reopen and relogin, etc. Nothing helped.

When I finally did a simple refresh in the browser, then the correct version 0.8.0 was shown in the browser. Sounds like something is allowed to be cached for too long in the browser.

**Comment by palourde** [comment]
This behaviour is expected (I don't know however the expected behaviour of your browser once it's closed/reopen) in order to avoid downloading the same static content and improve the user experience.

I've added some documentation about the upgrade process here: http://docs.uchiwa.io/en/latest/upgrading/

**Comment by FlorinAndrei** [comment]
Also, the "All Datacenters" drop down menu on the front page was disabled for a while after the upgrade, and then it magically started working again. I assume this was also something cached for too long.

You'll have to strike a balance somewhere. The user experience is also negatively impacted by things not working properly.

**Comment by palourde** [comment]
I can totally understand, that's why I added some additional instructions on the documentation regarding the upgrade process.

I would gladly accept any PR that could prevent the need to perform a full page reload after an upgrade.
