### ISSUE TITLE
can't display injected checks (custom JSON into localhost:3030)

### ISSUE THREAD

**Issue by pdaugavietis** [sensu/uchiwa#325]
when clicking on the event raised from an injected check/event (injected thru listener on 3030), the GUI doesn't display the event defs -- what fields are mandatory for that functionality to work?   I missed the docs on this somewhere, or they don't exist :)

either way - please advise...

**Comment by palourde** [comment]
Hi,

Please provide us with some basic information about your setup (e.g. Sensu and Uchiwa versions).

Also, can you confirm that you see this information on the Sensu API itself? If so, it would be nice if you could include a concrete example?

Thanks

**Comment by pdaugavietis** [comment]
Sensu 0.18.0, Uchiwa 0.8.1

Example insert: 
echo '{"name": "check_respawn", "output": "Redis-commander service respawned", "status": 2, "handlers": ["twitter"], "ocurrences":1, "interval":1, "flapping":false}' | nc localhost 3030
OR
echo '{"status": 2, "output": "something is down - 333.222.444.111:8080", "name": "F5-BIGIP-COMMON-MIB-bigipGtmPoolDisabled", "handlers": ["default"]}' | nc localhost 3030

Shows up in event list, but NOT in client summary list.

Sensu API:  http://localhost:4567/events/test/check_respawn
{"id": "927ce4e8-baa7-4821-9ff6-42a92aa7a046",
"client": {
"name": "test",
"address": "localhost",
"subscriptions": 
["test"],
"version": "0.18.0",
"timestamp": 1431309219},
"check": {
"name": "check_respawn",
"output": "Redis-commander service respawned",
"status": 2,
"handlers": 
["twitter"],
"ocurrences": 1,
"interval": 1,
"flapping": false,
"issued": 1431309237,
"history": 
["2"],
"total_state_change": 0},
"occurrences": 1,
"action": "create"}

It looks like (right now) - defined checks (like memory in example setup) display fine, but the inserted ones aren't drillable (or resolvable/silencable) from the main Uchiwa events list

**Comment by pdaugavietis** [comment]
Oops - correction - they ARE resolvable by checkbox/action menu - just not drillable (which then asks - is that by design or not?)

**Comment by palourde** [comment]
@pdaugavietis 

Do you see it within the client's history on the API? (http://localhost:4567/clients/test/history).

Uchiwa build the client summary page from the latest API endpoint and then, correlate each check within the history to a possible event.

Thanks

**Comment by portertech** [comment]
I just pushed https://github.com/sensu/sensu/pull/943 that defaults the check executed timestamp, as this timestamp is used by Sensu Core for various features.

**Comment by pdaugavietis** [comment]
I do see the history once resolved, but once another alert is raised, it leaves the history.

**Comment by portertech** [comment]
It does look like https://github.com/sensu/sensu/pull/943 will resolve this issue.

**Comment by palourde** [comment]
Hi @pdaugavietis, do not hesitate to let us know if you still have this specific issue with Sensu 0.18.1.
