### ISSUE TITLE
Display JIT clients

### ISSUE THREAD

**Issue by jared-k** [sensu/uchiwa#327]
With the new JIT clients feature in Sensu 0.18 it would be useful to add these to the Clients page (or maybe create a new page for them). If an event fires for a JIT client it shows up on the Events page with the correct client name, but otherwise the only way to view the status of these is to look at the Sensu client that is performing the checks on their behalf.

I don't know exactly how this would work but the functionality would be valuable in any case.

**Comment by warmfusion** [comment]
I've just started using JIT clients and they're displaying for me in Uchiwa as expected..

Sensu Server - 18.1
Uchiwa Dash - 8.1

**Comment by portertech** [comment]
Sensu 0.18.1-1 included a fix for the client socket check attribute defaults. Please upgrade to 0.18.1-1 :+1:

**Comment by jared-k** [comment]
Confirmed - upgraded to 0.18.1 and the JIT clients are displayed on the Clients page. Much appreciated @portertech, this is a very valuable feature.
