### ISSUE TITLE
Resolved issues still not clearing from list

### ISSUE THREAD

**Issue by poolski** [sensu/uchiwa#329]
Referenced in #309 which is now closed - and supposedly fixed in 0.8.0, but I'm still experiencing the issue with resolved events not clearing from the active events list, despite being in the "resolved" state. 

Any joy?

**Comment by ashish1099** [comment]
Hi, 

Yes I'm experiencing the same, the api status is o, but its still hanging in the event list.

```
[root@sensu ~]# rpm -qa | grep sens
sensu-0.18.1-1.x86_64

[root@sensu ~]# rpm -qa | grep uchi
uchiwa-0.8.1-1.x86_64
```

This the sensu-client log output
```
{"timestamp":"2015-05-22T14:27:05.581789+0100","level":"info","message":"received check request","check":{"name":"check-cpu","issued":1432301225,"command":"/etc/sensu/checks/check-cpu.rb"}}
{"timestamp":"2015-05-22T14:27:07.555336+0100","level":"info","message":"publishing check result","payload":{"client":"abc.example.com","check":{"name":"check-cpu","issued":1432301225,"command":"/etc/sensu/checks/check-cpu.rb","executed":1432301225,"duration":1.973,"output":"CheckCPU TOTAL OK: total=10.0 user=7.0 nice=0.0 system=3.0 idle=90.0 iowait=0.0 irq=0.0 softirq=0.0 steal=0.0 guest=0.0\n","status":0}}}
```

**Comment by palourde** [comment]
Unfortunately I'm unable to reproduce this issue with the latest release (0.8.1) so I'll need your help to investigate.

Next time you see a resolved event into your events list, could you provide me the results from the following endpoints:
- http://sensu-api-url:4567/events
- http://uchiwa-url:3000/get_sensu

Thanks!

**Comment by poolski** [comment]
http://sensu-api-url:4567/events:

```json
{
  "id": "1c1707f8-9bb1-4d52-b54b-31c194332f54",
  "client": {
    "name": "hostname.network.net",
    "address": "10.0.0.199",
    "bind": "127.0.0.1",
    "subscriptions": [
      "common"
    ],
    "safe_mode": false,
    "keepalive": {
      "high_flap_threshold": 20,
      "low_flap_threshold": 5,
      "refresh": 14400,
      "thresholds": {
        "critical": 120,
        "warning": 90
      }
    },
    "handlers": [
      "default"
    ],
    "version": "0.18.0",
    "timestamp": 1432507279
  },
  "check": {
    "command": "check-ram.rb",
    "interval": 60,
    "handlers": [
      "default"
    ],
    "refresh": 1209600,
    "standalone": true,
    "high_flap_threshold": 20,
    "low_flap_threshold": 5,
    "name": "os-memory",
    "issued": 1432507293,
    "executed": 1432507293,
    "duration": 0.138,
    "output": "CheckRAM OK: 87% free RAM left\n",
    "status": 0,
    "history": [
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0"
    ],
    "total_state_change": 0
  },
  "occurrences": 32659,
  "action": "flapping"
}```

I don't have access, currently, to the sensu backend itself, so I'll post the other result when I do

**Comment by jcmcken** [comment]
I was also still seeing this issue. I think if you're having this problem, you need to stop everything and issue a ``redis-cli flushall`` to clear out the cached event info. For me, the events did not just go away on their own after the upgrade (and full restart).

**Comment by poolski** [comment]
@jcmcken that seems to have fixed it, thanks!

**Comment by ashish1099** [comment]
@jcmcken :+1:

**Comment by jcmcken** [comment]
Hmm, actually I still might be seeing this issue. After doing the above, some new alerts came in and then resolved. Those alerts are still showing (as green) in the dashboard. I thought it might be because they're flapping, but their entire history window is now ``0``'s and they still haven't disappeared.

**Comment by palourde** [comment]
@jcmcken Do you also see these resolved issues in the `/events` endpoint of your Sensu API? If so, I would recommend you to open an issue on the Sensu project so we can better assist you with this issue!

**Comment by jcmcken** [comment]
Thanks @palourde, you're right, this is probably not an ``uchiwa`` issue. I think the problem is in the logic which clears flapping alarms, I'll take a look at it and submit an issue over to Sensu.
