### ISSUE TITLE
theme setting is not sticky between sessions

### ISSUE THREAD

**Issue by FlorinAndrei** [sensu/uchiwa#331]
If I go into admin / settings and I change the theme, the setting is lost the next time I open the browser. As such, it's pretty much useless, since it's boring to set it every single time I fire up the browser.

**Comment by ROunofF** [comment]
I just opened PR over uchiwa-web for this : https://github.com/sensu/uchiwa-web/pull/49

**Comment by palourde** [comment]
Thanks @ROunofF for resolving this issue! It will be available within the next release.
