### ISSUE TITLE
Events/clients/checks/stashes should be datacenter specified

### ISSUE THREAD

**Issue by khuongdp** [sensu/uchiwa#334]
Hi 

Events/clients/checks/stashes/... should match only for the selected datacenter. It is working fine if you select "All Datacenters"

**Comment by palourde** [comment]
Hi @khuongdp 

Could you provide us more details about the issue you are facing?

Also, could you check your browser console and your error log files to make sure there's no errors logged?

Let us know which version of Uchiwa you are running and the installation method (from the source or a package?)

**Comment by khuongdp** [comment]
Hi

Let say i have 100 events, 100 clients, 2000 checks (left side in uchiwa). Then we have 2 datacenter (dc1, dc2) and events/clients/checks is split between the two datacenter (equally)

If I select dc1 it still show 100 events, 100 clients, 2000 checks but should only display 50 events, 50 clients, 1000 checks.

**Comment by palourde** [comment]
Hi @khuongdp 

The datacenter filter is only used by the active view and will be reset as soon you change the view, this is why the counts on the left sidebar are not updated.
