### ISSUE TITLE
High CPU usage with 0.9.0

### ISSUE THREAD

**Issue by palourde** [sensu/uchiwa#337]
The CPU usage of Uchiwa definitively increased between 0.8.1 and 0.9.0. It might have something to do with the daemon package and the channel used.

**Comment by palourde** [comment]
Looks like 0.9.0.beta doesn't have this issue so it could related to https://github.com/sensu/uchiwa/pull/335/files

**Comment by roobert** [comment]
+1

**Comment by palourde** [comment]
I've made some profiling and it looks like the mapstructure package is responsible for the high cpu usage, which is now used in the new `findClientEvents` function. 

```
10.37s of 11.21s total (92.51%)
      flat  flat%   sum%        cum   cum%
[...]
     0.25s  2.23% 72.88%      5.27s 47.01%  github.com/mitchellh/mapstructure.(*Decoder).decodeStruct
     0.04s  0.36% 87.96%      5.27s 47.01%  github.com/mitchellh/mapstructure.(*Decoder).decode
     0.04s  0.36% 88.31%      0.69s  6.16%  github.com/mitchellh/mapstructure.(*Decoder).decodeSlice
[...]
```

I'll have to work again on it in order to optimize it.

**Comment by palourde** [comment]
CPU usage when passing from 0.9.0 to 0.9.1 \o/
![screen shot 2015-06-10 at 18 48 56](https://cloud.githubusercontent.com/assets/4105580/8096110/9462920c-0fa1-11e5-83dc-c51ceeb2c492.png)
