### ISSUE TITLE
Check output should show on the check details page

### ISSUE THREAD

**Issue by eheydrick** [sensu/uchiwa#346]
Sometimes the check output is so long that you're unable to see the entire output (see screenshot below) It would be nice if you could click on the check details and see the complete output there. 

![screen shot 2015-06-23 at 2 13 17 pm](https://cloud.githubusercontent.com/assets/328689/8317400/1a63baba-19b2-11e5-8dd5-cca76dfecb85.png)

**Comment by giladegozi** [comment]
+1

**Comment by roobert** [comment]
+1

**Comment by palourde** [comment]
The output of all checks are now displayed:
![screen shot 2015-06-24 at 20 45 25](https://cloud.githubusercontent.com/assets/4105580/8344672/b48a94b4-1ab2-11e5-909d-1b93c0ac20d5.png)

**Comment by eheydrick** [comment]
:trophy:
