### ISSUE TITLE
Mask passwords in sensu commands

### ISSUE THREAD

**Issue by HawtDogFlvrWtr** [sensu/uchiwa#348]
It would be nice if we could mask passwords in the web client. I've tried using substitution strings but they just appear in the client info window. Would be nice to set set custom client attributes that are masked in uchiwa so that the interface doesn't contain sensitive information. For example, have a custom attribute called "passwords" or "usernames" with all the information needed for substitution tokens, that appear as ****** in the web interface.

**Comment by johntdyer** [comment]
+1

**Comment by palourde** [comment]
@HawtDogFlvrWtr You should simply use the *redact* attribute in your client definition, as documented here: https://sensuapp.org/docs/0.19/clients.

**Comment by johntdyer** [comment]
@palourde ,

 Sorry but its not exactly clear ( at least to me ) how to use `redact` based on the docs... Any chance you can provide an example ? 

-John

**Comment by palourde** [comment]
@johntdyer In your *client.json* file, you would have something like:

```
"redact": [ "password" ],
"password": "secret"
```

Then, in your check, you would use the *password* attribute for your token substitution.

**Comment by johntdyer** [comment]
Hello,

  So lets say my client looks like this 

````json
{
  "client": {
    "name": "rt02.foo.jp",
    "address": "172.31.16.31",
    "subscriptions": [
      "base",
      "rt02.foo.jp",
      "prism",
      "runtime"
    ],
    "keepalive": {
      "thresholds": {
        "warning": 120,
        "critical": 180
      },
      "handlers": [
        "default",
        "pagerduty"
      ],
      "refresh": 1800
    },
    "prism": {
      "pdd": {
        "username": "foo",
        "password": "bar"
      },
      "license": {
        "mrcp": 50,
        "app": 50
      }
    }
  }
}
```

and I wanted to redact the value in `prism.pdd.username` how would that be done in `redact` ? 

-John

**Comment by palourde** [comment]
@johntdyer 

Unfortunately I don't know if you can redact `prism.pdd.username` or only the parent attribute `prism` but you should be able to easily test it. Also, maybe someone with better expertise could answer this question on IRC or Google Groups.
