### ISSUE TITLE
Uchiwa 0.10.0 - Cannot click on check to get check details

### ISSUE THREAD

**Issue by MattHodge** [sensu/uchiwa#350]
Hi,

Updated to version 0.10.0 via the .deb package and I am now unable to click on a check to get its information:

1. Click on Check
2. URL Changes but check does not display on the page, it just stays on the client page

![uchiwa](http://i.imgur.com/0idnhDH.png)

The following error shows up in the browser developer console:

![error](http://i.imgur.com/NWweuXA.png)

```
Error: currentCheck.model is null
updateCheck@http://10.13.37.162:3000/bower_components/uchiwa-web/js/controllers.js:148:11
@http://10.13.37.162:3000/bower_components/uchiwa-web/js/controllers.js:188:7
hf/this.$get</m.prototype.$emit@http://10.13.37.162:3000/bower_components/angular/angular.min.js:136:309
$scope.pull/<@http://10.13.37.162:3000/bower_components/uchiwa-web/js/controllers.js:120:11
k/g.success/<@http://10.13.37.162:3000/bower_components/angular/angular.min.js:86:360
f/<@http://10.13.37.162:3000/bower_components/angular/angular.min.js:120:113
hf/this.$get</m.prototype.$eval@http://10.13.37.162:3000/bower_components/angular/angular.min.js:134:394
hf/this.$get</m.prototype.$digest@http://10.13.37.162:3000/bower_components/angular/angular.min.js:131:419
hf/this.$get</m.prototype.$apply@http://10.13.37.162:3000/bower_components/angular/angular.min.js:135:159
l@http://10.13.37.162:3000/bower_components/angular/angular.min.js:87:150
N@http://10.13.37.162:3000/bower_components/angular/angular.min.js:91:187
Rf/</x.onload@http://10.13.37.162:3000/bower_components/angular/angular.min.js:92:220

http://10.13.37.162:3000/bower_components/angular/angular.min.js
Line 108
```

Have tried this in multiple browsers and after clearing cache, restarting uchiwa and sensu-api.

**Comment by palourde** [comment]
@MattHodge Can you confirm that the checks in question are all standalone checks?

**Comment by MattHodge** [comment]
@palourde Yes they are - all sent via the *Client socket input* feature

**Comment by palourde** [comment]
@MattHodge Alright thanks, I've identified the issue, I'll have a fix released asap.

**Comment by MattHodge** [comment]
Thanks @palourde  :)

**Comment by palourde** [comment]
Hi @MattHodge 

The PR https://github.com/sensu/uchiwa-web/pull/55 fix this issue. It's a simple patch with 3 lines so you could easily add it to your installation.

I'll release 0.10.1 later today.

**Comment by MattHodge** [comment]
0.10.1 works nicely - thanks.
