### ISSUE TITLE
Error while connecting to github 

### ISSUE THREAD

**Issue by adithyakhamithkar** [sensu/uchiwa#351]
Hi,

I am trying to authenticate Uchiwa with github and I am getting the following error

"Date":"2015-07-02T02:10:58.497824233+05:30","Level":"warning","Src":{"Func":"github.com/sensu/uchiwa/uchiwa/daemon.(*Daemon).fetchData","Line":68},"Output":"API call to \"http://192.168.44.153:4567/stashes\" returned: Get http://192.168.44.153:4567/stashes: dial tcp 192.168.44.153:4567: connection refused"}

Can some one please tell me where am I going wrong?

My Config file has
{
    "sensu": [
        {
            "name": "test-env",
            "host": "192.168.44.153",
            "ssl": false,
            "port": 4567,
            "path": "",
            "timeout": 5000
        }
    ],
    "uchiwa": {
        "port": 3000,
        "stats": 10,
        "refresh": 10000
    },

   "github": {
      "clientId": "",
      "clientSecret": "",
      "server": "https://github.com",
      "roles": {
        "guests": [
          ""
        ],
        "operators": [
          ""
        ]
      }
    }
}

**Comment by palourde** [comment]
Hi @adithyakhamithkar 

The error you see isn't related to an authentication problem. Uchiwa is actually unable to connect to your Sensu API (http://192.168.44.153:4567) so you should try to figure out why. Does the Uchiwa box has access to this address? Does your Sensu API is password protected?

For your information, Github authentication is only available with the Enterprise Dashboard. If you are using Uchiwa, please refer yourself to http://docs.uchiwa.io/en/latest/configuration/uchiwa/ instead.

**Comment by adithyakhamithkar** [comment]
Uchiwa is running on the same box and it's not password protected

**Comment by palourde** [comment]
If they are running on the same box, could you try to use `127.0.0.1` instead?

I recommend you to also take a look at the Sensu API logs (`/var/log/sensu/sensu-api.log`).

**Comment by adithyakhamithkar** [comment]
I have stopped getting that error. And i don't see any thing in the api logs. But this again in the uchiwa logs
{"Date":"2015-07-01T10:07:33.965516932+05:30","Level":"warning","Src":{"Func":"github.com/sensu/uchiwa/uchiwa.(*Uchiwa).GetClient","Line":120},"Output":"Could not find client sensu-master-prod"}
{"Date":"2015-07-01T10:11:38.271157807+05:30","Level":"info","Src":{"Func":"github.com/sensu/uchiwa/uchiwa/config.Load","Line":73},"Output":"Loading configuration file /etc/sensu/uchiwa.json"}
{"Date":"2015-07-01T10:11:38.271675009+05:30","Level":"info","Src":{"Func":"github.com/sensu/uchiwa/uchiwa.(*Uchiwa).WebServer","Line":274},"Output":"Uchiwa is now listening on 0.0.0.0:3000"}
{"Date":"2015-07-01T10:11:38.888697183+05:30","Level":"warning","Src":{"Func":"github.com/sensu/uchiwa/uchiwa.(*Uchiwa).GetClient","Line":120},"Output":"Could not find client web-01"}
{"Date":"2015-07-01T10:17:16.69373084+05:30","Level":"info","Src":{"Func":"github.com/sensu/uchiwa/uchiwa/config.Load","Line":73},"Output":"Loading configuration file /etc/sensu/uchiwa.json"}

**Comment by palourde** [comment]
@adithyakhamithkar it looks like you are facing some connectivity issues between the Sensu API and Uchiwa so I would recommend you to troubleshoot this aspect. Let me know if you are able to find anything.
