### ISSUE TITLE
feature request: re-add iFrame support..

### ISSUE THREAD

**Issue by roobert** [sensu/uchiwa#354]
Hi Palourde,

I was just reimplementing embedded graphs (this time with grafana) when I noticed uchiwa-web no-longer supports iframes. Here was my original PR that got merged: https://github.com/sensu/uchiwa/commit/6cde2ec79c133afd3be1e760b3500f882fcaa7ee

Is there any reason it was removed?

I would also be grateful for ideas on allowing an ID or class to be set for each iframe. As mentioned in the PR I thought simply changing the syntax for the field to be something like: "iframe:[id]:[url]" might work. It would be nice if Uchiwa could be configured, or could look for a local css file, too. What do you think?

Cheers,

**Comment by palourde** [comment]
@roobert My bad! I'll look into this ASAP.

**Comment by roobert** [comment]
@palourde: any comment on adding an id or class for custom styling..?

**Comment by palourde** [comment]
@roobert You now have a span with *iframe* class that contains the actual iframe.
