### ISSUE TITLE
feature: stash reason meta data

### ISSUE THREAD

**Issue by roobert** [sensu/uchiwa#356]
Hi Palourde,

It would be really useful if we had the option to store the logged in user as part of the stash reason, is this something you'd consider? I'm guessing the api has no concept of Uchiwa which is why I thought it may be simpler to have some option to include it as part of the "reason" string.

Cheers,

**Comment by jsoriano** [comment]
Hi @palourde,

Is this feature only available in Sensu Enterprise? I think it got lost in 6fdee7697c698ac3859c709e5117193ae3d197f6

**Comment by palourde** [comment]
@jsoriano You are right, I'll look into that!
