### ISSUE TITLE
Display sensu servers info

### ISSUE THREAD

**Issue by jaimegago** [sensu/uchiwa#357]
In a cluster setup where there are several sensu servers/apis configured with different handlers it'd be great to be able to see that info in the Sensu dashboard.

**Comment by portertech** [comment]
@jaimegago I think @amdprophet was working on this no so long ago :tada: 

@amdprophet Where did you get w/ this?

**Comment by jaimegago** [comment]
@portertech @amdprophet Any news on this? Also I filed  https://github.com/sensu/sensu/issues/1027 let me know if it's redundant.

**Comment by palourde** [comment]
This is now available in Sensu 0.28 and Uchiwa 0.23!
