### ISSUE TITLE
images not in panels

### ISSUE THREAD

**Issue by roobert** [sensu/uchiwa#361]
As suggested in #360, images should be in their own frames, has this already been implemented?

Here is what I see:

![no_panels](https://cloud.githubusercontent.com/assets/226654/8878363/7a686054-3222-11e5-9eec-17c11bb99543.png)

**Comment by palourde** [comment]
Hi @roobert 

Indeed, images should already have their own panels. Could you let me know the version of Uchiwa running and the URL for one of your images?

**Comment by roobert** [comment]
Hi Palourde, I'm running Uchiwa on debian wheezy, package version: 0.10.3-1

Example URL:

`https://grafana.xxx.net/render/dashboard-solo/script/host.js?host=%{hostname}&panelId=1&theme=light&force_image=.jpg`

**Comment by palourde** [comment]
@roobert I'm absolutely unable to reproduce this issue. I tested with an image generated by JS and still, the image properly show up in its own panel.

Could you provide me the HTML code for one of your image?

**Comment by roobert** [comment]
Hi Palourde, I'm not sure if I'm doing something wrong? Here is an example of iframes not being separated out into separate panels, I can get you code for exactly the same situation but with images later (this is all I have to hand right now), if this is not enough?

![uchiwa_no_frame](https://cloud.githubusercontent.com/assets/226654/9611482/c9041b26-50d7-11e5-8596-8f8abf55e889.png)

**Comment by palourde** [comment]
@roobert Oh I see, you are using an iframe to load your image. The support of dedicated panels for iframe is not implemented yet (https://github.com/sensu/uchiwa/issues/360). 

Right now, an image will be loaded to its own panel only when defined like this on the check definition:
```
"metric disk": "https://domain.tld/image.jpg"
```

**Comment by roobert** [comment]
Hi Palourde, I had the same problem with images from grafana and graphite, I will redeploy a client config with images from grafana and show you the code.

Cheers,

**Comment by roobert** [comment]
How's this?

![uchiwa_no_panel](https://cloud.githubusercontent.com/assets/226654/9612270/919cee92-50dc-11e5-89ea-326b44939a6b.png)

**Comment by roobert** [comment]
This was after upgrading to 0.10.4 - It looks like when resizing the screen to small sizes the details panel no longer floats to below the client details panel, was this intentional..?

**Comment by palourde** [comment]
@roobert Now I see the confusion; this behaviour was only applied to check attributes and not client attributes, which is now modified with the last PR.

Regarding the panels behaviour when resizing the window, yes it's intentional for now, until we have a true mobile compatible interface.

**Comment by roobert** [comment]
Ahh great, thanks @palourde! :+1:
