### ISSUE TITLE
Authentication : create a user with access to only a specific datacenter

### ISSUE THREAD

**Issue by jeanfrancis** [sensu/uchiwa#365]
Is it possible to create a user with access to only a specific datacenter ?

**Comment by Seraf** [comment]
Hello, I was wondering the same question. In order to have one uchiwa for multiple customer, this should be an awesome feature !

**Comment by palourde** [comment]
The RBAC (Role Base Access Control) feature is currently only available with Sensu Enterprise (https://sensuapp.org/docs/latest/enterprise-dashboard-configuration#role-based-access-controls-rbac).
