### ISSUE TITLE
Feature Request: Aggregates should list affected clients

### ISSUE THREAD

**Issue by filthyrake** [sensu/uchiwa#366]
Currently, Aggregates only show the number of clients affected by the alert.  However, when you drill into it, it doesnt actually tell you which clients those are.  Yes, you can get that information by going to the Events page and looking through the list (or filtering), but if you're already using aggregates it seems like a no-brainer to put that information there.

**Comment by palourde** [comment]
The Sensu API doesn't provide the information concerning the clients so it would require some additional logic in Uchiwa to provide it.

**Comment by stevenviola** [comment]
It looks like in Sensu 0.24, the ability to get a list of hosts per severity for an aggregate was [added to the API](https://sensuapp.org/docs/0.26/api/aggregates-api.html#aggregatesnameresultsseverity-get). For example: 

```
$ curl -s http://localhost:4567/aggregates/sensu-redis-slave/results/ok | jq .
[
  {
    "summary": [
      {
        "clients": [
          "sensu-redis02",
          "sensu-redis03"
        ],
        "total": 2,
        "output": "RedisSlaveCheck OK: The redis master links status is up!\n"
      }
    ],
    "check": "redis-slave-status"
  }
]
```

By using this API endpoint, uchiwa should be able to drill in and display the clients for each of the severities for a particular aggregate.

**Comment by palourde** [comment]
Quick update to let you know that Uchiwa now support this feature since 0.19.

Thanks!
