### ISSUE TITLE
uchiwa 0.10.3 having issue connecting to Sensu API

### ISSUE THREAD

**Issue by sumit-sngpt** [sensu/uchiwa#371]
After upgrading the uchiwa version to 0.10.3-1, I kept getting following error at its log where it wasn't able to establish connection with Sensu api intermittently. Downgrading the version to 0.10.1 fixed the issue.

"Src":{"Func":"github.com/sensu/uchiwa/uchiwa/daemon.(*Daemon).fetchData","Line":69},"Output":"API call to \"http://0.0.0.0:4567/stashes\" returned: Get http://0.0.0.0:4567/stashes: read tcp 127.0.0.1:4567: use of closed network connection"

**Comment by palourde** [comment]
Hi @sumit-sngpt 

I don't see any changes between 0.10.1 and 0.10.3 that could explain the error messages you received. I would recommend you to try upgrading again and restart both Uchiwa and the Sensu API process.

**Comment by jsoriano** [comment]
Just in case it can be related, after upgrading from 0.10.0 to 0.10.4 we have seen that the network traffic between uchiwa and sensu servers has increased a lot (almost x10), this increase has caused problems in one of our more heavy loaded sensu servers. It has reported some times this error when handling a notification:
```
"timed out while attempting to query the sensu api for a stash\n"
```
We have reverted the upgrade by now.

**Comment by portertech** [comment]
Also seeing this with Sensu Enterprise, which uses Jetty under the hood.

**Comment by palourde** [comment]
Hi @sumit-sngpt and @jsoriano.

Uchiwa 0.11.0 now uses Go 1.5.1, which added some improvements to the http client. If you have the chance, could you try this new version and let me know if you still see the same issues?

Thanks!

**Comment by jsoriano** [comment]
Hi @palourde,

We have just upgraded to 0.11.1 and it works pretty well by now, I'll let you know if any new problem arises. Good job!

Thanks.
