### ISSUE TITLE
Delete an individual check from a client

### ISSUE THREAD

**Issue by jaxxstorm** [sensu/uchiwa#372]
If a host has run a check previously, but the config is removed and the check no longer runs, it will remain in the redis keys forever more as a zombie, with the last execution time continually rising.

Ideally if we could add a button that allows us to delete the individual check from the client, that would be awesome

**Comment by palourde** [comment]
Unfortunately there's no endpoint available on the Sensu API to perform such operation, so as long this restriction exist, there's not much we can do.
