### ISSUE TITLE
Should the events/clients icon on the left side bar show the silenced alerts?

### ISSUE THREAD

**Issue by cintiadr** [sensu/uchiwa#382]
Of course, fell free to close this issue, but I have right now 10 alerts which are silenced (alerts I've addressed somehow). 

My events view is not showing them, but still I have a red number '10' by the events icon on the sidebar, which is somehow not what I expected to see. 

Should it reflect even the silenced alerts?

**Comment by palourde** [comment]
Hi @cintiadr 

This is an expected behaviour. The sidebar events count will display all events without distinction of silence status. I tend to believe that silencing an alert should only be a temporary measure, and therefore we should not completely hide silenced events from the users.
