### ISSUE TITLE
Could not retrieve the client

### ISSUE THREAD

**Issue by sstarcher** [sensu/uchiwa#383]
On a recent change in the last day or 2 anytime I click on the client I get "Could not retrieve the client..."
If i curl the sensu api that uchiwa is connected to I see the client in the /clients list

**Comment by palourde** [comment]
Hi @sstarcher,

I assume that you are running Uchiwa from the source? If so, please make sure to upgrade both [uchiwa](https://github.com/sensu/uchiwa) and [uchiwa-web](https://github.com/sensu/uchiwa-web) code since some major changes (and more to come) have been done on the Uchiwa internal API.

**Comment by sstarcher** [comment]
@palourde I'm actually running it from the docker container.  One of the commits on the 19th/20th I think broke it.

I use an automated docker build that is a downstream of sensu/uchiwa github.  So it rebuilds my docker container from your source every time you commit. https://github.com/sstarcher/docker-uchiwa

**Comment by palourde** [comment]
@sstarcher Oh I see now; the issue here is that you are fetching the latest tagged version of *sensu/uchiwa-web* (because of bower) and not the latest commit, which isn't compatible with the latest commits of *sensu/uchiwa*.

I would recommend you either modify your automated docker build process so it also fetch the latest *sensu/uchiwa-web* commit or only launch a build on tags and not commits so you always have a stable image for your container.

**Comment by sstarcher** [comment]
@palourde so does this leave your docker container that you push out to docker.io as non-functional also?  https://hub.docker.com/r/uchiwa/uchiwa/builds/

**Comment by sstarcher** [comment]
Essentially the docker container that you are pushing to docker.io contains code from the master of this repo and the last tagged version of uchiwa-web.  Which anytime master in this repo depends on changes in an unreleases version of uchiwa-web it will break anyone who is using the container on docker.io along with your instructions for running uchiwa in a docker container.

**Comment by palourde** [comment]
@sstarcher These containers are automatically built after a commit. Unfortunately I'm not aware of any way to restrict builds to git tags on Docker Hub.

I'll try to keep the *uchiwa-web* dependency updated by using the commit id between releases.

**Comment by sstarcher** [comment]
Would it make sense to change the bower.json to reference the git repo and freeze it at a tag prior to releases?  That would allow you to keep things up to date.
```
{
  "name": "uchiwa",
  "dependencies": {
    "uchiwa-web": git@github.com:sensu/uchiwa-web.git"
  }
}
```

**Comment by palourde** [comment]
I prefer to specify the Git commit SHA between releases in order to have easier and reproducible builds. Usually *uchiwa* and *uchiwa-web* versions are both backward compatible excepted when we touch to the backend API, which was the case last weekend.

I'll update the bower dependency tonight.
