### ISSUE TITLE
periodic nav bar issue

### ISSUE THREAD

**Issue by roobert** [sensu/uchiwa#387]
I get this oddness periodically with `0.11.1-1`:

![uchiwa-nav](https://cloud.githubusercontent.com/assets/226654/10102596/424405ba-6397-11e5-9759-c78e5db4692d.png)

```
sensu /root # dpkg -l | grep uchiwa
ii  uchiwa                             0.11.1-1                      amd64        Uchiwa, a Sensu dashboard, created by Simon Plourde.
```

Looking at the console I can see:
```
GET https://sensu.ext.brandwatch.net/get_sensu 404 (Not Found)
```

I'm guessing I need to upgrade Sensu (0.20.2-1) although there are no newer packages available at this time..

**Comment by palourde** [comment]
Hi @roobert 

Make sure to refresh your browser cache either by doing a full page reload or clear all your browser cache. With the 0.11.1 release, the `/get_sensu` API endpoint is no longer used.

We also started to use versioning on the CSS & JS resources so it should prevent this kind of issue for the next releases.

**Comment by sstarcher** [comment]
I get the same issue.  If I open the page in Chrome Incognito mode it works, but as soon as I reload the page it breaks.  Clearing the cache is only a temporary solution until the page is reloaded, which causes it to break again.

**Comment by NeckBeardPrince** [comment]
Same issue here, cache has been cleared as well. It works once then when you refresh that comes up.
