### ISSUE TITLE
No uhciwa 11.1 rpm's in repo.

### ISSUE THREAD

**Issue by jbehrends** [sensu/uchiwa#389]
Unless I'm missing something it doesn't look like any rpms have been published yet to repos.sensuapp.org.  Any ETA on this?

Thanks!

**Comment by palourde** [comment]
Hi @jbehrends 

Unfortunately it seems that the build box used by the Sensu organization to push the packages to the repos crashed so a new one needs to be provisioned, which should be done within the next few days. Otherwise you can still download the packages from Uchiwa website.

Thanks

**Comment by haghabozorgi** [comment]
Not sure why this was closed, it is still an issue as the latest version of uchiwa is still old 

uchiwa.x86_64                                                    1:0.10.3-1                                                    @sensu

Latest shows 0.11.2-1
any idea on when this will make it into the repo?

**Comment by palourde** [comment]
@haghabozorgi This issue was closed because I don't have any control over the Sensu repositories. However, the latest packages are available for download on https://uchiwa.io/#/download.
