### ISSUE TITLE
Current uchiwa Dockerfile doesn't work with current version

### ISSUE THREAD

**Issue by AlexClineBB** [sensu/uchiwa#391]
We're using the Dockerfile to start uchiwa and the latest version of uchiwa returns 404s for all resources like issue #323. The bower install was working, it was just putting the files in the wrong place.

I was able to work around the issue by adding this line before the final CMD instruction.

    
    RUN ln -s /go/src/app/bower_components /go/src/app/public/

**Comment by palourde** [comment]
Hi @AlexClineBB 

I just submitted a patch to cleanup a little bit the Dockerfile and update the golang image. I just tested the image from this [build](https://hub.docker.com/r/uchiwa/uchiwa/builds/bp8akgznecerxhecfe35kqc/) and it seems to be working pefectly; the `/go/src/app/public/bower_components` folder was creating without having to create any symlink. Let me know if you still have any difficulties.

Thanks
