### ISSUE TITLE
Support static RSA keys for JWT generation

### ISSUE THREAD

**Issue by boboli** [sensu/uchiwa#394]
I'm trying to use the simple auth settings to protect access to uchiwa. But whenever I log in, I see a glimpse of the dashboard before the login screen shows up again. If I use the wrong credentials, I get the red error notification, so I'm pretty sure the credentials were correct.

On further investigation, it seems like angular.js made GET requests onto /get_config and /get_sensu which both returned HTTP 401 Unauthorized, causing the app to show the login screen again. Strangely, Chrome shows that both requests are made twice, one succeeding with HTTP 200, one failing with HTTP 401.

The response itself is:
```
HTTP/1.1 401 Unauthorized
Content-Type: text/plain; charset=utf-8
Date: Mon, 05 Oct 2015 20:34:04 GMT
Server: nginx
Content-Length: 31
Connection: keep-alive
crypto/rsa: verification error
```

My uchiwa config looks like this:

```
{
    "uchiwa": {
        "host": "0.0.0.0",
        "port": 3000,
        "user": "admin",
        "pass": "******",
        "interval": 5
    }
}
```
If I disable the auth system by putting `""` for both `user` and `pass` settings, everything works fine.

FWIW, I'm putting uchiwa behind nginx, but I also tried directly hitting uchiwa on port 3000, and the issue persists.

I'm using uchiwa version 0.10.3 installed on Ubuntu 14.04 via the official sensu apt repository.

**Comment by palourde** [comment]
Hi @boboli 

Could you try to upgrade to the latest version, which is 0.11.2 (it's only available through HTTP download for now on https://uchiwa.io/#/download).

Also, please provide us the logs from your browser console and the Uchiwa service.

Thanks

**Comment by boboli** [comment]
Thanks @palourde for looking into this.

I just tried it with 0.11.2, and I get the same issue.

One thing to note is that I'm using 2 machines behind a load balancer (Amazon ELB) to serve the uchiwa dashboard. When I restricted it to just 1 machine, everything works fine. I'm guessing that the uchiwa service uses some local memory caching for the login session/cookies, and because that's not shared between the 2 boxes, once a request lands on the wrong server, it issues the 401. Is that the cause?

In any case, here are log dumps.

The uchiwa logs don't show anything:
```
bobo@ip-10-1-30-92:~$ sudo tail -f /var/log/uchiwa.log
{"Date":"2015-10-07T21:31:56.242466376-04:00","Level":"info","Src":{"Func":"github.com/sensu/uchiwa/uchiwa/config.Load","Line":82},"Output":"Loading configuration file /etc/sensu/uchiwa.json"}
{"Date":"2015-10-07T21:31:56.242964927-04:00","Level":"info","Src":{"Func":"github.com/sensu/uchiwa/uchiwa.(*Uchiwa).WebServer","Line":427},"Output":"Uchiwa is now listening on 0.0.0.0:3000"}
{"Date":"2015-10-08T19:11:05.657251793-04:00","Level":"info","Src":{"Func":"github.com/sensu/uchiwa/uchiwa/config.Load","Line":91},"Output":"Loading configuration file /etc/sensu/uchiwa.json"}
{"Date":"2015-10-08T19:11:05.657654533-04:00","Level":"info","Src":{"Func":"github.com/sensu/uchiwa/uchiwa.(*Uchiwa).WebServer","Line":417},"Output":"Uchiwa is now listening on 0.0.0.0:3000"}
```
```
bobo@ip-10-1-30-153:~$ sudo tail -f /var/log/uchiwa.log
{"Date":"2015-10-08T19:11:00.17438-04:00","Level":"info","Src":{"Func":"github.com/sensu/uchiwa/uchiwa/config.Load","Line":91},"Output":"Loading configuration file /etc/sensu/uchiwa.json"}
{"Date":"2015-10-08T19:11:00.174755185-04:00","Level":"info","Src":{"Func":"github.com/sensu/uchiwa/uchiwa.(*Uchiwa).WebServer","Line":417},"Output":"Uchiwa is now listening on 0.0.0.0:3000"}
{"Date":"2015-10-08T19:14:57.409588556-04:00","Level":"info","Src":{"Func":"github.com/sensu/uchiwa/uchiwa/config.Load","Line":91},"Output":"Loading configuration file /etc/sensu/uchiwa.json"}
{"Date":"2015-10-08T19:14:57.452200178-04:00","Level":"info","Src":{"Func":"github.com/sensu/uchiwa/uchiwa.(*Uchiwa).WebServer","Line":417},"Output":"Uchiwa is now listening on 0.0.0.0:3000"}
{"Date":"2015-10-08T19:14:57.477703189-04:00","Level":"info","Src":{"Func":"github.com/sensu/uchiwa/uchiwa/config.Load","Line":91},"Output":"Loading configuration file /etc/sensu/uchiwa.json"}
{"Date":"2015-10-08T19:14:57.568478975-04:00","Level":"info","Src":{"Func":"github.com/sensu/uchiwa/uchiwa.(*Uchiwa).WebServer","Line":417},"Output":"Uchiwa is now listening on 0.0.0.0:3000"}
```

And neither does the Chrome console:
![screen shot 2015-10-08 at 4 22 50 pm](https://cloud.githubusercontent.com/assets/4108038/10382448/f6b94cda-6dd8-11e5-8c46-fdc16454a6de.png)

**Comment by palourde** [comment]
Thanks @boboli for the details.

Currently, every time you start Uchiwa, a random RSA key is generated to sign the JSON Web Tokens (JWT) used to authenticate users. It means that a JWT generated by your first instance will not be valid with your second one and therefore this last instance will mark the request as unauthorized.

What we need to implement is a way to let users manually create their own RSA keys so it can be shared between multiple instances of Uchiwa.
