### ISSUE TITLE
Display all Check Results on Success

### ISSUE THREAD

**Issue by sstarcher** [sensu/uchiwa#395]
When a check succeeds only a few values are being displayed.  It would be great to show the entire check model similar to what is done when a check fails.

**Comment by palourde** [comment]
Hi @sstarcher 

Make sure to upgrade your Sensu server to at least 0.18.x since this functionality was added to the Sensu API.

**Comment by sstarcher** [comment]
Sensu 0.20.3
Uchiwa 0.11.2
Data on the check page
```
standalone true
history 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
last_execution 2015-10-08 17:58:12
output Succeeded
```

API request - results/Jobs-syseng/CloudwatchAlarmEmailer
```
{"client":"Jobs-syseng","check":{"name":"CloudwatchAlarmEmailer","source":"Jobs-syseng","output":"Succeeded","status":0,"slack_channel":"#listhub-syseng-status","logs":"http://kibana.cluster.private/#/discover?_g=(time:(from:'2015-10-08T21:58:01Z',mode:absolute,to:'2015-10-08T21:58:12Z'))&_a=(columns:!(message),index:%5Blogging-%5DYYYY.MM.DD,interval:auto,query:(query_string:(analyze_wildcard:!t,query:'docker.hostname:CloudwatchAlarmEmailer')),sort:!('@timestamp',asc))&empty_value","executed":1444341492,"issued":1444341492}}
```

When the result is an error it shows the rest of the data instead of just the 4 values that are above.

**Comment by palourde** [comment]
@sstarcher You are right, standalone checks do not take advantage from the `last_result` attribute that was added with Sensu 0.18.
