### ISSUE TITLE
Fix Docker Hub auto-build

### ISSUE THREAD

**Issue by palourde** [sensu/uchiwa#401]
Since the Dockerfile for the Docker Hub has been moved to the `fixtures` directory, the build process is broken.

**Comment by palourde** [comment]
The Dockerfile has been moved back: https://github.com/sensu/uchiwa/commit/a1e28187615b6de43ac11f1d17719d9c47516a06

**Comment by altvnk** [comment]
Auto builds on DockerHub is still broken, last image build was month ago.

**Comment by palourde** [comment]
@altvnk My bad, there was a misconfiguration on the Docker Hub, it's fixed!

**Comment by altvnk** [comment]
@palourde Thank you, now it works.
