### ISSUE TITLE
Debians

### ISSUE THREAD

**Issue by sstarcher** [sensu/uchiwa#402]
How often/long after a tag are the os packages built?  I notice the latest in the debian repo is 0.11.2

**Comment by palourde** [comment]
Hi @sstarcher,

Sorry for the delay. You can always grab the latest packages on https://uchiwa.io/#/download. They are also pushed to the repos within few days. Also make sure to use the newer Sensu repositories: https://sensuapp.org/docs/latest/install-repositories.

Thanks
