### ISSUE TITLE
Uchiwa not showing "Output" when check status is green (status 0)

### ISSUE THREAD

**Issue by pwn777** [sensu/uchiwa#404]
On the page /client/home/(servername) it shows a list of all the checks for that client. When an event is triggered it shows the output on this page's check. But when the status of the check is green, it does not show the output (probably by design). I would love to see the regular Output even when the checks are green. For example, if you have a check for memory use, it will say: "Memory use OK, 50% used". How can I pipe the output from the actual check page into this overall client "checks" page. 

This is the page I am referring to:
http://thepracticalsysadmin.com/wp-content/uploads/2014/08/uchiwa41.jpg

**Comment by jbehrends** [comment]
Uchiwa will do this if your using a newer version of Sensu.  From your screenshot it looks like your using v0.13.1  and I believe the ability to read the output for a check in an OK state was introduced in Sensu v0.18.    So upgrade your Sensu install and you'll get what your looking for.

**Comment by pwn777** [comment]
Thanks for the fast reply, this is not my screenshot - I just pulled it from a website. My sensu version is: v0.20.6 and my uchiwa version is v0.12.0. So should I downgrade my sensu to restore this functionality? Thanks!

**Comment by jbehrends** [comment]
Have you verified that both Sensu Server and Sensu Client are v0.20.6?
It sounds like you have versions of both Sensu and Uchiwa that should show you check results.  I would start by reviewing the output of your Sensu server's "results" API for a specific client and see what's returned. Do you see the results output when you hit /results/<CLIENTNAME> ?  
https://sensuapp.org/docs/0.20/api-results
Ultimately if the data isn't being returned by the API, then you won't see it in Uchiwa.

**Comment by pwn777** [comment]
Yeah I see all the outputs when I view /results/ . Also all of my sensu-client versions are on 0.20.6 as well. I've tried flushing redis also. Here is a screen shot of my actual setup: 
http://i.imgur.com/37OdFTk.png 
http://i.imgur.com/atnKPMl.png

When I drill into the check it shows me all information. 

Thanks again for the help.

**Comment by pwn777** [comment]
I think I may have narrowed it down to my CentOS version as strange as it sounds. I did a clean install on CentOS 7.1 and it has the same issue. I did an upgrade of uchiwa from 11.2 to 12.0 on CentOS 6.7 and there is no issue. Is there anyone else running sensu+uchiwa on centos 7 that is having issues?

**Comment by pwn777** [comment]
I found this in the uchiwa-web/partials/view/client.html
http://i.imgur.com/VFkvyPl.png

I believe this { check.output } is not returning any data. Maybe its a permissions issue? I don't know. I definitely need some help after this point - I don't know where to look next.

Thanks

**Comment by pwn777** [comment]
I couldn't find anything on this, any help is appreciated. Maybe there is a dependency i'm missing?

**Comment by palourde** [comment]
@pwn777 You are totally right, I completely missed it, sorry about that!
