### ISSUE TITLE
uchiwa and uchiwa-web short descriptions are the same

### ISSUE THREAD

**Issue by mi-wood** [sensu/uchiwa#407]
<img width="652" alt="screen shot 2015-10-31 at 8 54 25 pm" src="https://cloud.githubusercontent.com/assets/3472115/10867175/9b9f011e-8011-11e5-9c05-4d910ae7e4e4.png">

It wasn't immediately apparent that these two repos were different. Maybe just adding something like "backend for..." and "web ui for..." to each description would help clarify.

Thank!

**Comment by palourde** [comment]
Thanks for the suggestion, I modifier the description for uchiwa-web.
