### ISSUE TITLE
Old status data sticks around until restart

### ISSUE THREAD

**Issue by e1ven** [sensu/uchiwa#408]
Using Uchiwa-0.12.1 on Sensu 0.20.3.

A few times lately, Uchiwa as been displaying stale data.
For example, it was just recently reporting that it hadn't received a keepalive for a server.
I had brought the server back online, but it still kept the event.
I tried resolving the event - It stayed.
I tried deleting the client.. When the client was re-created, the alert was still there.

I then restarted uchiwa, and the alert disappeared for good.
For now, I'm scheduling a uchiwa restart via cron, but I figured I'd pass along my experience.

**Comment by palourde** [comment]
Hi @e1ven 

Unfortunately I'm unable to reproduce this issue. If you are still facing this problem, could you try to verify the Sensu API in order to see if the event is also present there? Also, make sure to check your browser console and the Uchiwa logs.

Thanks

**Comment by ROunofF** [comment]
Could this be related to https://github.com/sensu/uchiwa-web/pull/85 ? We had similar symptom but the issue was that uchiwa wasn't unable to connect to the backend (interface lost wifi but nothing was apparent from the uchiwa interface)

**Comment by e1ven** [comment]
@ROunofF's theory makes sense to me as to what happened.
I haven't seen this recur, and didn't save the logs from Nov when it happened

Since so much of the webpage runs client-side, it will appear to be working well.
I can click on new pages, and view events, without ever realizing that it can't talk to the uchiwa server.

My guess is that I had VPN issues or similar at the time, which prevented connections to the uchiwa server. Since so much was automatically cached client-side, it wasn't apparent where the problem was.

We should probably give some sort of obvious alert when we can't contact the uchiwa server, but I'd guess that was the original cause. Thanks.

**Comment by palourde** [comment]
Starting with 0.13.0, a proper error message is displayed when the client-side JS can't contact the Uchiwa backend!
