### ISSUE TITLE
Re-Enabling Dashboard 

### ISSUE THREAD

**Issue by RiRa12621** [sensu/uchiwa#414]
On one of the earlier version of uchiwa, there used to be dashboard look like this
<img width="348" alt="uchiwa1" src="https://cloud.githubusercontent.com/assets/14996407/11301436/5daa3442-8f97-11e5-82d1-e78152aa6f8a.png">

is there any chance that this will be re-enabled since this would be a super awesome feature if you want to, like me, present the dashboard on overhead monitors etc. because it gives a great visibility of the overall situation.

**Comment by palourde** [comment]
Hi @RiRa12621 

I have no plan for bringing back a similar feature in a near future. However, if someone is interested to contribute, it will be my pleasure to provide assistance.

There's already a similar [issue](https://github.com/sensu/uchiwa/issues/75) opened so I'll close this one.

Thanks

**Comment by RiRa12621** [comment]
ok, thanks for the answer and I'll see if i might have time to contribute. 
but also like this sensu-grid project
