### ISSUE TITLE
uchiwa.json being overwritten when building Dockerfile

### ISSUE THREAD

**Issue by basickarl** [sensu/uchiwa#420]
In docker it's good practice to put all RUN commands in one long list. This means installing uchiwa and starting it without being able to run COPY in-between installing and starting.

```
COPY	./files/uchiwa.json /etc/sensu/uchiwa.json

RUN		// other run commands...
		sudo apt-get install -y sensu uchiwa && \
		sudo update-rc.d uchiwa defaults && \
		sudo service uchiwa start && \
 		// more run commands...
```
As you can see, I first copy the file to the right place. However the installation overwrites it with the example file. I must manually go into the container and replace the file.

Simple solution would be when installing check if there is a file already in the location and not overwrite it if so.

**Comment by multani** [comment]
What is the gain for Docker by putting the ``update-rc.d`` and ``service start`` commands on the same line as the installation commands?

I'm pretty sure you can move your ``COPY`` command between 2 ``RUN``, the first one doing the installation part and the second one doing the service start thing without much lost.

**Comment by palourde** [comment]
After reviewing this issue, I would argue that you should actually start Uchiwa using the `CMD` instruction and specify a custom location for your configuration file, e.g.:

```
[...]
CMD ["/opt/uchiwa/bin/uchiwa", "-c", "/uchiwa.json", "-p", "/opt/uchiwa/src/public"]
```
