### ISSUE TITLE
0.13.0 missing from apt repository

### ISSUE THREAD

**Issue by nhinds** [sensu/uchiwa#422]
The [apt repository](http://repositories.sensuapp.org/apt/pool/sensu/main/u/uchiwa/) seems to have uchiwa 0.11.2 - 0.12.1, but not 0.13.0. The [yum repository](http://repositories.sensuapp.org/yum/x86_64/) seems to have the same versions.

The [release announcement for 0.13.0](http://blog.uchiwa.io/uchiwa-0-13-0/) said it would be in the repositories "soon", but that was a month ago. Can we get the uchiwa package for 0.13.0 released to apt and yum please? Is there a technical reason or process stopping this from happening immediately after tagging?

**Comment by obazoud** [comment]
+1

**Comment by icebourg** [comment]
+1 Particularly troubling since 0.12.1 has a broken "hide silenced clients" option.

**Comment by martinisoft** [comment]
Same for me as well. Have temporarily reverted back to the http url until this is resolved.

**Comment by portertech** [comment]
Hi all, sorry for the inconvenience. There are still a few kinks to be worked out of the build pipeline, in early Q1. I have manually added 0.13.0-1 to the DEB & RPM repositories. You can now install Uchiwa 0.13.0 from the Sensu Core repositories :+1:
