### ISSUE TITLE
feature request: add support for deleting aggregate checks

### ISSUE THREAD

**Issue by br0ch0n** [sensu/uchiwa#427]
Similar to #419 it would nice to be able to call DELETE /aggregates/:check from uchiwa (unless you can now and I'm just not seeing the button).  Unless I'm mistaken, it looks like even if you delete all stale checks, the stale aggregates produced by those checks will stay there in Redis until deleted also.

**Comment by palourde** [comment]
This has been introduced via https://github.com/sensu/uchiwa-web/pull/118 and will be included in 0.20 release!
