### ISSUE TITLE
bug: Uchiwa debian package doesn't restart on upgrade

### ISSUE THREAD

**Issue by br0ch0n** [sensu/uchiwa#428]
While I don't see the packaging code in the repo, I'm not sure where else to put this...

I'm referring to the packages from http://repositories.sensuapp.org/apt/

Looking in the prerm script for the uchiwa debian package:
```
case "$1" in
    remove|purge)
        stop_uchiwa_service
        ;;

    upgrade|deconfigure)
        ;;

    *)
```
Thus uchiwa doesn't restart when you upgrade it.  I actually noticed that sensu's debian has the same code but I just never noticed before because sensu-puppet is sending a notify to the service resource.  I've been running an older puppet-uchiwa pre- https://github.com/Yelp/puppet-uchiwa/commit/78716f5ec5038dbda7c74a59448575bdd0e7a371 so I've been having to go in and manually restart the service myself every time I upgrade.

Please let me know if this bug belongs elsewhere.  Thanks!

**Comment by palourde** [comment]
Hi @br0ch0n 

I moved this issue to the [uchiwa-build](https://github.com/sensu/uchiwa/issues/428) repo, where all the packages scripts are located.

Thanks for reporting this issue!
