### ISSUE TITLE
Version 14 package release name

### ISSUE THREAD

**Issue by heffergm** [sensu/uchiwa#430]
Just wondering if this is on purpose or not... note the v14 package name. It seems to break the chef run if you're installing via the `http` method.

```
root@uchiwa1:/var/chef/runs# apt-cache madison uchiwa
    uchiwa | 1:0.14.0-1 | http://repositories.sensuapp.org/apt/ sensu/main amd64 Packages
    uchiwa |   0.13.0-1 | http://repositories.sensuapp.org/apt/ sensu/main amd64 Packages
    uchiwa |   0.12.1-1 | http://repositories.sensuapp.org/apt/ sensu/main amd64 Packages
```

**Comment by palourde** [comment]
Yes, we are aware of this issue: https://github.com/sensu/uchiwa-build/issues/26

Sorry for the inconvenient!
