### ISSUE TITLE
Actually print the error for "Connection failed to the datacenter"

### ISSUE THREAD

**Issue by nhooey** [sensu/uchiwa#436]
The [code that handles connection errors](https://github.com/sensu/uchiwa/blob/ad9d5fabf909a905dc0e6ece03f5164df69d39ad/uchiwa/daemon/daemon.go#L80) doesn't actually print the error.

It would help if it printed something.

**Comment by nhooey** [comment]
Also printing the host and port of the server it's trying to connect to would be helpful.

**Comment by palourde** [comment]
@nhooey Starting from 0.14.1, these information are now sent to the logs, e.g.: https://github.com/sensu/uchiwa/blob/ad9d5fabf909a905dc0e6ece03f5164df69d39ad/uchiwa/sensu/loadbalancing.go#L55

**Comment by nhooey** [comment]
Great! Thanks @palourde!
