### ISSUE TITLE
Use batch requests for actions on multiple entities

### ISSUE THREAD

**Issue by nhooey** [sensu/uchiwa#440]
When I select a lot of clients and delete them, Uchiwa dispatches one XHR request for each delete operation, which is very slow.

Using a batch request to post a JSON "delete" command to a batch URL would speed this up.

If Sensu doesn't have batch requests, let's get an issue opened there as well.

**Comment by palourde** [comment]
Unfortunately I don't think the Sensu API offers such capability, according to this documentation: https://sensuapp.org/docs/latest/api-events

**Comment by nhooey** [comment]
Here is the [issue in Sensu](https://github.com/sensu/sensu/issues/1161) to implement a batch API.

**Comment by palourde** [comment]
:+1:

**Comment by palourde** [comment]
I'm going to close this issue since it will not be something available before Sensu 2.0!

**Comment by nhooey** [comment]
Why not just tag this issue "v2.0"?

We're going to lose track of it if you close it.
