### ISSUE TITLE
[ubuntu] wrong package version was pushed in APT repo

### ISSUE THREAD

**Issue by scalp42** [sensu/uchiwa#446]
```
root@sensu-i-7af732a0 # apt-cache madison uchiwa
    uchiwa | 1:0.14.0-1 | http://repositories.sensuapp.org/apt/ sensu/main amd64 Packages
    uchiwa |   0.14.2-1 | http://repositories.sensuapp.org/apt/ sensu/main amd64 Packages
    uchiwa |   0.14.1-1 | http://repositories.sensuapp.org/apt/ sensu/main amd64 Packages
    uchiwa |   0.13.0-1 | http://repositories.sensuapp.org/apt/ sensu/main amd64 Packages
    uchiwa |   0.12.1-1 | http://repositories.sensuapp.org/apt/ sensu/main amd64 Packages
    uchiwa |   0.12.0-1 | http://repositories.sensuapp.org/apt/ sensu/main amd64 Packages
    uchiwa |   0.11.2-1 | http://repositories.sensuapp.org/apt/ sensu/main amd64 Packages
```

You can see `1:0.14.0-1` is actually superior than `0.14.2-1`.

**Comment by dalesit** [comment]
The tickets #430 and sensu/uchiwa-build#26 were prematurely closed. Although the subsequent build versions have now been corrected, as you can see above the incorrect version needs to be removed from the apt repo, as otherwise it will always be the 'latest' version. Please can you remove the erroneous version from the apt repo.

**Comment by palourde** [comment]
@portertech Could you remove the `0.14.0-1` version from the APT repositories?

Thanks!

**Comment by 7ob1** [comment]
Are there news here? I would like to install the latest uchiwa without pinning.

**Comment by GhostLyrics** [comment]
Please delete the offending package from the repository - if necessary for archival purposes, re-issue it with a correct version number. User using your Puppet module are stuck in previous releases unless they implement workarounds.

**Comment by dalesit** [comment]
It **has** been deleted from the repo, as far as I can see at http://repositories.sensuapp.org/apt/pool/sensu/main/u/uchiwa/

**Comment by portertech** [comment]
Removed 0.14.0 from deb repositories, re-indexed, CDN purged :+1:

**Comment by portertech** [comment]
FYI, Uchiwa 0.15.0-1 is available.

**Comment by scalp42** [comment]
Thanks a lot!
