### ISSUE TITLE
Checks page throws ngRepeat:dupes exception

### ISSUE THREAD

**Issue by jgnagy** [sensu/uchiwa#447]
## Scenario

We're running uchiwa 0.14.2, behind nginx as an SSL reverse-proxy (plus we use it for logging requests). Sensu is at 0.20.3 on the server. Hitting the `/#/checks` page renders no list of checks, though I can a JS exception in the JS console. I also checked that `/checks` does properly return JSON data. Looking through the `/checks.html` content, the only `ngRepeat` I see is based on `check._id`. I'm no certain where this field comes from, as I don't see anything like it in the JSON. Is it just a synonym for `$index`? If so, I question how an array index could have a duplicate in the first place.

## Testing

I have tested in Firefox, Chrome, and Safari. I also pulled down the JSON and tried some basic tests on the actual JSON data to find duplicates in things like "name" or "command", of which I could find none.

All other pages render correctly, including `/#/stashes`, `/#/datacenters`, etc.

## Screenshot

![checks___uchiwa_and_clients](https://cloud.githubusercontent.com/assets/664413/12992334/a839d004-d0c8-11e5-84e8-38e438ebf5c3.png)

## Exact Error

https://docs.angularjs.org/error/ngRepeat/dupes?p0=check%20in%20filtered%20%7C%20orderBy:predicate:reverse%20%7C%20limitTo:filters.limit%20track%20by%20check._id&p1=undefined&p2=%7B%22command%22:%22%2Fopt%2Fsensu%2Fembedded%2Fbin%2Fruby.exe%20%2Fopt%2Fsensu%2Fembedded%2Fbin%2Fcheck-windows-process.rb%20-p%20nxlog%22,%22dc%22:%22sensu%22,%22handlers%22:%5B%22hipchat%22,%22mailer%22%5D,%22interval%22:60,%22name%22:%22check-nxlog-process%22,%22standalone%22:false,%22subscribers%22:%5B%22windows%22%5D%7D

**Comment by palourde** [comment]
Hi @jgnagy,

Could you provide me an example of the content returned when you hit the Uchiwa API on the `/checks` endpoint? I suspect that the Uchiwa process was not restarted during the upgrade; the `_id` attribute is now generated by the Uchiwa backend so if it's missing, you should simply try to restart Uchiwa.

Thanks

**Comment by jgnagy** [comment]
Looks like the upgrade was it. I manually restarted the uchiwa service and the checks work again. Thanks!
