### ISSUE TITLE
Support hashed passwords

### ISSUE THREAD

**Issue by ctheune** [sensu/uchiwa#448]
I'm a bit surprised that passwords in the simple authentication are supported only in plaintext. 

I have no way to store plaintext passwords and this really encourages bad behaviour. Even if the open source edition has a somewhat reduced feature set, I think general `crypt` features should be supported.

When generating config with data from any other database, chances are that people won't store their passwords in plain text. I don't, and I don't see any way to get this set up at all. :(

**Comment by palourde** [comment]
I would gladly accept a patch or assist anyone interested in working on it.

**Comment by ctheune** [comment]
Hi, any feedback on that patch?

**Comment by wbrodie** [comment]
This should be high and now low IMHO

**Comment by ctheune** [comment]
Hey there,@palourde,  I'd be "Dee-diddly-lighted" if we could move this forward, somehow. :)

**Comment by bcbv** [comment]
would really like to see this merged
