### ISSUE TITLE
Feature request: Access sensu logs

### ISSUE THREAD

**Issue by kobbe** [sensu/uchiwa#450]
It would be nice to be able to access the sensu (server) logs with uchiwa in case there is a problem with a check not working properly. For example, if you write a handler and your json is formatted wrong, then that handler is just ignored by sensu and one needs to read in the sensu server log to see that it was in fact a json problem. I would guess it is the same with checks, if they are not properly set up there is only evidence in the server logs about a problem.

(I realise that it might be out of scope for uchiwa)

**Comment by palourde** [comment]
Hi,

Unfortunately this is currently impossible, considering that Uchiwa only interacts with the Sensu API, for simplicity and scaling concerns, which means that this information would need to be accessible from the API.

Thanks
