### ISSUE TITLE
Sidebar doesn't work

### ISSUE THREAD

**Issue by georgespatton** [sensu/uchiwa#451]
On version 0.14.2, the sidebar doesn't work shown here in the screenshot.  Here is my info:

cat /etc/sensu/uchiwa.json
{
  "sensu": [
    {
      "name": "Sensu-localhost",
      "host": "127.0.0.1",
      "port": 4567,
      "timeout": 5
    }
  ],
  "uchiwa": {
    "host": "0.0.0.0",
    "port": 3000,
    "user": "myuser",
    "pass": "mypass",
    "interval": 5
  }
}

rpm -qa uchiwa
uchiwa-0.14.2-1.x86_64

I am accessing the uchiwa dashboard on Mac from Chrome.  This worked on the previous version of uchiwa I had installed (0.10).

![screenshot 2016-02-16 15 26 09](https://cloud.githubusercontent.com/assets/2066191/13094749/b00cd072-d4c1-11e5-9d6e-0afb36500816.png)

**Comment by ttarczynski** [comment]
I had the same issue (in chrome only) after rpm update from uchiwa-0.10.3-1.x86_64 to uchiwa-0.14.2-1.x86_64. 
I've tried rpm reinstall plus service restart and now it works OK.

**Comment by georgespatton** [comment]
I tried that too as part of the debug process.  No love.

**Comment by ttarczynski** [comment]
My debugging also included:
* clear browser cache and cookies

**Comment by palourde** [comment]
Hi @georgespatton,

Could you try to clear your web browser cache and restart the Uchiwa process, as suggested [here](http://docs.uchiwa.io/en/latest/upgrading/)? Then, if you still face the same issue, could you try to lunch your web browser console to check if there's any JS errors?

Thanks

**Comment by georgespatton** [comment]
I will do that next week.  Thanks for the suggestions.

**Comment by s33dunda** [comment]
+1 clearing my cache helped

**Comment by georgespatton** [comment]
I upgraded again, cleared everything on my browser, and this problem is fixed.  Thanks, guys!
