### ISSUE TITLE
Feature request: Favicon

### ISSUE THREAD

**Issue by kobbe** [sensu/uchiwa#454]
I just noticed that there is no favicon for uchiwa which makes locating the tab much more difficult.

**Comment by palourde** [comment]
Hi @kobbe 

Uchiwa does have a favicon, as shown here: 
![screen shot 2016-02-26 at 20 59 10](https://cloud.githubusercontent.com/assets/4105580/13370050/df48c7bc-dccb-11e5-8f59-b48a0ab81a7c.png)

Thanks

**Comment by kobbe** [comment]
Hi, thank for the reply. I have investigated it further since I did not really see a favicon. This is a firefox specific problem which can be solved be appending "?" to the address of the favicon. For some reason I can see the favicon now but not if I open uchiwa in privte surfing mode.

http://stackoverflow.com/questions/8616016/favicon-not-displayed-by-firefox-i-know-its-been-asked-10000-times
