### ISSUE TITLE
32bit packages does contain 64bit binary that doesn't run

### ISSUE THREAD

**Issue by kosli** [sensu/uchiwa#457]
the 32bit debian package of version 0.14.2-1 on https://www.uchiwa.io/#/download (http://dl.bintray.com/palourde/uchiwa/uchiwa_0.14.2-1_i386.deb) has a 64bit 
/opt/uchiwa/bin/uchiwa

0.10.1-1: 
/opt/uchiwa/bin/uchiwa: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, not stripped

0.14.2-1:
/opt/uchiwa/bin/uchiwa: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), not stripped

so the package of the new version does NOT run on the 32 bit system :-(

**Comment by kosli** [comment]
is it only me with that problem ?

**Comment by AaronShea** [comment]
Yeah, this is the same problem.
You guys seem to have packaged a 64 bit ELF in the 32 bit deb

**Comment by kosli** [comment]
not only the 32 bit debian but also the 32 bit RPM packages contain the 64 bit binaries... are there any pre-compiled 32 bit binaries available somewhere?

**Comment by ROunofF** [comment]
I just checked and version 0.13 is fine.

**Comment by kosli** [comment]
@ROunofF this is right, just tested it. but still, the latest version 32bit packages (e.g. 0.14.3) contain 64 bit binaries, so I can't upgrade to the latest version.

**Comment by ROunofF** [comment]
Not sure people get a notification when I cross-linked this issue, but I'm pretty sure I found the source of the error. A missing flag on the go compilation command. See https://github.com/sensu/uchiwa-build/pull/31

**Comment by palourde** [comment]
The 32 bits are now fixed starting from 0.14.5. You can grab it right now at https://uchiwa.io/#/download or it will be uploaded to the repositories today.

**Comment by kosli** [comment]
updated the package via the repositories and works like a charm. thank you @palourde
