### ISSUE TITLE
Allow wildcard hostnames for stashed/silenced alerts

### ISSUE THREAD

**Issue by cryptk** [sensu/uchiwa#458]
Sometimes I have a need to silence an entire alert on all hosts (frequently, these are alerts that are generated by JIT clients).

I have tried using the stashes API in sensu to add a stash for the following two paths:

silence/*/check-name
silence//check-name

These appear in the stashes list in Uchiwa as a stash for a host named "*" and a host with no name respectively, but it appears that neither of these options actually act as a wildcard.

Proposed solution:

Use a host name of \* to represent a wildcard for a stash to have it apply to every host.
Add another action to the Checks page in Uchiwa, as well as a "silence" speaker button beside the check name to allow you to create a silence stash for an entire Check (rather than a check on a specific host).  Adding a silence stash for a check from the Checks page would generate one of these wildcard silences.

**Comment by calebhailey** [comment]
This behavior would need to be supported by the Sensu API, which is currently under consideration here: https://github.com/sensu/sensu/issues/1219 

The Sensu team is making plans to improve how checks & handlers (e.g. notifications) are subdued, which would provide support for the scenarios you've described here. Please be sure to participate in the discussion on https://github.com/sensu/sensu/issues/1219 as we progress to a solution (currently targeting the version 0.25 release).

**Comment by fessyfoo** [comment]
it's worth noting that sensu-handler currently supports `/silence/all/check-name`  to silence  by check-name.  as of  v0.3.0 and above https://github.com/sensu-plugins/sensu-plugin/commit/266277237b524410070dc9ae012dc815d9969e4c

**Comment by palourde** [comment]
This has been introduced by the new built-in silenced in Sensu and available in Uchiwa since 0.18 release!
