### ISSUE TITLE
Create slim, lightweight uchiwa "binary" docker image using alpine linux

### ISSUE THREAD

**Issue by oryband** [sensu/uchiwa#462]
After building from source according to the docs, and also trying the supplied image, I've noticed a few interesting things:
```bash
uchiwa $ ls -hl
total 7.7M
drwxr-xr-x  3 ory  ory  4.0K Mar 24 11:43 fixtures
drwxr-xr-x  3 ory  ory  4.0K Mar 24 11:43 Godeps
drwxr-xr-x  4 ory  ory  4.0K Mar 24 11:45 node_modules
drwxr-xr-x  3 ory  ory  4.0K Mar 24 11:45 public
drwxr-xr-x 11 ory  ory  4.0K Mar 24 11:43 uchiwa
drwxr-xr-x  2 root root 4.0K Mar 24 11:49 uchiwa-config
-rw-r--r--  1 ory  ory    75 Mar 24 11:43 bower.json
-rw-r--r--  1 ory  ory   20K Mar 24 11:43 CHANGELOG.md
lrwxrwxrwx  1 ory  ory    19 Mar 24 11:46 config.json -> config.json.example
-rw-r--r--  1 ory  ory   396 Mar 24 11:43 config.json.example
-rw-r--r--  1 ory  ory   313 Mar 24 11:43 Dockerfile
-rw-r--r--  1 ory  ory  1.2K Mar 24 11:43 Gruntfile.js
-rw-r--r--  1 ory  ory  1.1K Mar 24 11:43 LICENSE
-rwxr-xr-x  1 ory  ory  7.6M Mar 24 11:52 main
-rw-r--r--  1 ory  ory   340 Mar 24 11:43 package.json
-rw-r--r--  1 ory  ory  1.6K Mar 24 11:43 README.md
-rw-r--r--  1 ory  ory  1.4K Mar 24 11:43 uchiwa.go

uchiwa $ du --exclude=uchiwa --exclude=Godeps --exclude=.git -sh .
47M     .

uchiwa $ docker images | grep uchiwa
uchiwa/uchiwa                     latest              356feffcc3cf        2 weeks ago         817.1 MB
```
Excluding go source files and its dependencies, the whole directory is less than 50MB. The image itself, however, is a staggering ~800MB. That's 1600% more than required!

So, how can we reduce the image size?
 1. We could build the binary in a "builder image", and then build an "binary" image with only the go binary and the frontend stuff (npm, `public/` dir, etc.). This involves two Dockerfiles, and letting travis use build the "build" image, run it with the build output dir mounted, and then build "binary" image while copying the binary inside. The "binary" image will then be pushed to Dockerhub. I can't think of a way to do all of this via Dockerhub in a nice way.
 1. Docker has started creating trusted builds using Alpine Linux, for example: [Ruby](https://hub.docker.com/_/ruby/). The [base image](https://hub.docker.com/_/alpine/) is only ~5MB. We should base the "binary" image on this one, instal node + npm, and that should be it (there isn't an official `node-alpine` image currently).

**Comment by oryband** [comment]
Might be worth releasing "binary" releases, and not just "source" ones here on github. With this, creating a "binary" image will be easy: just download the binary release and run.

**Comment by Gillingham** [comment]
Some comments on uchiwas current Dockerfile, each RUN command creates a new layer, you want to minimize them. You can do stuff like change
```
RUN apt-get install -yq nodejs npm git wget
RUN ln -s /usr/bin/nodejs /usr/bin/node
RUN npm install --production --unsafe-perm
```
into
```
RUN apt-get install -yq nodejs npm git wget && \
    ln -s /usr/bin/nodejs /usr/bin/node && \
    npm install --production --unsafe-perm
```

Switching to alpine over debian would also definately help, docker is trying to push official images to use alpine and I've had success in converting most of my Docker images over as well. There are official golang alpine variants now even, https://hub.docker.com/_/golang/

**Comment by palourde** [comment]
The docker image is now built from the golang:*-alpine base image (see the attached PR).
