### ISSUE TITLE
Uchiwa 0.14.3

### ISSUE THREAD

**Issue by nilroy** [sensu/uchiwa#463]
When are we going to have the uchiwa 0.14.3 apt package?

**Comment by obazoud** [comment]
any news ?

**Comment by dalesit** [comment]
Hopefully this will also fix #446

**Comment by calebhailey** [comment]
@nilroy thank you for submitting this issue. Sorry for the belated response. The 14.3 packages have been published for some time now, so we're going to close this issue. 

See here for the latest packages: https://core.sensuapp.com/apt/pool/sensu/main/u/uchiwa/
