### ISSUE TITLE
Add `limit=0` option to display everything

### ISSUE THREAD

**Issue by nhooey** [sensu/uchiwa#466]
Currently the `limit=0` parameter actually shows no items in the list when looking at alerts or clients.

It would be helpful to have the `Show All` things option set `limit=0` instead of setting the limit to whatever the current max number of things is.

It would be even better if the limit was saved in a cookie or browser storage.

**Comment by calebhailey** [comment]
@nhooey thank you for this submission. We're categorizing this issue as part of an ongoing issues triage and will provide another update if/when this is scheduled for implementation. At this time we're targeting the 0.15 release.
