### ISSUE TITLE
All check filters except for "keepalive" do nothing

### ISSUE THREAD

**Issue by nhooey** [sensu/uchiwa#468]
When I click on the "check" filter, unless it's `keepalive`, it does nothing.

It doesn't look like an AJAX request is being made, so I'm guessing it's just JavaScript filtering of the last list of events to be returned.

This happens with Uchiwa as late as version `0.14.2-1` from the Sensu Apt repository.

I personally have hundreds of clients, @jaxxstorm confirms this happens with many clients.

**Comment by jaxxstorm** [comment]
Also having this issue. It seems to be a problem once you start getting to a large number of clients, probably related #438

**Comment by rmc3** [comment]
I think it's unlikely that this is related #438, since that is a lockup of the data fetcher goroutine in the Uchiwa server daemon due to the Sensu API returning fewer client entries than the pagination field says should be returned. From a quick review of the source, it looks like @nhooey is right and the functionality of that filter is implemented using Angular.js ```filter``` on the frontend.

**Comment by rmc3** [comment]
Also, I can't reproduce this issue at over 1,000 clients. @jaxxstorm @nhooey, any other conditions that help to reproduce the issue?

**Comment by nhooey** [comment]
@rmc3 One of my checks is called `ansible-pull`, which has a hyphen in it. Maybe that's it. How about your checks, @jaxxstorm?

**Comment by rmc3** [comment]
We have several checks with hyphens in their names. Hasn't caused us any issues.

**Comment by nhooey** [comment]
@rmc3 What else would be helpful?

When I click the checks dropdown, and select any non-`keepalive` check, I see nothing in the Chrome JavaScript console, and no XHR requests are made.

**Comment by nhooey** [comment]
@rmc3 I'll see if I can debug the JavaScript myself since you guys can't reproduce.

Let me know if you have any advice that would save me time while trying to do that.

**Comment by nhooey** [comment]
@rmc3 @palourde What is the function that generates the list of check results?

**Comment by palourde** [comment]
Thanks for the PR @nhooey, I'll have a look at it today!

**Comment by nhooey** [comment]
@palourde Could you cut a new release with this fix in it? I haven't found it in any `uchiwa-web` tags.

**Comment by nhooey** [comment]
@calebhailey Is this getting released this week?

**Comment by calebhailey** [comment]
@nhooey sorry for the delay. I had hoped we could cut a release on Monday, but something is holding it up. I've been away from my desk all week so I'm not sure exactly what the situation is. I'll be back at my desk on Monday morning and @palourde will be back from vacation next week too, so it shouldn't be too much longer.

**Comment by nhooey** [comment]
@calebhailey @palourde Can you guys cut a release tomorrow? This bug is pretty debilitating.

**Comment by nhooey** [comment]
@calebhailey @palourde This bug still happens with version `0.14.3-1` from Ubuntu's Apt repository.

I've confirmed that my change is in the JavaScript, but the filter still breaks in exactly the same way as described in this bug. I'm not sure why it's happening.

**Comment by palourde** [comment]
@nhooey This bugfix is included starting from the 0.14.4 version. It will be added to the repositories today, meanwhile you can grab the latest release here: https://uchiwa.io/#/download

**Comment by nhooey** [comment]
@palourde Thanks.

Could you start using milestones in GitHub so it's easier to track?

**Comment by palourde** [comment]
Yes, good point!
