### ISSUE TITLE
Stale extra client attributes

### ISSUE THREAD

**Issue by julian7** [sensu/uchiwa#471]
I'm using 0.14.2-1 (as 0.14.3 is not yet available in the repository), and I found if I look at a client with extra parameters, and then look at another client, the params defined in the old one, but not in new also appear. It doesn't work for the third client though: only the extra parameters in the new client will be shown in the first client's detailed view.

**Comment by rodriguesalex** [comment]
i have observed this weird behavior as well, though it seems to rectify itself if i refresh my page after a few seconds
