### ISSUE TITLE
Feature request Be able to search for checks inside executioners

### ISSUE THREAD

**Issue by jonasdaman** [sensu/uchiwa#476]
Be able to search for checks inside executioners.

**Comment by palourde** [comment]
Sorry for the delay.

Could you provide us a detailed example of this use case? Unfortunately I'm not sure to understand the use case.

Thanks!

**Comment by palourde** [comment]
I'm closing this issue since we didn't received any responses.

If you are still facing this problem, please let us know with a comment and we'll be happy to reopen the issue.

Thanks!
