### ISSUE TITLE
Feature Request Persistent Check Sorting

### ISSUE THREAD

**Issue by AirCombat** [sensu/uchiwa#479]
Hi,

On the client page, it would be great if checks could be sorted by name or if the UI could remember our sorting preferences. If you have a lot of checks its a pain having to Ctrl+F for them or looking through a long list.

**Comment by calebhailey** [comment]
@AirCombat thank you for submitting this issue! We're tagging this for inclusion in the 0.15 release as a new feature. The client detail view currently displays checks in order of check status, in descending order (with no secondary sort condition). We will change this to sort by status, then check name.

**Comment by palourde** [comment]
It seems that we have few duplicated issues for this feature, I'll close this one in favor of https://github.com/sensu/uchiwa/issues/156 so it will be easier to keep everyone informed about the progress.
