### ISSUE TITLE
Honor Sensu client "notification" attribute in events pane

### ISSUE THREAD

**Issue by johntdyer** [sensu/uchiwa#481]
Sensu has the concept of a "notification" field for a check [1](https://sensuapp.org/docs/0.21/checks#sensu-plugin-attributes) which allows you to override the output of the check command w/ something more meaningful.  Uchiwa doesn't honor this and instead shows the output of the command.

**Comment by calebhailey** [comment]
@johntdyer hi there! 👋  

We have recently improved the documentation to clarify that the `notification` attribute is _not_ a part of the [Sensu check definition specification][1], but rather a [custom check definition attribute][2] that happens to be supported by the [`sensu-plugin` gem][3]. Having said that, I do see some merit in your suggestion that a "user-friendly" description of an issue may be more appropriate to show in the dashboard than the check `output`. However, this would be a somewhat opinionated change, which we would need to make configurable, at which point we'd be taking Uchiwa in a completely different direction than it is currently headed. 

At this time we're going to give this issue the "Customizations" label as part of an ongoing issues triage. We may revisit this idea (and related ideas) as part of a bigger conversation around dashboard customizations.

**Comment by annaplotkin** [comment]
This type of context will be present in the Sensu Go web UI.
