### ISSUE TITLE
Is there any plan to add a  feature in uchiwa to change the configuration of checks and other related things?

### ISSUE THREAD

**Issue by narang** [sensu/uchiwa#482]
Hi there,

Is there any plan to add a feature in uchiwa whereby I can add a new check, delete a check or change the configuration of some check? I think it would be a really useful feature because then people would not have to login to the host where sensu server runs to do all these things. 

Thanks
Sourabh

**Comment by narang** [comment]
I am new to GitHub , so I am not sure whether this is the right place to ask such questions. Please let me know if there is any other forum I can ask such questions.

**Comment by calebhailey** [comment]
@narang thank you for submitting this issue! One of Sensu's core design tenets is its dependency on configuration for automation and security purposes, among other reasons. Having said that, it is possible to define checks which are not regularly scheduled by using the [`"publish": false` check definition attribute][1], and then [submitting adhoc check requests][2] via the Uchiwa dashboard. 

Aside from this example solution, there are no plans to support arbitrary check execution requests via the Uchiwa dashboard. We're going to go ahead and close this issue at this time, however please feel free to comment and/or open a new issue if you should have any further questions. 👍 

#monitoringlove 

[1]: https://sensuapp.org/docs/latest/checks#check-attributes 
[2]: http://docs.uchiwa.io/en/latest/features/issuing-check-requests/
