### ISSUE TITLE
Unchiwa can't connect to the Sensu API

### ISSUE THREAD

**Issue by ulrith** [sensu/uchiwa#483]
I have Sensu 0.23.1 and Uchiwa (0.14.2) on Centos 6.7 and Uchiwa can't connect to the API (on the same machine).

The error is "Datacenter Sensu returned: Connection error. Is the Sensu API running?"

I have the following in the logs:

```
{"timestamp":"2016-04-21T13:38:00.076106951+03:00","level":"warn","message":"GET http://sensu.gustaff.eu:4567/stashes returned: Get http://sensu.mydomain.tld:4567/stashes: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"}
{"timestamp":"2016-04-21T13:38:00.076201324+03:00","level":"warn","message":"Connection failed to the datacenter Sensu"}
{"timestamp":"2016-04-21T13:38:00.076239578+03:00","level":"info","message":"Updating the datacenter Sensu"}
```

**Comment by wbrodie** [comment]
Hi, This may be your issue:

https://github.com/sensu/sensu/issues/1209

Theres was change with the newest version of Sensu where localhost is ::1 and not 127.0.0.1 but Redis is ipv4 only. Changing localhost ot 127.0.0.1 in your configs may fix it.

**Comment by ulrith** [comment]
Thank you very much @wbrodie ! After I changed localhost to 127.0.0.1 everything works again!

**Comment by calebhailey** [comment]
Closing this issue as it appears to have been resolved (and wasn't an issue with Uchiwa). 

#monitoringlove
