### ISSUE TITLE
Unclear on how to utilize iframe injection for static images

### ISSUE THREAD

**Issue by cmeisinger** [sensu/uchiwa#484]
I would like to utilize inline images with checks as shown in https://github.com/sensu/uchiwa/issues/361 . 

The thing that's killing me is that check token expansion doesn't seem to occur, so :::name::: never gets translated when doing something like this...
`      load_avg: http://grafana.host.com:3030/render/dashboard-solo/db/host-stats?panelId=1&var-hostname=:::name:::&width=750&height=200&sensu.png`

As I have my checks defined on the sensu-servers, I can't dynamically craft the URLs and need to rely on check tokens.

Is there a good way to do this?

Thanks for all the hard work btw, Uchiwa is a great piece of software!

**Comment by calebhailey** [comment]
@cmeisinger hi there! Thank you for submitting this issue. It looks like the issue you're having is a common misunderstanding about Sensu's [check `command` token substitution][1]. Token substitution currently only works for the check `command` attribute, not for custom attributes. We're going to go ahead and close this issue as unrelated to Uchiwa. Please feel free to create an issue in [sensu/sensu][2] if this matter is not resolved. 

[1]: https://sensuapp.org/docs/latest/checks#check-command-tokens 
[2]: https://github.com/sensu/sensu/issues

**Comment by hany** [comment]
Hi there,

I too am trying to achieve what @cmeisinger is attempting. Understanding the token substitution is for commands only, is there a way to achieve this goal?
