### ISSUE TITLE
Client names sorting sensitive to case

### ISSUE THREAD

**Issue by AirCombat** [sensu/uchiwa#485]
The sorting of client names in Uchiwa is sensitive to case.

That mean server Aaaaa comes after axaaa etc...

It meant my servers are unevenly sorted based on OS

Maybe adding a toLowerCase() to sort?

**Comment by calebhailey** [comment]
@AirCombat thank you for submitting this issue. We're tagging this for inclusion in the 0.15 release!

**Comment by palourde** [comment]
Hi @AirCombat,

According to the Angular [orderBy](https://docs.angularjs.org/api/ng/filter/orderBy) documentation, the name are compared _alphabetically in a case- and locale-insensitive way_.

However, a second ordering is done, based on the client status, which might explain why you saw the server _Aaaaa_ after _axaaa_, e.g.:

<img width="226" alt="screen shot 2016-06-22 at 12 47 06" src="https://cloud.githubusercontent.com/assets/4105580/16281186/ff40fc94-3877-11e6-87ee-4e3a8bfeda58.png">
 
If you then order explicitly the clients based on name by clicking on the _name_ column title, you'll have the clients ordered exclusively by name:

<img width="241" alt="screen shot 2016-06-22 at 12 50 18" src="https://cloud.githubusercontent.com/assets/4105580/16281228/31f4fa82-3878-11e6-8ab7-8e053dbfe5da.png">

Let me know if you have any other questions!
