### ISSUE TITLE
Feature Request - Add 'healthy' and 'not-healthy' values to 'check' filter on 'Events' page

### ISSUE THREAD

**Issue by AirCombat** [sensu/uchiwa#486]
In a standalone client setup, it would be great to see a list of all unique check names for all clients and upon selecting that check being able to see the most recent response from all clients with that check.

As en example, I checks for how recently Yum updated all my Red Hat servers. It would be great if I could see a list of all servers with this check and order them by result giving me a list of which servers were updated the longest amount of time ago.

Another example is up time... generally uptime is good but very long periods of uptime can be bad so it would be useful to order all my servers by uptime...

See which servers have the most IIS connections, disk IO etc...

**Comment by nhooey** [comment]
This feature already exists. It's the "Events" page, and if you click "All Checks" and select a check, it will show you a list of clients subscribed to that check, and their last return value.

**Comment by wbrodie** [comment]
Hey! My events page is empty. I mean non failing checks.

**Comment by nhooey** [comment]
Ah, in that case, this issue should be changed to: "Add 'healthy' and 'not-healthy' values to 'check' filter on 'Events' page". Could you update your title?

Also the `check` filter is currently broken. A fix was added, but I'm not sure if it's been deployed to the Ubuntu/Debian repositories yet.

**Comment by AirCombat** [comment]
Done
