### ISSUE TITLE
Feature Request - Aggregate and filter standalone clients based on environment

### ISSUE THREAD

**Issue by AirCombat** [sensu/uchiwa#487]
So currently I have standalone clients spread across numerous AWS VPCs and DataCentres

It would be great if there was a way of filtering clients (irrelevant of whether they are healthy) based on variables such as environment

**Comment by calebhailey** [comment]
@AirCombat Uchiwa does currently offer support for searching for custom attribute values (by value only). Have you tried this? More extensive search functionality is available in the Sensu Enterprise dashboard (which is based on Uchiwa), which we call "Collections". See here for example: https://sensuapp.org/docs/latest/enterprise-dashboard-collections
