### ISSUE TITLE
CLOSE_WAIT connections on sensu-api/uchiwa port

### ISSUE THREAD

**Issue by suraj-kamath** [sensu/uchiwa#488]
Hi ,
      We have a setup of sensu high availability architecture, with three sensu-servers in place. The sensu-api runs on the default port 4567.

Lately we have seen issues where the uchiwa UI starts flapping between events, meaning showing older or different events in different moments. This also cascades with the problem of us being not able to clear, resolve or stash/unstash checks and clients.

The sensu-api/uchiwa logs do not talk much about any specific issue, but only these (refer below): 

``
{"Date":"2016-04-07T21:05:54.481281852Z","Level":"warning","Src":{"Func":"github.com/sensu/uchiwa/uchiwa.Build","Line":73},"Output":"API call to \"http://0.0.0.0:4567/info\" returned: Get http://0.0.0.0:4567/info: read tcp 127.0.0.1:4567: use of closed network connection"} 
``

A netstat on the port 4567 revealed a good amount of stale connections: 

tcp 1 0 127.0.0.1:50137 127.0.0.1:4567 CLOSE_WAIT 27406/uchiwa 
tcp 1 0 127.0.0.1:48517 127.0.0.1:4567 CLOSE_WAIT 27406/uchiwa 
tcp 1 0 127.0.0.1:50122 127.0.0.1:4567 CLOSE_WAIT 27406/uchiwa 
tcp 1 0 127.0.0.1:51111 127.0.0.1:4567 CLOSE_WAIT 27406/uchiwa 
tcp 1 0 127.0.0.1:53087 127.0.0.1:4567 CLOSE_WAIT 27406/uchiwa 
tcp 1 0 127.0.0.1:57519 127.0.0.1:4567 CLOSE_WAIT 27406/uchiwa 
tcp 0 0 127.0.0.1:4567 127.0.0.1:42509 ESTABLISHED 10304/ruby 
tcp 1 0 127.0.0.1:55653 127.0.0.1:4567 CLOSE_WAIT 27406/uchiwa 
tcp 1 0 127.0.0.1:37483 127.0.0.1:4567 CLOSE_WAIT 27406/uchiwa 
tcp 1 0 127.0.0.1:52022 127.0.0.1:4567 CLOSE_WAIT 27406/uchiwa 
tcp 1 0 127.0.0.1:38337 127.0.0.1:4567 CLOSE_WAIT 27406/uchiwa 
tcp 1 0 127.0.0.1:53389 127.0.0.1:4567 CLOSE_WAIT 27406/uchiwa 
tcp 1 0 127.0.0.1:53321 127.0.0.1:4567 CLOSE_WAIT 27406/uchiwa 

The only known work-around is to kill the sensu-api and uchiwa and start them afresh, but over due time this issue recurs.

Following is the version details:
``
sensu-server-0.12.2-1.x86_64 
``
``
uchiwa-0.4.0-1.x86_64
``

I see there are a couple of related issue's but none like this:
https://github.com/sensu/uchiwa/issues/309
https://github.com/sensu/uchiwa/issues/329
https://github.com/sensu/sensu/issues/1051

Would like to understand this behaviour of sensu-api/uchiwa and obtain a permanent fix for this.
Let me know if you need additional info.

Thanks

**Comment by calebhailey** [comment]
@suraj-kamath thank you for submitting this issue. It looks like you're using _extremely_ old versions of Sensu and Uchiwa! Sensu version 0.12.2 was [released in November 2013][1] (!), which was 6 months before the first commit to Uchiwa; Uchiwa version 0.4 was [released in December 2014][2]. We're going to go ahead and close this issue with the recommendation to upgrade to the latest releases of Sensu (version 0.23) and Uchiwa (version 0.14). Please feel free to comment on this issue and/or open a new issue if you continue to see this behavior after upgrading. 

Thanks! 

[1]: https://github.com/sensu/sensu/blob/master/CHANGELOG.md#0122---2013-11-22
[2]: https://github.com/sensu/uchiwa/blob/master/CHANGELOG.md#040-2014-12-08
