### ISSUE TITLE
Complex client attributes not rendered properly

### ISSUE THREAD

**Issue by klynch** [sensu/uchiwa#490]
After upgrading to Uchiwa 14.3, it appears as though complex client attributes are no longer being rendered.

For example, custom attributes such as `rabbitmq: {password: "REDACTED", username: "blah", port: 6571}` would appear in the dashboard.

However, after upgrade the same information is being rendered as `[object Object]`.

**Comment by calebhailey** [comment]
@klynch we think this might have been fixed in the 14.4 release (https://github.com/sensu/uchiwa-web/commit/7d8fa993ea8f87feb27957823aabb37898ccc2cc). Can you upgrade and let us know if you're still seeing this behavior? 

Thanks!

**Comment by klynch** [comment]
I've been using the RPM packages, which have not yet been updated. In the meantime, I will work on verifying this!

**Comment by klynch** [comment]
Confirmed working now.
