### ISSUE TITLE
Ubuntu 14.0.4 Software Center reports error during installation

### ISSUE THREAD

**Issue by addiscent** [sensu/uchiwa#491]
On a system with no version of Uchiwa previously installed:
-  Download Uchiwa using Chrome browser at URL:
       http://dl.bintray.com/palourde/uchiwa/uchiwa_0.14.5-1_amd64.deb
-  Double-click on downloaded filename, Software Center loads and shows "Install" button
-  Click "Install" button, Software Center displays the following message:

"The package is of bad quality

The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.

Lintian check results for /home/xxx/Downloads/uchiwa_0.14.5-1_amd64.deb:
E: uchiwa: maintainer-name-missing Simon Plourde simon.plourde@gmail.com
E: uchiwa: maintainer-address-malformed Simon Plourde simon.plourde@gmail.com
Use of uninitialized value $name in pattern match (m//) at /usr/share/perl5/Lintian/Check.pm line 203."
-  Choose "Install Anyway" button, Software Center reports "Installation Successful".
-  Set Uchiwa configuration per Uchiwa website instructions, Uchiwa appears to work OK.

**Comment by annaplotkin** [comment]
We believe this is resolved. Closing.
