### ISSUE TITLE
debian package with wrong version number causes "downgrade"

### ISSUE THREAD

**Issue by kosli** [sensu/uchiwa#502]
there is a version number in the uchiwa debian repository that force the client to "downgrade" to this old 0.14.0 release, e.g.:

apt-cache show uchiwa |grep Version
Version: 1:0.14.0-1
Version: 0.14.5-1
Version: 0.14.4-1
Version: 0.14.3-1
Version: 0.14.2-1
Version: 0.14.1-1
Version: 0.13.0-1
Version: 0.12.1-1
Version: 0.12.0-1
Version: 0.11.2-1

it's in the repo @ http://repositories.sensuapp.org/apt/dists/sensu/main/binary-i386/Packages

**Comment by palourde** [comment]
Hi,

Thank you for submitting this issue. The 0.14.0 deb packages were removed. Also, please note that the 0.15.0-1 packages are now available.

Please let us know if there's anything else!

**Comment by kosli** [comment]
just updated to 0.15.0-1 and works as expected. thank you.
