### ISSUE TITLE
don't show aggregated's check

### ISSUE THREAD

**Issue by orelhinhas** [sensu/uchiwa#504]
Hi ppl, 

I updated Sensu and Uchiwa to 0.24 and 0.15 and after this, the aggregation's tab doesn't show the aggregated checks only show state's counter. This behaviour was expected?

tks

**Comment by palourde** [comment]
Hi @orelhinhas,

Please make sure to restart Uchiwa (and possibly the Sensu processes if not already done). Let me know if you still have any trouble.

Thanks

**Comment by joaogabriel-luizalabs** [comment]
Hi @palourde,

I tried to restart (server, api and uchiwa) but the same was happen.

<img width="1384" alt="screen shot 2016-06-08 at 6 50 02 pm" src="https://cloud.githubusercontent.com/assets/14184766/15912387/546ebf72-2daa-11e6-9fa8-780d48e740c4.png">

Thanks

**Comment by palourde** [comment]
Hi @orelhinhas,

This result is expected since the aggregates API in Sensu was modified, see the new specifications for this endpoint: https://sensuapp.org/docs/0.24/api/aggregates-api.html

You can expect Uchiwa to support the additional endpoints in a near future.
