### ISSUE TITLE
https private key parsing error

### ISSUE THREAD

**Issue by kaushiksriram100** [sensu/uchiwa#505]
I got the root, intermediate certs and private key from by company and when I plug it in I get this error. ANy pointers on how I should go debugging it? It works ok with self signed certificate. I don't think this is related to Uchiwa but I am not able to see where I should start debugging this. 

[root@server ssl]# tail -f /var/log/uchiwa.log 
{"timestamp":"2016-06-09T12:36:46.979557864-07:00","level":"warn","message":"Loading the configuration file /etc/sensu/uchiwa.json"}
{"timestamp":"2016-06-09T12:36:46.980677426-07:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/auth.loadToken","line":52},"message":"Attempting to load the RSA keys from the filesystem"}
{"timestamp":"2016-06-09T12:36:46.980755553-07:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/auth.initToken","line":90},"message":"The paths to the private and public RSA keys were not provided"}
{"timestamp":"2016-06-09T12:36:46.980832896-07:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/auth.generateToken","line":40},"message":"Generating new temporary RSA keys"}
{"timestamp":"2016-06-09T12:36:46.980832896-07:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/auth.generateToken","line":40},"message":"Generating new temporary RSA keys"}
{"timestamp":"2016-06-09T12:36:46.981048606-07:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(_Sensu).getSlice","line":50},"message":"GET http://localhost:4566/stashes"}
{"timestamp":"2016-06-09T12:36:47.224804324-07:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(_Sensu).getSlice","line":50},"message":"GET http://localhost:4566/checks"}
{"timestamp":"2016-06-09T12:36:47.24930007-07:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(_Sensu).getSlice","line":50},"message":"GET http://localhost:4566/clients"}
{"timestamp":"2016-06-09T12:36:47.426322792-07:00","level":"warn","src":{"func":"github.com/sensu/uchiwa/uchiwa.(_Uchiwa).WebServer","line":537},"message":"Uchiwa is now listening on 0.0.0.0:3000"}
{"timestamp":"2016-06-09T12:36:47.426951702-07:00","level":"fatal","src":{"func":"github.com/sensu/uchiwa/uchiwa.(*Uchiwa).WebServer","line":540},"message":"crypto/tls: failed to parse private key"}
c^C

**Comment by palourde** [comment]
Thank you for reporting this issue. Could you provide me your current Uchiwa configuration? Also, make sure to include the intermediates certificates in the PEM file specified in the _certfile_ attribute.

As stated by the error message, it looks like your private key is not properly formatted.

**Comment by kaushiksriram100** [comment]
@palourde : I have one pem file that includes root, intermediate and private keys (all in one file). I separated the private key and added to uchiwa.key and the rest is in uchiwa.pem. 

"uchiwa": {
        "host": "0.0.0.0",
        "port": 3000,
        "loglevel": "info",
        "refresh": 10,
	"ssl": {
          "certfile": "/etc/sensu/uchiwa/ssl/uchiwa.pem",
          "keyfile": "/etc/sensu/uchiwa/ssl/uchiwa.key"
        },

**Comment by palourde** [comment]
Hi @kaushiksriram100,

I'm sorry, this issue completely passed under my radar. Were you able to make it work?

**Comment by palourde** [comment]
I'm closing this issue since we didn't received any responses.

If you are still facing this problem, please let us know with a comment and we'll be happy to reopen the issue.

Thanks!

**Comment by kaushiksriram100** [comment]
Sorry for the delay. I haven't checked this of late. Will reopen if I find issues.
