### ISSUE TITLE
Stash cannot be "ticked" or deleted from interface

### ISSUE THREAD

**Issue by xlr-8** [sensu/uchiwa#507]
Hello,

It seems there is a bug with the Uchiwa interface version 0.15.0 with sensu 0.15.1-1.
On the `/#/stashes` URL, I cannot tick nor delete stashes anymore.

I tested both on Chromimum 51.0.2704.79 and Firefox 46.0.1. Is it something you observe as well?

Kind regards,

**Comment by palourde** [comment]
Hi @xlr-8,

Thank you for reporting this issue. It's indeed something I was able to reproduce, I will have a patch ready as soon as possible.

Thanks
