### ISSUE TITLE
iframe not behaving as expected, element not created in dashboard

### ISSUE THREAD

**Issue by scosist** [sensu/uchiwa#508]
I tried `"grafana_test_iframe": "iframe:http://example.url/provided/by/grafana/iframe/src"` in the client configuration but no graph was displayed. The url wasn't shown either. All I got was:

`grafana_test_iframe {}`

I noticed at some point the original PR(#195) that added support for this was dropped and then re-implemented with [4f21f0b](https://github.com/sensu/uchiwa-web/pull/59/commits/4f21f0ba82e04d5fe189c95ff3c44dd2b6683f32) (#59). I double checked filters.js to make sure I had that change but I can't seem to get the iframe. Any ideas?

I'm running uchiwa on debian jessie, package version: 0.11.2-1

Issue mentioned in sensu/sensu#1281

**Comment by runningman84** [comment]
@palourde are iframes supported in the latest 0.16 release?

**Comment by palourde** [comment]
The path for this issue will be include in the 0.16.1 release. Thanks for reporting it!
