### ISSUE TITLE
Latest version is not showing some client data fields correctly

### ISSUE THREAD

**Issue by jbehrends** [sensu/uchiwa#509]
uchiwa-0.15.0-1
sensu-0.25.3-1

Under the client view both "keepalive" and "socket" are not showing correct data:

![image](https://cloud.githubusercontent.com/assets/1915783/16242197/2f9b21f8-37a6-11e6-9a89-c23705c310bd.png)

**Comment by palourde** [comment]
Hi @jbehrends,

Thank you for reporting this issue! I'm however unable to reproduce it. Could you try to fire up your browser console and let us know if you have any errors showing up? Also, did you tried to clean your browser cache?

**Comment by jbehrends** [comment]
*sigh*  I just revisited this issue and it seems it's no longer an issue...  Closing.
