### ISSUE TITLE
Option to trust HTTP-username

### ISSUE THREAD

**Issue by UnitedMarsupials** [sensu/uchiwa#510]
In order to allow users to authenticate against our corporate mechanism, we will front Uchiwa with an Apache-based proxy. Apache will verify the user's credentials and forward the request -- including the username -- to Uchiwa.

We'd like Uchiwa to accept that username and treat each such user according to settings for their `role`s -- without asking for password, indeed, without even having the password-fields in the `"users":`-substree of the configuration JSON.

Can such a feature be added, please?

**Comment by palourde** [comment]
Thank you for opening an issue! We already have a similar request (https://github.com/sensu/uchiwa/issues/295) for this feature so I'll go ahead and close this one to avoid any confusion.
