### ISSUE TITLE
Old alert doesn't disappear

### ISSUE THREAD

**Issue by mikrob** [sensu/uchiwa#512]
Since i have upgraded sensu to 0.25.3-1, old alert already resolved stay alive in uchiwa dashboard.

Restarting uchiwa solve the problem. But it's boring to restart uchiwa all the time.

**Comment by mikrob** [comment]
For additional informations, sensu api/server do the good work because i also use opsgenie for SMS alerting and OPS Genie alert are always update.

**Comment by palourde** [comment]
Hi @mikrob,

Which version of Uchiwa are you using? I would highly recommend you to try upgrading to 0.16.0 (just released few moments ago).

Thanks

**Comment by mikrob** [comment]
I use 0.15.0-1, ok i am going so try to upgrade to 16.0 but it doesn't seem to be available in apt repository ? 

Is this one the good one ? http://sensu.global.ssl.fastly.net/apt sensu main

**Comment by fattylewis** [comment]
Hi All,

I'm just chiming to say im seeing the same thing as mikrob. I have just updated to 0.16.0.
The menu on the left seems to update. But the main "events" window never clears the alert.

Cheers!

**Comment by palourde** [comment]
@mikrob The packages will be available in the repositories during the day. Meanwhile, you can grab these manually here: https://uchiwa.io/#/download

@fattylewis Could you provide me a screenshot of this behaviour and fire up your browser console to see if there's any errors?

Thanks!

**Comment by fattylewis** [comment]
Sure, here you go: http://imgur.com/FyqiIHS

So this is a really bare system, one external host running 2 checks. Nothing fancy. 
The Events screen refreshes to show the check failing, but never removes that failure after i bring the httpd server back up. Though as you can see, the menu on the left does show the check failure has gone.

**Comment by palourde** [comment]
@fattylewis Thank you very much! I'll try to reproduce this issue and have a patch as soon as possible.

**Comment by palourde** [comment]
Unfortunately I was unable to reproduce this issue; I mocked a check that randomly pass from a critical to a success state and it properly disappeared from the events list when resolved.

If you are able to reproduce this problem, could you provide me the Uchiwa logs, the Sensu API data on the events endpoint (e.g. `http://SENSU_API:4567/events`) and if you do not use authentication with Uchiwa, the Uchiwa data for the same endpoint (e.g. `http://UCHIWA:3000/events`)

Thanks!

**Comment by fattylewis** [comment]
Sure thing.

Here is the SENSU_AP/events when the check has failed:

`[{"client":{"name":"remote-test-1","address":"localhost","subscriptions":["ALL"],"version":"0.25.3","timestamp":1466788849},"check":{"command":"/etc/sensu/plugins/check-apache.rb","interval":60,"subscribers":["ALL"],"name":"apache_check","issued":1466788852,"executed":1466788853,"duration":0.085,"output":"CRITICAL - Apache daemon is NOT running\n","status":2,"type":"standard","history":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","2"],"total_state_change":6},"occurrences":1,"action":"create","timestamp":1466788852,"id":"46098dc4-460c-4411-9cfa-ca0dda117fad","last_state_change":1466788852}]`

And here UCHIWA/events when the check has failed:

`[{"_id":"Sensu/remote-test-1/apache_check","acknowledged":false,"action":"create","check":{"command":"/etc/sensu/plugins/check-apache.rb","duration":0.085,"executed":1.466788853e+09,"history":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","2"],"interval":60,"issued":1.466788852e+09,"name":"apache_check","output":"CRITICAL - Apache daemon is NOT running\n","status":2,"subscribers":["ALL"],"total_state_change":6,"type":"standard"},"client":{"acknowledged":false,"address":"localhost","name":"remote-test-1","subscriptions":["ALL"],"timestamp":1.466788849e+09,"version":"0.25.3"},"dc":"Sensu","id":"46098dc4-460c-4411-9cfa-ca0dda117fad","last_state_change":1.466788852e+09,"occurrences":1,"timestamp":1.466788852e+09}]`

Here are both when the check tehn becomes OK again:

SENSU_API:

`[]`

UCHIWA /events:

`null`

Here is the uchiwa.log:

```
{"timestamp":"2016-06-24T18:24:56.643400893+01:00","level":"info","message":"Updating the datacenter Sensu"}
{"timestamp":"2016-06-24T18:25:06.643385311+01:00","level":"info","message":"Updating the datacenter Sensu"}
{"timestamp":"2016-06-24T18:25:16.643389037+01:00","level":"info","message":"Updating the datacenter Sensu"}
{"timestamp":"2016-06-24T18:25:26.643391616+01:00","level":"info","message":"Updating the datacenter Sensu"}
{"timestamp":"2016-06-24T18:25:36.643383492+01:00","level":"info","message":"Updating the datacenter Sensu"}
```

And the error log is blank.

And finally, uchiwa.log with logging level set to debug:

`{"timestamp":"2016-06-24T18:29:50.67587266+01:00","level":"info","src":{"func":"github.com/sensu/uchiwa/uchiwa/daemon.(*Daemon).fetchData","line":73},"message":"Updating the datacenter Sensu"}
{"timestamp":"2016-06-24T18:29:50.675985645+01:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getSlice","line":50},"message":"GET http://127.0.0.1:4567/stashes"}
{"timestamp":"2016-06-24T18:29:50.677252005+01:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getSlice","line":50},"message":"GET http://127.0.0.1:4567/checks"}
{"timestamp":"2016-06-24T18:29:50.677891243+01:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getSlice","line":50},"message":"GET http://127.0.0.1:4567/clients"}
{"timestamp":"2016-06-24T18:29:50.678892268+01:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getSlice","line":50},"message":"GET http://127.0.0.1:4567/events"}
{"timestamp":"2016-06-24T18:29:50.679789412+01:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getBytes","line":35},"message":"GET http://127.0.0.1:4567/info"}
{"timestamp":"2016-06-24T18:29:50.680996268+01:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getSlice","line":50},"message":"GET http://127.0.0.1:4567/aggregates"}
{"timestamp":"2016-06-24T18:30:00.675863005+01:00","level":"info","src":{"func":"github.com/sensu/uchiwa/uchiwa/daemon.(*Daemon).fetchData","line":73},"message":"Updating the datacenter Sensu"}
{"timestamp":"2016-06-24T18:30:00.675963384+01:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getSlice","line":50},"message":"GET http://127.0.0.1:4567/stashes"}
{"timestamp":"2016-06-24T18:30:00.677292229+01:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getSlice","line":50},"message":"GET http://127.0.0.1:4567/checks"}
{"timestamp":"2016-06-24T18:30:00.677965935+01:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getSlice","line":50},"message":"GET http://127.0.0.1:4567/clients"}
{"timestamp":"2016-06-24T18:30:00.679039077+01:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getSlice","line":50},"message":"GET http://127.0.0.1:4567/events"}
{"timestamp":"2016-06-24T18:30:00.67992616+01:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getBytes","line":35},"message":"GET http://127.0.0.1:4567/info"}
{"timestamp":"2016-06-24T18:30:00.681118297+01:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getSlice","line":50},"message":"GET http://127.0.0.1:4567/aggregates"}
{"timestamp":"2016-06-24T18:30:10.675872601+01:00","level":"info","src":{"func":"github.com/sensu/uchiwa/uchiwa/daemon.(*Daemon).fetchData","line":73},"message":"Updating the datacenter Sensu"}
{"timestamp":"2016-06-24T18:30:10.675967978+01:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getSlice","line":50},"message":"GET http://127.0.0.1:4567/stashes"}
{"timestamp":"2016-06-24T18:30:10.677282121+01:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getSlice","line":50},"message":"GET http://127.0.0.1:4567/checks"}
{"timestamp":"2016-06-24T18:30:10.677950458+01:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getSlice","line":50},"message":"GET http://127.0.0.1:4567/clients"}
{"timestamp":"2016-06-24T18:30:10.678929817+01:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getSlice","line":50},"message":"GET http://127.0.0.1:4567/events"}
{"timestamp":"2016-06-24T18:30:10.679799821+01:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getBytes","line":35},"message":"GET http://127.0.0.1:4567/info"}
{"timestamp":"2016-06-24T18:30:10.681052858+01:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getSlice","line":50},"message":"GET http://127.0.0.1:4567/aggregates"}
`

For what its worth. This is a CentOS 7 machine. 

If you need anything else, let me know. 

Cheers!

**Comment by palourde** [comment]
Thanks @fattylewis!

I was able to reproduce it when passing from one to zero event; looks like the frontend does not properly handle the null response. I'll have a patch ready soon.

**Comment by fattylewis** [comment]
Fantastic. Thanks for your help. Really looking forward to getting this into production :)
