### ISSUE TITLE
Release 0.16 at apt repo

### ISSUE THREAD

**Issue by runningman84** [sensu/uchiwa#514]
the latest package is still 0.15:
```
apt-cache show uchiwa | head
Package: uchiwa
Version: 0.15.0-1
```

**Comment by palourde** [comment]
Hi @runningman84 

The 0.16.0 packages are going to be available in the repositories in the next few hours, sorry for the inconvenience. Meanwhile, you can grab these here: https://uchiwa.io/#/download

Thanks

**Comment by runningman84** [comment]
can you push the latest sensu package too?

**Comment by palourde** [comment]
@runningman84 The 0.16.0 packages are now uploaded to the repositories.

Concerning the Sensu packages, it should be available in the next few days. You can safely use 0.25.3 version.

Thanks
