### ISSUE TITLE
Wrong client timestamp

### ISSUE THREAD

**Issue by bovy89** [sensu/uchiwa#519]
Original issue: https://github.com/sensu/uchiwa/issues/456
This bug still exists:

Release 0.13 (correct)
![013_img1](https://cloud.githubusercontent.com/assets/697408/16595790/2eff2342-42f1-11e6-9885-31a12011eec9.png)
![013_img2](https://cloud.githubusercontent.com/assets/697408/16595789/2ef61b26-42f1-11e6-9e5a-e10bc3dbf353.png)

Release > 0.13 (bugged)
![016_img1](https://cloud.githubusercontent.com/assets/697408/16595788/2ee6ba78-42f1-11e6-8400-e7796fdf2a7d.png)
![016_img2](https://cloud.githubusercontent.com/assets/697408/16595787/2ecf3074-42f1-11e6-8076-2a9d21b1c244.png)

**Comment by palourde** [comment]
Seems related to https://github.com/sensu/uchiwa/issues/541, we will continue to track this problem in this last issue.

Thanks for reporting it!
