### ISSUE TITLE
Uchiwa not opening

### ISSUE THREAD

**Issue by vijayrabha** [sensu/uchiwa#520]
Hello,
I have configure sensu-0.20.3-1.x86_64 around last week. Everything was working as expected until Friday when uchiwa not opening. I tried to find out the issue by looking in to logs but couldn't find anything. Strange thing is that I a still getting normal alerts from client. Also Keep getting keeplive alerts. 
tried to google the issue but couldn't find anything. I'll attach a log snippet.
![capture](https://cloud.githubusercontent.com/assets/16815272/16758655/87135474-4830-11e6-96d0-cd01af1afd37.PNG)

-sh-4.1$ tailf sensu-api.log
{"timestamp":"2016-07-12T00:30:18.430587-0700","level":"info","message":"GET /info","remote_address":"127.0.0.1","user_agent":"Go 1.1 package http","request_method":"GET","request_uri":"/info","request_body":""}
{"timestamp":"2016-07-12T00:30:18.435718-0700","level":"info","message":"GET /aggregates","remote_address":"127.0.0.1","user_agent":"Go 1.1 package http","request_method":"GET","request_uri":"/aggregates","request_body":""}
{"timestamp":"2016-07-12T00:30:18.438965-0700","level":"info","message":"GET /results","remote_address":"127.0.0.1","user_agent":"Go 1.1 package http","request_method":"GET","request_uri":"/results","request_body":""}
{"timestamp":"2016-07-12T00:30:28.407728-0700","level":"info","message":"GET /stashes","remote_address":"127.0.0.1","user_agent":"Go 1.1 package http","request_method":"GET","request_uri":"/stashes","request_body":""}
{"timestamp":"2016-07-12T00:30:28.450136-0700","level":"info","message":"GET /checks","remote_address":"127.0.0.1","user_agent":"Go 1.1 package http","request_method":"GET","request_uri":"/checks","request_body":""}
{"timestamp":"2016-07-12T00:30:28.453056-0700","level":"info","message":"GET /clients","remote_address":"127.0.0.1","user_agent":"Go 1.1 package http","request_method":"GET","request_uri":"/clients","request_body":""}
{"timestamp":"2016-07-12T00:30:28.458171-0700","level":"info","message":"GET /events","remote_address":"127.0.0.1","user_agent":"Go 1.1 package http","request_method":"GET","request_uri":"/events","request_body":""}
{"timestamp":"2016-07-12T00:30:28.463800-0700","level":"info","message":"GET /info","remote_address":"127.0.0.1","user_agent":"Go 1.1 package http","request_method":"GET","request_uri":"/info","request_body":""}
{"timestamp":"2016-07-12T00:30:28.467153-0700","level":"info","message":"GET /aggregates","remote_address":"127.0.0.1","user_agent":"Go 1.1 package http","request_method":"GET","request_uri":"/aggregates","request_body":""}
{"timestamp":"2016-07-12T00:30:28.469240-0700","level":"info","message":"GET /results","remote_address":"127.0.0.1","user_agent":"Go 1.1 package http","request_method":"GET","request_uri":"/results","request_body":""}

Can anyone help me with this issue. I am totally stucked.

**Comment by josephholsten** [comment]
@vijayrabha did you get this figured out?

**Comment by palourde** [comment]
I'm closing this issue since we didn't received any responses.

If you are still facing this problem, please let us know with a comment and we'll be happy to reopen the issue.

Thanks!
