### ISSUE TITLE
Unmatched client token(s) error not a valid link

### ISSUE THREAD

**Issue by Gillingham** [sensu/uchiwa#521]
This may be a combination of not properly handling the error in combination with it being a proxy check.

In the alerts view I see
![screen shot 2016-07-13 at 9 02 40 am](https://cloud.githubusercontent.com/assets/385396/16810482/dbd2eeae-48d8-11e6-89ed-fdb127de2608.png)

However if I click that alert I get taken to the client view for the proxy client, and see:
![screen shot 2016-07-13 at 9 02 51 am](https://cloud.githubusercontent.com/assets/385396/16810496/e93778b2-48d8-11e6-89b8-0b65f51798ca.png)
with no mention or details on the failing check, no matter where I click on the failing check, output, source, check etc, it always just takes me to the source page without the failing check on it.

**Comment by rodriguesalex** [comment]
We are on Uchiwa 0.15.0 and see this too

**Comment by palourde** [comment]
Hi,

I apologize for the delay, it slipped my mind. I believe this issue could have been resolved with https://github.com/sensu/uchiwa/issues/471.

If you are still facing this problem, please let us know with a comment and we'll be happy to reopen the issue.

Thanks!
