### ISSUE TITLE
check duration display appears to break for some (very-small?) values

### ISSUE THREAD

**Issue by mrasmus** [sensu/uchiwa#522]
While testing very simple extension checks in my go client, I noticed anomalous output formatting on uchiwa as it live-updated the check's results. The duration would occasionally format as just a datetime epoch ("1969-12-31 16:00:00"; server is in America/Los Angeles tz). When I was able to reproduce it, the value as read directly from the /results API endpoint was:

`    "duration": 9.278e-05,`

Which is the same representation as the output logged from my client to be sent out over the transport. Other times in the same order of magnitude (some lower, as low as ~7.0e-05) were displayed as expected (0.00007..., etc). 

More of a distraction than anything (that level of precision on that output isn't what I'd call "useful") as it flopping values with live updates is sort of confusing, but an interesting corner case in the formatting code I guess.

**Comment by palourde** [comment]
Seems related to https://github.com/sensu/uchiwa/issues/541, we will continue to track this problem in this last issue.

Thanks for reporting it!
