### ISSUE TITLE
silence checks for an entire data center

### ISSUE THREAD

**Issue by joshzitting** [sensu/uchiwa#523]
I would like to be able to silence checks for an entire data center using the uchiwa gui... This would be handy for things like env maintenatnce, network outages etc without having to silence every individual host. thanks

**Comment by runningman84** [comment]
This depends heavily on your handler setup. I have a virtual client named handler. I use uchiwa to create a stash for this client. My custom handler always checks if there is a stash for the virtual client and stops if it finds a stash for it.

**Comment by runningman84** [comment]
Maybe the new native silence concept will give us a similar feature within the core. I suggest to create a feature request in the sensu repo.

**Comment by cwjohnston** [comment]
@joshzitting @runningman84 

Under the current silencing model this would require uchiwa to create a stash for every client in the datacenter. If a new client were to register itself during an outage or maintenance window, it would not be silenced.

Once Uchiwa has been updated to support the new native silencing model (proposed in sensu/sensu#1328 and being implemented in sensu/sensu#1400), it should be possible to silence an entire datacenter by using client subscriptions to tag clients. e.g. assign subscription "dc-1" to all clients in datacenter "dc-1" and then silence that subscription as needed.

**Comment by palourde** [comment]
For reference, silencing has been implemented in Uchiwa since 0.18. Here's the associated documentation: https://docs.uchiwa.io/reference/silencing/

Let us know if you have any question.

Thanks!
