### ISSUE TITLE
uchiwa information [object Object] in 0.17.1 

### ISSUE THREAD

**Issue by DamionWaltermeyer** [sensu/uchiwa#533]
Howdy.

Configuration of Uchiwa is not showing properly in console. At least, that's my assumption since it's up and running and not throwing errors in the log.

On the https://uchiwa-server/#/info page    I get the following:
```
UCHIWA
VERSION
0.17.1
CONFIG
[object Object]
```

This is a docker container from uchiwa/uchiwa  and otherwise seems to be up and running and receiving checks from the local sensu server.

**Comment by palourde** [comment]
Hi @DamionWaltermeyer,

I'm unfortunately unable to reproduce this issue. If you do, could you try to open your browser console to see if there's any error? Also, you might want to try to clear your browser cache.

Thanks

**Comment by DamionWaltermeyer** [comment]
I'll close it.  I don't recall when it was fixed, but it is no longer doing that.  Thank you for taking a look in any event.
