### ISSUE TITLE
Feature request: Option to disable "No expiration" from uchiwa-web

### ISSUE THREAD

**Issue by ulyssesbbg** [sensu/uchiwa#538]
For uchiwa-web, can there be an option to disable the "No expiration" UI?  Perhaps an option in the conf file that toggles / untoggles this line:  https://github.com/sensu/uchiwa-web/blob/5ac7e4fc58425def1b9c7db6c8cf6d165bd33940/partials/stash-modal.html#L82

Selecting "no expiration" encourages users to be lazy instead of selecting a proper expiration time period for the stash.

**Comment by fessyfoo** [comment]
I think it's worth plugging the [`expire_on_resolve`](https://github.com/sensu/sensu/issues/1328#issuecomment-239260485) feature coming in sensu 0.26's new [built in silencing](https://github.com/sensu/sensu/issues/1328)  I think covers _some_ of the cases where people use "no expiration", but of course not all.

**Comment by josephholsten** [comment]
see also #531

**Comment by palourde** [comment]
This feature has been introduced via https://github.com/sensu/uchiwa-web/pull/117 and will be included in the 0.20 release!
