### ISSUE TITLE
support for built in silencing in sensu 0.26

### ISSUE THREAD

**Issue by fessyfoo** [sensu/uchiwa#539]
sensu 0.26 will support [built in silencing](https://github.com/sensu/sensu/issues/1328) which changes the way silencing is done.    

what are the plans for uchiwa to support this? (  [and how to migrate](https://github.com/sensu/sensu/issues/1412)? )   will uchiwa support display of both stashes and built in silencing?  or will it be a hard transition? ... 

i'm still trying to think how best to get through this, any thoughts are appreciated.

**Comment by palourde** [comment]
After investigating carefully, I believe we should drop all support for _silence stashes_ (but still support other types of stashes or at least still display them in the stashes view for the time being) and automatically use the new built-in silencing. Unfortunately, what it means is that is that the next minor release of Uchiwa will only fully support Sensu => 0.26. Supporting both silencing methods would create too much technical debt I believe.

**Comment by fessyfoo** [comment]
Thanks.    

That's an interesting point about "other types of stashes".  It's easy to forget stashes are a more generic tool than just for silencing.  Are you aware of anyone using stashes for things other than silencing and how they're using them?

**Comment by palourde** [comment]
I know the enterprise version of the uses stashes for sharing _collections_ (which might come at some point to the OSS version). I'm not aware personally of any other concrete use but I believe as long Sensu support stashes, we should at least display them and let the user delete them which I believe could be useful to ease the migration between _silence stashes_ and the new _silences_.
