### ISSUE TITLE
Basic authentication not working

### ISSUE THREAD

**Issue by UnitedMarsupials** [sensu/uchiwa#540]
I've turned on Uchiwa's "simple" authentication and am trying to access the service using basic auth. My account's entry looks like this:

```json
{
          "username":     "mteterin",
          "accessToken":  "eTcJPrVYslcO**hk7MRmOzc_",
          "password":     "fake",
          "readonly":     false
},
```
However, when I attempt to access `/metrics`, for example, using curl:
```
 # curl http://mteterin:fake@127.0.0.1:3000/metrics
```
I get 401-error. The request-headers, according to `tcpdump`, are:
```
GET /metrics HTTP/1.1
Authorization: Basic bXRldGVyaW46ZmFrZQ==
User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.21 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Host: 127.0.0.1:3000
Accept: */*
```
Note the `Authorization`-header in there, which decodes to, precisely, `mteterin:fake`. Despite the matching credentials, the request is rejected with:
```
HTTP/1.1 401 Unauthorized
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Fri, 12 Aug 2016 22:15:59 GMT
Content-Length: 21

Request unauthorized
```
A web-application requiring authentication ought to support Basic Auth... Please, advise...

**Comment by fessyfoo** [comment]
hey @UnitedMarsupials,   I'm taking a stab at answering your question from the code. 

_if i'm reading things correctly_  The api endpoints appear to only support token based authentication.   ([verifyAccessToken](https://github.com/sensu/uchiwa/blob/8aa5dce/uchiwa/authentication/accessToken.go#L69-L86))  Your example is using Basic AUTH.

try using [query param based token auth] (https://github.com/sensu/uchiwa/blob/8aa5dce/uchiwa/authentication/accessToken.go#L36-L38): 
```
# curl  'http://27.0.0.1:3000/metrics?token=eTcJPrVYslcO**hk7MRmOzc_'
```
or [token based auth in the header](https://github.com/sensu/uchiwa/blob/8aa5dce/uchiwa/authentication/accessToken.go#L19-L32):
```
# curl -H 'Authorization: Token eTcJPrVYslcO**hk7MRmOzc_' 'http://27.0.0.1:3000/metrics' 
```

I didn't test this, and I got lost in the go code so I could be wrong.  :)   it's possible the token has to be dynamically created by logging in first.    but this is where I got. 

hope this helps.

**Comment by UnitedMarsupials** [comment]
Thanks, @fessyfoo, but that's "not good enough" for my purposes. Even if I figure out the token-format ([JWT](https://jwt.io/)?), constructing such a thing from shell is too difficult. Searching through Uchiwa's repository, it seems, Baisc Auth handling was deliberately _replaced_ by JWTs at some point.

I think, this was a mistake -- whatever other authentication schemes may be supported, Basic Auth should always be one of the choices.

**Comment by fessyfoo** [comment]
tested it.  it works with the `authToken` in your config.json for the user. 

```
    "users": [
      {
        "username" : "admin",
        "password": "secret",
        "accessToken": "vFzX6rFDAn3G9ieuZ4ZhN-XrfdRow4Hd5CXXOUZ5NsTw4h3k3l4jAw__",
        "readonly": false
      }
    ]
```

```
fess@otfess-alt-8-1176% curl -v -H 'Authorization: Token vFzX6rFDAn3G9ieuZ4ZhN-XrfdRow4Hd5CXXOUZ5NsTw4h3k3l4jAw__'  http://127.0.0.1:3000/metrics
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
> GET /metrics HTTP/1.1
> Host: 127.0.0.1:3000
> User-Agent: curl/7.43.0
> Accept: */*
> Authorization: Token vFzX6rFDAn3G9ieuZ4ZhN-XrfdRow4Hd5CXXOUZ5NsTw4h3k3l4jAw__
> 
< HTTP/1.1 200 OK
< Date: Sat, 13 Aug 2016 04:54:31 GMT
< Content-Length: 527
< Content-Type: text/plain; charset=utf-8
< 
{"aggregates":{"critical":0,"healthy":0,"silenced":0,"total":0,"unknown":0,"warning":0},"checks":{"critical":0,"healthy":0,"silenced":0,"total":0,"unknown":0,"warning":0},"clients":{"critical":0,"healthy":0,"silenced":0,"total":0,"unknown":0,"warning":0},"datacenters":{"critical":0,"healthy":0,"silenced":0,"total":0,"unknown":0,"warning":0},"events":{"critical":360,"healthy":0,"silenced":0,"total":0,"unknown":0,"warning":0},"stashes":{"critical":0,"healthy":0,"silenced":0,"total":0,"unknown":0,"warning":0}}
```

```
fess@otfess-alt-8-1177% curl -v  http://127.0.0.1:3000/metrics?token=vFzX6rFDAn3G9ieuZ4ZhN-XrfdRow4Hd5CXXOUZ5NsTw4h3k3l4jAw__               
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
> GET /metrics?token=vFzX6rFDAn3G9ieuZ4ZhN-XrfdRow4Hd5CXXOUZ5NsTw4h3k3l4jAw__ HTTP/1.1
> Host: 127.0.0.1:3000
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Sat, 13 Aug 2016 04:55:24 GMT
< Content-Length: 527
< Content-Type: text/plain; charset=utf-8
< 
{"aggregates":{"critical":0,"healthy":0,"silenced":0,"total":0,"unknown":0,"warning":0},"checks":{"critical":0,"healthy":0,"silenced":0,"total":0,"unknown":0,"warning":0},"clients":{"critical":0,"healthy":0,"silenced":0,"total":0,"unknown":0,"warning":0},"datacenters":{"critical":0,"healthy":0,"silenced":0,"total":0,"unknown":0,"warning":0},"events":{"critical":360,"healthy":0,"silenced":0,"total":0,"unknown":0,"warning":0},"stashes":{"critical":0,"healthy":0,"silenced":0,"total":0,"unknown":0,"warning":0}}
```

hope that helps.

**Comment by UnitedMarsupials** [comment]
Now, this is pretty helpful indeed. I wonder, what is the significance of the actual _password_ in this scheme, however -- and why is this better than the actual Basic Auth... But now I can almost, where I want to be.

Except, when an alert is "stashed" in this manner, the stash is then listed as anonymous:
```json
{
 "_id":"som-sensu01/silence/som-sensu01",
 "content":{
  "reason":"",
  "source":"uchiwa",
  "timestamp":1.471097236e+09,
  "username":""
 },
 "dc":"som-sensu01",
 "expire":459,
 "path":"silence/som-sensu01"
}
```
Somehow Uchiwa does not translate the supplied token into username, when recording the stash-request... Or have I hit a bug and Uchiwa-created stashes _always_ list username as empty?

**Comment by palourde** [comment]
@UnitedMarsupials Indeed, the username is currently provided within the payload supplied by the frontend but as per https://github.com/sensu/uchiwa/issues/542, it does make sense to use information in the JWT if no username was provided.

The password attribute within a user object represents the password a human would use to authenticate itself through the web interface. It can be ignored if you plan to only use this user through the API with an accessToken.

Basic HTTP authentication was voluntary dropped in order to simplify the codebase but I would gladly accept any clean and simple implementation in conjunction with JWT.

I will go ahead and close this issue since we seem to have specific issues to address the multiple concerns raised here but do not hesitate to let me know if there's anything else.

**Comment by UnitedMarsupials** [comment]
> The password attribute within a user object represents the password a human would use

But it is not any different from the password. Somebody knowing either of the two strings can access the system... Maybe, if the token was automatically regenerating from some cryptographic algorithm -- but it is not.

> the username is currently provided within the payload supplied by the frontend but as per #542

In that case, this is a big security problem. Because, being up to no good, I can easily silence an alarm by providing _somebody else's name_... Both the authenticated username and the IP-address, where the request came from should be stored...

There is no point in placing the username in the payload at all.

> Basic HTTP authentication was voluntary dropped

Sorry, but I remain of the opinion, that any web-application using authentication and authorization must support Basic Auth. Other mechanisms can be used _in addition_.

**Comment by palourde** [comment]
> But it is not any different from the password. Somebody knowing either of the two strings can access the system

This is why I would recommend only setting one of them, depending on whether the user is a human or a computer.

> In that case, this is a big security problem

You are right, we should only base ourselves on the information provided in the JWT as long with the IP address.

> Sorry, but I remain of the opinion, that any web-application using authentication and authorization must support Basic Auth. Other mechanisms can be used in addition.

I respect your opinion and I will gladly accept any PR with a clean and simple implementation but considered the limited amount of time I can dedicate to this project, I believe the current authentication system, while it may not be perfect, responds to the needs of the vast majority of the users.
