### ISSUE TITLE
Uchiwa does not record usernames even when available

### ISSUE THREAD

**Issue by UnitedMarsupials** [sensu/uchiwa#542]
When access to Uchiwa is protected by an authentication scheme, Uchiwa ought to make use of it and record the username of the user who stashes an alarm or deletes a result-check.

Instead, the JSON coming from the client is stored verbatim. This is the `CreateStash`-function from Uchiwa-0.17.0:
```go
func (s *Sensu) CreateStash(payload interface{}) (map[string]interface{}, error) {
	payloadstr, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("Stash parsing error: %q returned: %v", err, err)
	}
	return s.postPayload(fmt.Sprintf("stashes"), string(payloadstr[:]))
}
```
The function should check, whether authentication is used and, if so, populate the `username` part of the stash-request for posterity. It may also attempt to catch tricksters and report, when the payload itself already contains username _not matching_ the authenticated credentials.

**Comment by UnitedMarsupials** [comment]
Please, consider also storing the requesting IP-address -- either the actual one or the contents of the `X-Forwarded-For`-header, in case Uchiwa's GUI is accessed through a proxy.

**Comment by josephholsten** [comment]
looks like the new silence mechanism is designed to support this: https://github.com/sensu/sensu/blob/master/lib/sensu/api/routes/silenced.rb#L52

**Comment by josephholsten** [comment]
to whomever may so implement: #547 probably requires very similar work

**Comment by palourde** [comment]
Uchiwa 0.18 now uses the username available in the JWT with the new silenced entries: https://github.com/sensu/uchiwa/blob/0.18.2/uchiwa/server.go#L898

However, it's now impossible to store additional metadata in a silenced entry so we can add the IP address or any other information.

**Comment by UnitedMarsupials** [comment]
I may be misreading the diff, but it _seems_ to me the username is taken simply from the incoming JSON, rather than the actual authentication layer. Please, confirm, that it is not possible to carefully craft a JSON `POST` implicating somebody else in silencing an alarm?

**Comment by palourde** [comment]
@UnitedMarsupials The `token` variable is extracted from the JWT, as you can see here: https://github.com/sensu/uchiwa/blob/0.18.2/uchiwa/server.go#L844. So no, it's not possible to alter this token and therefore, alter the username!

**Comment by UnitedMarsupials** [comment]
> The token variable is extracted from the JWT

I'm not sure, this will work in our case -- we do not rely on Uchiwa's client-side JavaScript to handle authentication, using the trick I describe in #295 instead. Apache-proxy, which performs the authentication, then inserts the `Authorization`-header with the value `Token .....` into it.

I'll have to test with the latest Uchiwa-version...

**Comment by palourde** [comment]
In this case, it will indeed not work since we rely on JWT provided with Uchiwa built-in authentication.

**Comment by UnitedMarsupials** [comment]
So, this feature should be in Uchiwa-0.18.2, which we already run, and, indeed, it is not working in our setup. The "creator" field is empty, when I look at a particular "silenced" tab I just created.

Sad... Frankly, I see no reason to not make the feature work regardless of the authentication scheme. You have the username on the server-side -- from the token specified in the `Authorization`-header. Why not use it?
