### ISSUE TITLE
Datacenter filter in subscriptions

### ISSUE THREAD

**Issue by runningman84** [sensu/uchiwa#546]
We have uchiwa connected to a bunch of different datacenters. If I select a datacenter in the client list, I still see all subscriptions which does not make sense.

The same item count is also wrong because it shows all instead of the amount of clients in the datacenter.

**Comment by palourde** [comment]
The Uchiwa /subscriptions endpoint should support a _dc_ parameter in order to return specific subscriptions for a particular datacenter.
