### ISSUE TITLE
Add requester's username (and IP-address) to check-requests made through Uchiwa

### ISSUE THREAD

**Issue by UnitedMarsupials** [sensu/uchiwa#547]
Uchiwa's interface allows for explicit requests for checks performed outside of the scheduled times through the GUI.

Excessive use of the feature could cause a DOS, but currently there is no way to figure out, _who_ made the request(s).

In the environments, where authentication is already used, the check-requester's username should be added to the request. In _all_ environments the requester's IP-address(es) (either verbatim or from `X-Forwarded-For`) should be added.

The values would then be present in the check-results easing any audits.

**Comment by johntdyer** [comment]
Would also be great if there was a way to pass a username if via header.  This is what we do with Grafana and it's pretty nice.

**Comment by josephholsten** [comment]
to whomever may so implement: #542 probably requires very similar work

**Comment by palourde** [comment]
Unfortunately, it seems that metadata passed to the /request endpoint is not translated to the check results data, therefore making it impossible to audit the requests.

**Comment by UnitedMarsupials** [comment]
So, should a feature-request ticket be opened with Sensu itself to have this capability added?

**Comment by palourde** [comment]
@UnitedMarsupials Yes, I suggest you to do so!

**Comment by UnitedMarsupials** [comment]
Wait, sorry, I don't get it... Right now, a check-description can have any and all arbitrary fields -- we use this trick to, for example, embed links to Graphite-charts. These fields are copied from the check-request JSON into the check-results JSON (with substitutions performed) and all is well.

Why can't Uchiwa-generated requests have some additional fields added similarly?
