### ISSUE TITLE
Documentation should indicate proper format of hashed passwords

### ISSUE THREAD

**Issue by inferiorhumanorgans** [sensu/uchiwa#550]
Per vendor/github.com/kless/osutil/user/crypt/crypt.go 

Hashed passwords need a prefix to indicate their origin, but this is not mentioned anywhere in http://docs.uchiwa.io/en/latest/configuration/uchiwa/

Additionally the suggested commands for hash generation should not be platform specific (ex: use passlib vs mkpasswd). Ex:

```
$ python -c 'from passlib.hash import sha512_crypt; hash = sha512_crypt.encrypt("password"); print hash;'
 $6$rounds=656000$lFXVHUN57B8d7nt4$XYX19FhUUY5uokqp9z8ZnGnyHOzqABt3AotqPvvAcHQEcBHEuJouhnYeMR96QT4SHqHnhMevLHuW5BStuc2iI.
```

```
$ python -c 'from passlib.hash import sha256_crypt; hash = sha256_crypt.encrypt("password"); print hash;'
$5$rounds=535000$3WgZWV976NkHaCHi$t79Ki/vdEaS.zE0m.WJMkGjHLaMGqtiCOqbSsddFk97
```

```
$ python -c 'from passlib.hash import md5_crypt; hash = md5_crypt.encrypt("password"); print hash;'
  $1$0T6IR/dV$JiLOV1KNC/wxB03pFVLFy0
```

Also the examples ought not require place passwords on the command line

**Comment by palourde** [comment]
I believe the documentation already explicitly mentions that you should use the `{crypt}` prefix with encrypted passwords: http://docs.uchiwa.io/en/latest/configuration/uchiwa/#encrypted-passwords.

I didn't used the passlib library in the examples but I'll add a note to mention this alternative.

Thanks

**Comment by palourde** [comment]
It's now documented.
