### ISSUE TITLE
DOCUMENTATION REQUEST - Version of Go needs to be updated from 1.3 to >=1.6

### ISSUE THREAD

**Issue by EZtheOG** [sensu/uchiwa#551]
When I run uchiwa I get this:
```
godep go run uchiwa.go
# github.com/sensu/uchiwa/uchiwa/authorization
/usr/lib/golang/src/github.com/sensu/uchiwa/uchiwa/authorization/authorization.go:34: undefined: http.MethodHead
/usr/lib/golang/src/github.com/sensu/uchiwa/uchiwa/authorization/authorization.go:34: undefined: http.MethodGet
godep: go exit status 2
```

I am running uchiwa `0.17.1`.  I upgraded our sensu - tbh I don't remember which version. 

Not sure where to go from here?

**Comment by Gillingham** [comment]
Looks like https://github.com/sensu/uchiwa/pull/528 may have changed the requirements from go>=1.3 to >= 1.6

**Comment by EZtheOG** [comment]
Yep - that is correct - just kind of figured that out by digging around and IRC.

Documentation still has `Recent version of go (>= 1.3) (guide)`.

**Comment by EZtheOG** [comment]
YEP update GO to 1.6 or higher. CLOSING

**Comment by Gillingham** [comment]
@EZtheOG you should probably keep this open and change it to be a request ot update the documentation to state the correct depdenency
