### ISSUE TITLE
Uchiwa consistently dies if refresh param is less than 5 seconds

### ISSUE THREAD

**Issue by Savemech** [sensu/uchiwa#552]
error log:
==> /var/log/uchiwa.err <==
net/http.HandlerFunc.ServeHTTP(0xc8200c7ba0, 0x7f0c99db8a68, 0xc82011c410, 0xc8200e2e00)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820066ae0, 0x7f0c99db8a68, 0xc82011c410, 0xc8200e2e00)
        /usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc82008e280, 0x7f0c99db8a68, 0xc82011c410, 0xc8200e2e00)
        /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82014cb00)
        /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2137 +0x44e

**Comment by Savemech** [comment]
my bad,
Debian GNU/Linux 8
3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
using this package: uchiwa_0.17.1-1_amd64.deb

**Comment by josephholsten** [comment]
@Savemech did you get this resolved?

**Comment by Savemech** [comment]
@josephholsten sort of, i just did 
crontab:
*  *    * * *   root    systemctl restart uchiwa.service
and this is barely helps, uchiwa still goes unstable some time
i'm thinking of implementation some of keepalived + vip to keep my uchiwa instances up and dont show broken info.
I'm also noticed, when uchiwa about to broke, its some symbols appear in random places like 
```
action create&12
```
idk maybe its chrome bug to render that in way like this, maybe it's uchiwa itself but few minutes later uchiwa just stop responding and dies completely

**Comment by palourde** [comment]
Hi,

I believe this issue could be related and fixed with the 0.18 release: https://github.com/sensu/uchiwa/issues/543

Could you let us know if you still face this problem with the newer versions?

Thanks

**Comment by Savemech** [comment]
Yes of course, i will update my uchiwa installations soon and post some results.
Thank you guys, you're awesome!

**Comment by Savemech** [comment]
Bug seems fixed, with refresh ratio in 1 sec works stable for 2 days in row with 16MB memory footprint with 24 clients and ~50 checks

**Comment by palourde** [comment]
\o/
