### ISSUE TITLE
Use different favicon to reflect the state of affairs

### ISSUE THREAD

**Issue by UnitedMarsupials** [sensu/uchiwa#554]
Uchiwa already uses different colors to reflect the most troubling state of the checks -- looking at the page in the browser even from afar, one can see, that everything is green (or not).

It would be nice, if the favicon also changed depending on the status. This way, one could have the Uchiwa page in a browser _tab_ or a minimized window, for example, and still notice, if the icon changed.

If you choose to implement this feature, please, be sure the different icons are separate (static) files -- to not break caching -- and that the page HTML specifies a different file depending on the actual status.

**Comment by palourde** [comment]
Thank you very much for your suggestion. It seems we already have an issue for this feature request so I'll close this one to avoid any duplication. Any progress will be posted in https://github.com/sensu/uchiwa/issues/227.
