### ISSUE TITLE
Check detail issue when command is using a url with an image

### ISSUE THREAD

**Issue by luisdalves** [sensu/uchiwa#558]
Hello,

I think I found an issue in uchiwa's UI. I'm using check_http to check a web service, this check is getting a blank pixel.
`check-http.rb -u http://localhost/pixel.gif -H "Host: example.com"`

When uchiwa render the client/check, the section in the checks is broken because is trying to get localhost/pixel.gif

![check_detail](https://cloud.githubusercontent.com/assets/11091389/18364897/9f1d253e-75e6-11e6-884b-b02a13a5695f.png)

Regards

Uchiwa Version: 0.17.1

**Comment by josephholsten** [comment]
seems like the fix would be to XML escape the command before rendering
