### ISSUE TITLE
HTTP Basic auth no longer works alongside Uchiwa

### ISSUE THREAD

**Issue by smuth4** [sensu/uchiwa#559]
It looks as though something is overwriting the Authentication header on some requests (.e.g. `/uchiwa/config`) but not others, so I while I can authenticate against both uchiwa and basic auth successfully, it doesn't let me past the login page.

**Comment by palourde** [comment]
Hi,

Thank you for reporting this issue. In order to help us troubleshoot this problem, could you provide us some examples of the requests made against the Uchiwa API?

Thanks

**Comment by smuth4** [comment]
Sure, here are two requests that happen in sequence after entering the uchiwa login credentials:

The actual login passes in the cached `Authorization: Basic` token correctly and succeeds.
```
POST /uchiwa/login HTTP/1.1
Host: example.com
User-Agent: <redacted>
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/json;charset=utf-8
Referer: https://example.com/uchiwa/
Content-Length: 31
Cookie: uchiwa_theme=uchiwa-default; <redacted>
Authorization: Basic <redacted>
Connection: keep-alive

HTTP/1.1 200 OK
Server: nginx
Date: Tue, 13 Sep 2016 16:55:04 GMT
Content-Type: application/json
Content-Length: 988
Connection: keep-alive
```
The next call replaces the  `Authorization` header with a `Bearer` token, so nginx rejects it.
```
GET /uchiwa/config HTTP/1.1
Host: example.com
User-Agent: <redacted>
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer <redacted>
Referer: https://example.com/uchiwa/
Cookie: uchiwa_theme=uchiwa-default; <redacted>
Connection: keep-alive

HTTP/1.1 401 Unauthorized
Server: nginx
Date: Tue, 13 Sep 2016 16:55:04 GMT
Content-Type: text/html
Content-Length: 188
Connection: keep-alive
WWW-Authenticate: Basic realm="Restricted"
```
The call after that to `uchiwa/bower_components/uchiwa-web/partials/views/events.html` also fails in the exact same way.

**Comment by palourde** [comment]
It looks like you are using both HTTP basic authentication and Uchiwa's built-in authentication? If so, I can simply recommend you to disable one of them since Uchiwa needs to use the `Authorization` header with a `Bearer` token as you noticed. 

Unfortunately I don't think supporting both authentication mechanisms at the same time is something we should consider nor recommend.
