### ISSUE TITLE
uchiwa 0.18.1 does not work with sensu <= 0.26

### ISSUE THREAD

**Issue by cabecada** [sensu/uchiwa#563]
the new uchiwa 0.18.1 has inbuilt silencing support for sensu, which is not yet present in sensu < 0.26 versions.

the uchiwa.err is empty and uchiwa.log simply tries to connect to /silenced which does not exists in sensu-api.
the same config below works for uchiwa 0.17.1 though.
i guess it is because it expects to get all /silenced results. but as the sensu api < 0.26 does not support /silenced, it fails and hence it does not get any data for the datacenter.

https://github.com/sensu/uchiwa/blob/12ac27f20c422e7252f56a5c12e4d381bd02c57c/uchiwa/daemon/daemon.go#L89

![image](https://cloud.githubusercontent.com/assets/20220560/18413585/70c6eaf0-77c9-11e6-87a3-f868c165cc7c.png)
![image](https://cloud.githubusercontent.com/assets/20220560/18413588/85302650-77c9-11e6-9e15-1e21caa1400f.png)
![image](https://cloud.githubusercontent.com/assets/20220560/18413592/91bbd75c-77c9-11e6-8ab4-dc7d70a37c93.png)
![image](https://cloud.githubusercontent.com/assets/20220560/18413599/b7b3fd4a-77c9-11e6-9818-f0b3f3be7568.png)
![image](https://cloud.githubusercontent.com/assets/20220560/18413638/1e7ab194-77cb-11e6-925c-6d0954d42bdb.png)

```shell
root@sensu-server:/etc/sensu# cat config.json
{
  "rabbitmq": {
    "host": "localhost",
    "port": 5672,
    "user": "sensu",
    "password": "sensu",
    "vhost": "/sensu"
  },
  "redis": {
    "host": "localhost",
    "port": 6379
  },
  "api": {
    "host": "localhost",
    "port": 4567
  },
  "handlers": {
    "logevent": {
      "type": "pipe",
      "command": "handler-logevent.rb"
    },
    "default": {
      "type": "set",
      "handlers": [
        "logevent"
      ]
    },
    "stdout": {
      "type": "pipe",
      "command": "cat"
    }
  },
  "logevent": {
    "eventdir": "/tmp/sensuevents",
    "keep": 10
  },
  "checks": {
    "test": {
      "command": "ls /tmp/vjain",
      "subscribers": [
        "test"
      ],
      "interval": 60
    }
  },
  "client": {
    "name": "localhost",
    "address": "127.0.0.1",
    "subscriptions": [
      "test"
    ]
  }
}
root@sensu-server:/etc/sensu# cat uchiwa.json 
{
  "sensu": [
    {
      "name": "localhost",
      "host": "127.0.0.1",
      "port": 4567,
      "timeout": 10
    }
  ],
  "uchiwa": {
    "host": "0.0.0.0",
    "port": 3000,
    "refresh": 10,
    "loglevel": "debug"
  }
}
```

**Comment by amdprophet** [comment]
Hi @cabecada,

This is intentional and is noted in the change log (https://github.com/sensu/uchiwa/blob/master/CHANGELOG.md). You will need to upgrade your Sensu version or revert back to Uchiwa 0.17.1 to resolve the issue.

**Comment by cabecada** [comment]
Thanks for the confirmation Justin.

I got confused as doc mentioned <= 0.26 which meant all versions until 0.26 :)
Should that be changed as  sensu >= 0.26 ?


Thanks
Vijay

Sent from my iPhone

On 11-Sep-2016, at 3:37 AM, Justin Kolberg <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @cabecada<https://github.com/cabecada>,

This is intentional and is noted in the change log (https://github.com/sensu/uchiwa/blob/master/CHANGELOG.md). You will need to upgrade your Sensu version or revert back to Uchiwa 0.17.1 to resolve the issue.

-

**Comment by amdprophet** [comment]
@cabecada Ah yes, that's a typo. Good catch! I'll get that fixed.
