### ISSUE TITLE
Filtering by silenced clients/checks on the events page hides all clients/checks

### ISSUE THREAD

**Issue by GuitarrasDeAmor** [sensu/uchiwa#565]
Uchiwa 0.18.1
Sensu 0.26.1

Steps to reproduce:

1. Silence a client and/or a check.
2. Have that client and/or check produce an event to show up on the events page.
3. Have a non silent client produce an event to show up on the events page.
4. Click the hide dropdown and select "Silenced Checks" or "Silenced Clients"
5. See all hosts/checks disappear even if they are not silenced.

**Comment by josephholsten** [comment]
I do wonder how #568 affects this.

**Comment by RyanJarv** [comment]
Still seeing this bug (or similar one at least) on 0.18.2. Silencing checks with Hide Silenced selected does not hide them on the event page while check page shows them as silenced. Silencing a host works as expected.

**Comment by sfrostick** [comment]
Still seeing this on 0.18.2. All the clients and sensu server are running 0.26.3-1. If i click hide silenced checks every client disappears.

**Comment by GuitarrasDeAmor** [comment]
@sfrostick I am on the same versions and am not seeing the problem. I am able to hide silenced checks as well as clients.

I have noticed with Chrome + Uchiwa that my caching sometimes gets funky and shows weird behavior, and clearing that helps.

**Comment by sfrostick** [comment]
Had done an in place upgrade from 0.24 sensu and 0.15 uchiwa and restarted all the services and still had the issue even on a different browser. In the end i just ended up restarting the whole server and the issue is now resolved.
