### ISSUE TITLE
check.silenced in /events does not match /clients/{client}/history

### ISSUE THREAD

**Issue by josephholsten** [sensu/uchiwa#567]
originally noticed in #566

### Summary
Some checks on the `/#/events` page are not showing as silenced even when they are on the `/#/client/sensu/{client}` page. This happens only for clients running an old version of `sensu-client`.

### Notes
`sensu-api` output for `/clients/{client}/history` doesn't include a silenced key, I only see it from the uchiwa response.

For the uchiwa `/clients/{client}/history` response, the `silenced` key is added by [uchiwa/client.go: *Uchiwa.buildClientHistory()](https://github.com/sensu/uchiwa/blob/master/uchiwa/client.go#L27)

### Possible solutions

- create a similar `buildEvents` like `buildClientHistory` that adds the correct `silenced` key

**Comment by josephholsten** [comment]
this should probably have an upstream ticket, because [Sensu::API::Routes::Events.get_events](https://github.com/sensu/sensu/blob/master/lib/sensu/api/routes/events.rb#L14) should really be returning `silenced` for these checks, not just ignoring the key if it's missing from redis.

**Comment by josephholsten** [comment]
oh, it is returning silenced in every event, but it doesn't match that from `buildClientHistory`

**Comment by josephholsten** [comment]
ah, I see the problem. [*Daemon.buildEvents()](https://github.com/sensu/uchiwa/blob/master/uchiwa/daemon/events.go) only sets `.client.silenced` from `helpers.IsClientSilenced()`, but does not set `.silenced` & `.silenced_by` from `helpers.IsCheckSilenced()`.

**Comment by palourde** [comment]
Hi,

Thank you for opening this issue. Could you please let us know which version of Uchiwa you are using? Please note that Uchiwa 0.18.x requires Sensu <= 0.26.0.

Starting from 0.26, the Sensu API /events endpoint will provide the `silenced` and `silenced_by` attributes, which explains why the `*Daemon.buildEvents()` method does not add these attributes.

Thanks

**Comment by josephholsten** [comment]
I'm using uchiwa 0.18.1, and sensu-api 0.26.1. I also have clients which are stuck using an older sensu-client, and the incorrect `.silenced` values come from them.

The main goal of this patch is to make the events page match the client & check pages. It's very confusing to have them be different, and allows you to "silence" the checks in the ui, which clearly makes no sense.

**Comment by palourde** [comment]
@josephholsten I was able to reproduce this issue by using a client with a pre-0.26 Sensu version. When silencing an event of this client, it looks like the Sensu API does not return the proper `silenced` value.

@portertech Is it an expected behaviour?

**Comment by palourde** [comment]
@josephholsten According to [this recent commit](https://github.com/sensu/sensu-docs/blob/709bd941de462619a1748fdd767c8fc15bc0ea0a/docs/0.26/reference/silencing.md#migrating-from-stash-based-silencing) pushed to the sensu documentation, this behaviour is expected and therefore, you should upgrade all your Sensu clients to 0.26 or downgrade Sensu server and Uchiwa.

I do not wish to add backward compatibility in Uchiwa for this specific case since it would only be a cosmetic change and the event would still not be silenced in Sensu.

Thanks

**Comment by josephholsten** [comment]
Great! It's no fun deciding to remove backward compatibility later. So long as it's doc'd, I'm cool with it.
