### ISSUE TITLE
An old failure never ends

### ISSUE THREAD

**Issue by UnitedMarsupials** [sensu/uchiwa#576]
Due to a local misconfiguration, the simple check performed by the sensu-plugins-mailq was failing -- the Sendmail's `mailq` could not run.

Unfortunately, even after the misconfiguration was rectified, Uchiwa _continues_ to claim that a) there is a problem with the check; b) the problem is _current_:

![uchiwa-mailq-check](https://cloud.githubusercontent.com/assets/1486340/18934760/a038fa10-85a9-11e6-80dd-8830c35d378f.png)

According to the host's `sensu-client.log` the check-results were `OK` for two days already, but Uchiwa continues to claim failure. The only way to get rid of it is to explicitly clear the check through Uchiwa's dashboard.

Maybe, this is deliberate and each failure needs to be explicitly accounted for. But then:

- The clearing should prompt the user for reasons/details and record them with the user-ID (where authentication is used) -- same as with stashing
- The check-results can not be presented as _current_

**Comment by palourde** [comment]
Thanks for reporting this issue.

Were you able to confirm if this event was still present in the Sensu API or only in Uchiwa?

Thanks

**Comment by UnitedMarsupials** [comment]
I wish, I know, how to check with the API... Is there a command-line tool of some sort, for example?

Meanwhile, the problem seems gone for now. Not sure, what cleared it -- but I've restarted Sensu-servers after upgrading to 0.26.4...

**Comment by palourde** [comment]
I'm aware of the [sensu-cli](https://github.com/agent462/sensu-cli) project, otherwise you could simply use curl:

```
curl http://SENSU_API:4567/events
```

And if you have authentication enabled on your Sensu API, simply add the `-u myusername:mypassword` argument.

Please do not hesitate to re-open an issue if you are able to reproduce this problem so we can investigate further.
