### ISSUE TITLE
Feature Request: uchiwa over ipv6

### ISSUE THREAD

**Issue by x70b1** [sensu/uchiwa#587]
I would like to use uchiwa with an IPv6 address. At the moment I can't set something in my config file. If I set an v6 address at the "host" part I got an error in my logfile: 

> listen tcp: too many colons in address 

This means we can use uchiwa with IPv4 only. 
An option for dual stack environments would be awesome. So we could reach uchiwa in every case.

**Comment by palourde** [comment]
Hi,

Uchiwa does support IPv6 addresses. For example, in your `config.json` file:

```
[...]
"uchiwa": {
  "host": "[::1]"
}
```

And then, we can browse the URL http://[::1]:3000/#/events. I'll push some documentation about it.
