### ISSUE TITLE
Uchiwa 0.19 Silenced dont work

### ISSUE THREAD

**Issue by alexwbaule** [sensu/uchiwa#588]
Using Sensu 0.26 and Uchiwa 0.19, the new Silenced dont work correctly.

Using this feature, i note 3 errors:

1 - The silenced list don´t show more than 1 silenced item, even if i have more itens, and the Sensu API return all silences.

2 - Clear the Silence, the text (id, creator, datacenter, etc) is blank. The modal shows only the checkbox.

3 - If you try to remove the Silence, click in the checkbox and submit, a javascript error occurs.

> angular.js:12808TypeError: Cannot read property '_id' of null
>     at controllers.js?rel=1476657523783:757
>     at Object.p [as forEach](angular.js:341)
>     at n.$scope.ok (controllers.js?rel=1476657523783:756)
>     at fn (eval at compile (angular.min.js?rel=1476657523783:1), <anonymous>:4:197)
>     at b (angular.js:14635)
>     at e (angular.js:24103)
>     at n.$eval (angular.js:16384)
>     at n.$apply (angular.js:16484)
>     at HTMLButtonElement.<anonymous> (angular.js:24108)
>     at Pf (angular.js:3384)(anonymous function) @ angular.js:12808

**Comment by alexwbaule** [comment]
In the Silenced List, when you click in the X , another javascript Error:

> angular.js:12808 TypeError: Cannot read property 'indexOf' of undefined
    at Object.getResources (services.js?rel=1476657523783:14)
    at Object.delete (services.js?rel=1476657523783:366)
    at b.$scope.deleteSilenced (controllers.js?rel=1476657523783:647)
    at fn (eval at compile (angular.js:13653), <anonymous>:4:502)
    at b (angular.js:14635)
    at e (angular.js:24103)
    at b.$eval (angular.js:16384)
    at b.$apply (angular.js:16484)
    at HTMLElement.<anonymous> (angular.js:24108)
    at Pf (angular.js:3384)(anonymous function) @ angular.js:12808(anonymous function) @ angular.js:9555$apply @ angular.js:16489(anonymous function) @ angular.js:24108Pf @ angular.js:3384d @ angular.js:3372

**Comment by palourde** [comment]
Hi Alex,

I was unfortunately unable to reproduce this issue. In order to assist you with the investigation, could you provide us the output produced by the Uchiwa API for the silenced entries, e.g.: `http://127.0.0.1:3000/silenced`?

I would also recommend you to try to restart Uchiwa and clear your web browser cache.

Thanks

**Comment by alexwbaule** [comment]
Yeap !

This is the output:

[{"check":null,"creator":"alex.baule","dc":"Sensu","expire":804,"expire_on_resolve":false,"id":"client:appsaasfluig-03:*","reason":"TESTE","subscription":"client:appsaasfluig-03"}]

This is a silence to a client

**Comment by alexwbaule** [comment]
you need that i do something else? Some procedure or log ?

**Comment by palourde** [comment]
@alexwbaule I assume you built by yourself the Uchiwa binary? If so, please make to include the https://github.com/sensu/uchiwa/commit/f9e1c5ca7fd68cb727ad4e021e14e2d56bc19ba1 commit. It seems you used a commit between the 0.19.0 release and this last commit, which is not fully tested.

Let me know if it resolves your issue.

Thanks

**Comment by alexwbaule** [comment]
yeap, i build... 

Ok, doing a pull, get this and now its working.

Tks @palourde  !
