### ISSUE TITLE
Checks page does not list any checks

### ISSUE THREAD

**Issue by thisisjaid** [sensu/uchiwa#591]
This is our current checks configuration from /etc/sensu/conf.d/checks.json

`{
  "checks": {

    "rabbit_is_ok": {
      "command": "check-rabbitmq-node-health.rb -P 55672",
      "subscribers": [
        "monitor_v2",
				"monitor_portal"
      ],
      "interval": 60
    },

		
		"redis_6379_is_ok": {
			"command": "check-redis-ping.rb",
			"subscribers": [
				"monitor_portal"
			],
			"interval": 60
		},

    "redis_6380_is_ok": {
      "command": "check-redis-ping.rb -p 6380",
      "subscribers": [
        "monitor_portal"
      ],
      "interval": 60
    },

    "mysql_is_ok": {
      "command": "check-mysql-alive.rb -s :::mysql_socket|/var/lib/mysql/mysql.sock:::",
      "subscribers": [
				"monitor_v2",
        "monitor_portal"
      ],
      "interval": 60
    }

  }
}
`
Uchiwa however consistently shows 0 checks and lists no checks on the Checks page. Would appreciate if anyone could give us a hint as to why this might be occurring? I have read the docs saying that standalone checks would not show up but these are definitely defined on the master.

**Comment by rodriguesalex** [comment]
Make sure you restart the sensu-server/server-api services after adding those checks

**Comment by thisisjaid** [comment]
Ah that was it, we'd restarted sensu-server but sensu-api also needed a restart. Much appreciated @rodriguesalex !
