### ISSUE TITLE
Latest docker image broken

### ISSUE THREAD

**Issue by Gillingham** [sensu/uchiwa#593]
Using the latest official image:
```
latest: Pulling from uchiwa/uchiwa
Digest: sha256:6aa46bdf0ac5edc536947f7b430792745035e80f836de912f02204c02dc76419
Status: Image is up to date for uchiwa/uchiwa:latest
```

It seems to have references to `bower_components/uchiwa-web/js/common.js` and
`bower_components/angular-resource/angular-resource.min.js`both of which 404 and prevent uchiwa from actually loading the web interface at all.

I have confirmed these files don't exist in the docker images:
```
$ sudo docker run -ti --rm uchiwa/uchiwa:latest ls /go/src/github.com/sensu/uchiwa/public/bower_components/angular-resource/angular-resource.min.js
ls: /go/src/github.com/sensu/uchiwa/public/bower_components/angular-resource/angular-resource.min.js: No such file or directory
$ sudo docker run -ti --rm uchiwa/uchiwa:latest ls /go/src/github.com/sensu/uchiwa/public/bower_components/uchiwa-web/js/common.js
ls: /go/src/github.com/sensu/uchiwa/public/bower_components/uchiwa-web/js/common.js: No such file or directory
```

**Comment by palourde** [comment]
Hi,

It seems the Docker Hub was still building images upon every commit. We just adjusted the settings so the image generation is only triggered by a tag pushed to Github.

I also moved the *latest* tag so it points to *0.19.0*. However, I would still recommend to avoid the use of the *latest* tag.

Thanks
