### ISSUE TITLE
requested URL /silenced was not found on this server

### ISSUE THREAD

**Issue by cixelsyd** [sensu/uchiwa#600]
Hello.  I run uchiwa behind an apache reverse proxy server, and it appears that the new silence feature looks for an absolute, rather than a relative URL.  See error attached.
<img width="300" alt="screen shot 2016-11-21 at 12 49 04 pm" src="https://cloud.githubusercontent.com/assets/654692/20493998/ff2a2968-afe8-11e6-9965-6ae9c301f487.png">

**Comment by johnseekins** [comment]
Similarly, the "info" page (<host>/#/info) tries to reach a /config endpoint without honoring any headers, so this also breaks.

**Comment by johnseekins** [comment]
The /results endpoint also doesn't honor a reverse proxy setup.

**Comment by cixelsyd** [comment]
Rock on!  Thank you!

steve


mobile

**Comment by johnseekins** [comment]
That was so fast!
