### ISSUE TITLE
popover info of the clients button in uchiwa is empty

### ISSUE THREAD

**Issue by x70b1** [sensu/uchiwa#607]
In uchiwa 0.20.2 the popover info of the clients button in uchiwa is empty if everything is ok. 
If there are clients with a warning or critical state the popover works and shows an value.

![image](https://cloud.githubusercontent.com/assets/10016267/20646858/b5617552-b484-11e6-8c3f-aaf330f65728.png)

**Comment by palourde** [comment]
Hi,

Thanks for reporting this issue! Does it only happen for the clients or also for other objects?

**Comment by x70b1** [comment]
Hi palourde

I dont get it only at the clients button. The other buttons are working.

**Comment by x70b1** [comment]
It should be fixed with the last update.
And yes, it works a bit more. But there still seems to be a problem.

![image](https://cloud.githubusercontent.com/assets/10016267/21083160/b6815418-bfea-11e6-9e79-89f28aa8dfcc.png)
