### ISSUE TITLE
Uchiwa 0.20.2 showing an alert with no details

### ISSUE THREAD

**Issue by CVTJNII** [sensu/uchiwa#609]
Uchiwa 0.20.2 connecting to Sensu 0.26.5 on Firefox 43 & 45 is showing one alert on the sidebar alert triangle.  However, mouseover shows no data, and clicking on the icon does not navigate away from the current page.

![phantomalert](https://cloud.githubusercontent.com/assets/13871930/20814569/3ba3a4e4-b7e8-11e6-8948-9328403189a0.png)

## Expected Behavior
Uchiwa should reveal what that red 1 is all about

## Your Environment
* Uchiwa version used: 0.20.2
* Sensu version used: 0.26.5
* Operating System and version (e.g. Ubuntu 14.04): uchiwa/uchiwa Docker container

**Comment by palourde** [comment]
Thanks for reporting this issue. Could you let us know if you have anything showing up in your browser console? Thanks!

**Comment by CVTJNII** [comment]
No, I don't see anything in the console.

**Comment by cwjohnston** [comment]
@CVTJNII is this issue ongoing for you with the latest uchiwa? Can you provide any additional detail?

**Comment by CVTJNII** [comment]
I'll have to test, but due to time constraints I'm not sure when I'll be able to.

**Comment by palourde** [comment]
I'm closing this issue since we didn't received any updates.

If you are still facing this problem, please let us know with a comment and we'll be happy to reopen the issue.

Thanks!
