### ISSUE TITLE
Uchiwa responsive design

### ISSUE THREAD

**Issue by portertech** [sensu/uchiwa#616]
- [x] Rebase using the previous prototype
- [x] Adapt the sidebar popovers
- [x] Adapt the modal windows
- [x] Text trimming if required on mobile 
- [x] Apply to all views

**Comment by palourde** [comment]
Prototype:
![img_1637](https://cloud.githubusercontent.com/assets/4105580/21330953/0f94270a-c60e-11e6-9a64-ba914befbcb9.PNG)
![img_1638](https://cloud.githubusercontent.com/assets/4105580/21330954/0f9e6d0a-c60e-11e6-8443-14ce3662c705.PNG)
![img_1639](https://cloud.githubusercontent.com/assets/4105580/21330952/0f936d06-c60e-11e6-94bd-a98e35d88bd9.PNG)
