### ISSUE TITLE
Reflected XSS in logger's print function 

### ISSUE THREAD

**Issue by willdeed** [sensu/uchiwa#618]
A reflected XSS may exist due to the logger function not escaping HTML before potentially being displayed in the browser. Although the `Content-Type` is set to `text/plain`, some browsers may render as HTML if HTML is detected. 

For instance, [https://msdn.microsoft.com/en-us/library/gg622940(v=vs.85).aspx](url) mentions the following:
"If Windows Internet Explorer 9 encounters an HTML document delivered with a "text/plain" content-type, the document will be rendered as plain text **unless the site is rendering in Compatibility View.** "

## Expected Behavior

Content that could be displayed in a browser and interpreted as HTML has proper HTML escaping.

## Current Behavior

HTML is not escaped in error messages

## Possible Solution

Use `html.EscapeString()` in the `logger.print()` function

## Steps to Reproduce (for bugs)

1. Browse to `/uchiwa/aggregates/<img%20src%3d'vbscript%3aMsgBox%28"XSS"%29'>` in a browser that renders HTML on detection

Alternatively,

2. Browse to `/uchiwa/clients/<img%20src%3d'vbscript%3aMsgBox%28"XSS"%29'>` in a browser that renders HTML on detection

## Context

The instances listed in steps to reproduce above are detected as Reflected XSS in Fortify as a Critical issue

## Your Environment

* Uchiwa version used: 0.20.0-1
* Sensu version used: 0.26.5-2
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 14.04.1

**Comment by palourde** [comment]
Fixed by https://github.com/sensu/uchiwa/issues/620
