### ISSUE TITLE
uchiwa-web key: value search does not work

### ISSUE THREAD

**Issue by cabecada** [sensu/uchiwa#624]
as per
https://github.com/palourde/uchiwa-docs/pull/12/files
and 
https://github.com/sensu/uchiwa-web/pull/122

i expected key: value search in events to looks for events

![image](https://cloud.githubusercontent.com/assets/20220560/21768431/b06e7576-d69f-11e6-8e3e-d04c83d8a7f6.png)

i should be able search with key value pair (eg check name = mon_check)

![image](https://cloud.githubusercontent.com/assets/20220560/21768467/da907ec6-d69f-11e6-87b1-522f8388ab0c.png)

but i am not able to search

![image](https://cloud.githubusercontent.com/assets/20220560/21768482/e75f14b4-d69f-11e6-8bf0-a94e37bbaf06.png)

![image](https://cloud.githubusercontent.com/assets/20220560/21768489/f29a8944-d69f-11e6-9b43-a02172635878.png)

whereas regex based search work

![image](https://cloud.githubusercontent.com/assets/20220560/21768506/ffaa7de2-d69f-11e6-9e7c-a1aa3826e446.png)

am i missing something here?

* Uchiwa version used: 0.21
* Sensu version used: 0.26.5
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by palourde** [comment]
Hi @cabecada 

Thanks for reporting this issue. It looks like recursive search while using key/value isn't working properly. I'll look into it!
