### ISSUE TITLE
Bulk resolving removed?

### ISSUE THREAD

**Issue by joshgarnett** [sensu/uchiwa#628]
I just upgraded from Uchiwa 0.17 to 0.22 and noticed that I can no longer bulk resolve issues.  I was curious if this was by design or if there is another way to re-enable this functionality?  Thanks!

**Comment by palourde** [comment]
Hi @joshgarnett,

Thank you for reporting this issue. It has just been fixed through https://github.com/sensu/uchiwa-web/pull/138, we will release a new version ASAP.

Thanks
