### ISSUE TITLE
alt text for complex custom urls

### ISSUE THREAD

**Issue by exeral** [sensu/uchiwa#629]
On uchiwa-web

shortly: alt text for long ugly URLs in custom attributes

My goal is to provides on each check details page ( /#/client/sensu/hostname?check=checkname )
a field to create a JIRA issue corresponding to the alert

currently I have a custom attribute:

jira : https://jira.example.org/secure/CreateIssueDetails!init.jspa?pid=11000&issuetype=56&duedate=30/01/2017&customfield_15103=16405&customfield_15104=16411&customfield_11201=11113&customfield_11201:1=11144&customfield_12710=18100&components=11103&summary=[sensu]+alert+-+check+TRUC&description=Sensu%20Alert%20!%0AOn%3A%20webservices%20servers%0A%0ACritical%20%3A%20*Check%20TRUC*

I would like to have

jira : "Click here to create ticket"   =>   that points to the URL above

1 solution that need some code logic:
if the custom attributes is an array and have a field url and a field alt_text
  display the alt_text and point to the url

another workaround
if the custom attribute looks like url and is longer than  X characters
   shorten the displayed text "https://jira.example.org/secure/CreateIssueDetails!init.jspa?__...__"

another question:
How to include the check result content in the URL ? so the ticket would be auto created with check status.
This would need to generate the URL on the fly

What do you think ?
thanks

**Comment by Evesy** [comment]
+1

Would be nice to have some logic from Uchiwa to shorten the displayed texts on URL's

**Comment by jothoma1** [comment]
:+1: 

We are interested too in this feature
