### ISSUE TITLE
silence interface should default to no expiration with expire on resolve

### ISSUE THREAD

**Issue by fessyfoo** [sensu/uchiwa#631]
## Current Behavior

currently the uchiwa interface for silence defaults to no expire on resolve, and 15 minute expiry.

![image](https://cloud.githubusercontent.com/assets/1090063/22599463/eb21478e-e9eb-11e6-9e21-a4ee981d0a49.png)

### preferred
IMO it should have a single expire on resolve button, and default to it. eliminating the expire on resolve checkbox but implying no expiry date + expire on resolve. the remaining buttons would imply no expire on resolve. 

![image](https://cloud.githubusercontent.com/assets/1090063/22599482/f8ce0336-e9eb-11e6-9584-224b7b565870.png)

### alternate
an alternative quick solution might just be to change the default on the existing interface. this would work as well, but I don't see the need to use both an expiry date  and expire on resolve at the same time.  so i think the above solution is less confusing. 

![image](https://cloud.githubusercontent.com/assets/1090063/22599816/f7915c2e-e9ec-11e6-9990-cbdc64fb156c.png)

In either case I think it's best to default to expire on resolve.  

## context 

We provide sensu to a lot of different engineering teams,  basically a lot of customers who have rare interaction with the system.  so first impression on silence is important. our users have experienced confusion when they don't notice a 15 minute expiry and the alerts re fire.  Others experience more confusion when the check has gone green then red again some time in the future but the check is still silenced because they clicked no expiration the first time they silenced it but they expected that when the check was green the science would clear. 

## system info

current behavior observed in uchiwa `0.22.0`

**Comment by fessyfoo** [comment]
submitted a PR https://github.com/sensu/uchiwa-web/pull/139  updated tests, and manually tested in our env.

**Comment by palourde** [comment]
Good point. Thank you for your PR, it has been merged so I'll close this issue.
