### ISSUE TITLE
Uchiwa doesn't refresh stale checks and doesn't schedule them

### ISSUE THREAD

**Issue by dancb10** [sensu/uchiwa#632]
## Current Behavior
I have some checks that are old and they aren't configured locally on the servers (in the json file). But I still get alerts saying that the checks aren't OK. If i go in Uchiwa in the checks tab, my stale checks do NOT appear there so I'm guessing that it's fetching this false data somewhere from redis?
I have another issue for checks that aren't scheduled automatically. They aren't checked automatically and work only if I schedule them manually from the Uchiwa interface

## Possible Solution
Haven't found a solution yet

## Context
I'm trying to have a live monitoring system. I'm using Ansible so I'm adding and deleting checks frequently. I don't want to have false checks that poisons my dashboard. Plus since some checks need to be manually scheduled it isn't feasible for my setup.

## Your Environment

* Uchiwa version used: uchiwa-0.22.0-1.x86_64
* Sensu version used: sensu-0.26.5-2.x86_64
* Operating System and version (e.g. Ubuntu 14.04): 
Sensu server: CentOS Linux release 7.2.1511 (Core)
Sensu clients: CentOS Linux release 7.2.1511 (Core) and Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Comment by dancb10** [comment]
Here is my config on how checks appear:
    "service_atomic-openshift-node_status": {
      "interval": 180, 
      "command": "check_service.sh -s atomic-openshift-node", 
      "subscribers": [
        "ose-master"
      ], 
      "handlers": [
        "notify_all"
      ]
    }, 
    "service_atomic-openshift-master-controllers_status": {
      "interval": 180, 
      "command": "check_service.sh -s atomic-openshift-master-controllers", 
      "subscribers": [
        "ose-master"
      ], 
      "handlers": [
        "notify_all"
      ]
    }, 
    "service_atomic-openshift-master-api_status": {
      "interval": 180, 
      "command": "check_service.sh -s atomic-openshift-master-api", 
      "subscribers": [
        "ose-master"
      ], 
      "handlers": [
        "notify_all"
      ]
    }

So each check is scheduled every 180 seconds but if I go on the Uchiwa interface I see that the last checks were made 40 minutes ago which I've scheduled manually

**Comment by palourde** [comment]
Hi @dancb10,

If I understand correctly, the problem you are currently facing is that some checks are not automatically ran by your sensu clients? If so, it feels like it might be a configuration issue between the sensu server and the sensu clients. You might want to try to get home help from the [sensu community](https://sensuapp.org/support#community-support) since I don't feel like it's an issue with Uchiwa.

Thanks

**Comment by dancb10** [comment]
Hello @palourde ,
There aren't any wrong configurations because if I use the Uchiwa interface to schedule a check, it will work and will schedule them in the future. Note that this issue appears only for new checks that have just been added to the monitoring system.
And btw why do I need to restart everything (uchiwa, sensu-server, sensu-api, redis) when I add a new check? If i do not restart them, the checks will never appear in the interface
