### ISSUE TITLE
feature: more precise check request

### ISSUE THREAD

**Issue by exeral** [sensu/uchiwa#639]
Issue check requests on specific groups of servers using subscribers attributes: described here https://sensuapp.org/docs/latest/api/checks-api.html#request-post-specification
instead of all check subscribers by default

## Expected Behavior
Be able to specify which subscribers should receive the check request

## Current Behavior
The check request is sent to all the machines that subscribed to this check

## Possible Solution
on client view
https://uchiwa:3000/#/client/datacenter/hostname?check=checkname
in right panel (Check details)
add a refresh icon next to silence and elete result icon (top right corner)
that do an API /request with
```
{
  "check": "checkname",
  "subscribers": [
    "client:hostname"
  ]
}
````
## Steps to Reproduce (for bugs)
- Go to checks view: http://uchiwa:3000/#/checks
 -Tick a check
- Bulk actions
- Issue check request

## Context
Let's say you have a check that perform an heavy SQL request every 15min in MySQL instance of the sensu-client
You have 50 MySQL servers with this check

You're oncall, the alert rings at 3AM on client1
You fix it.
You don't want to wait 10min the next check run to verify the Alert goes back to green, you want to sleep Now !
You don't want to force a check request on all MySQL server that subscribed to this check, it would causes extra load on your whole platform and you just want to refresh 1 client.

**Comment by johntdyer** [comment]
Fwiw, We've accomplished something similar by making every client have a subscription to its own hostname.  Hacky you say, I'd answer probably :). Would be kinda cool to see similar behavior as a first class citizen in sensu.

**Comment by cwjohnston** [comment]
@johntdyer same hack has been made part of Sensu in 0.26 and later, as clients now add a `client:$CLIENT_NAME` subscription automatically. 

I think adding the capability to target check execution requests using per-client subscriptions is a good idea. 👍

**Comment by johntdyer** [comment]
Any plans to move forward with this guys?

**Comment by exeral** [comment]
The code part in charge of this in the check view:
/opt/uchiwa/src/public/bower_components/uchiwa-web/partials/views/check.html
```
                  <i class="fa fa-refresh fa-fw"
                    aria-hidden="true"
                    tooltip-placement="top-right"
                    tooltip-trigger
                    uib-tooltip="Issue Request"
                    ng-click="issueCheckRequest(dc, name, subscribers)">
                  </i>
```

I think we don't have to modify the issueCheckRequest function

I have just replicated this in the client view, in check details panel
graphically, it is what i'm looking for
![image](https://cloud.githubusercontent.com/assets/14330725/25385933/dfab5b3c-29c5-11e7-8c3f-8ef141bdead1.png)

However, I don't know how to submit the subscription value. I'm big noob with angular

would need something like:
```
ng-click="issueCheckRequest(dc, name, '[ \"client:'+client.name+'\" ]')"
```
maybe...
