### ISSUE TITLE
when do i get to use 0.22.1 deb repo

### ISSUE THREAD

**Issue by cabecada** [sensu/uchiwa#640]
i need to make use of the bulk action in events which was (re)introduced in 0.22.1
even though it shows available for download but i cannot see it in the repo

```
root@ubuntu1404-5:~# https://sensu.global.ssl.fastly.net/apt/pubkey.gpg^C
root@ubuntu1404-5:~# dpkg -s uchiwa
Package: uchiwa
Status: install ok installed
Priority: extra
Section: Monitoring
Installed-Size: 18989
Maintainer: Simon Plourde simon.plourde@gmail.com
Architecture: amd64
Version: 0.22.0-1
Conffiles:
 /etc/sensu/uchiwa.json ecdebfef0776e6c113e2083c7e6fab3c
Description: Uchiwa is a simple dashboard for the Sensu monitoring framework.
License: https://github.com/sensu/uchiwa/blob/master/LICENSE
Vendor: Simon Plourde
Homepage: https://uchiwa.io

root@ubuntu1404-5:~# dpkg-query -l | grep uchiwa
ii  uchiwa                              0.22.0-1                          amd64        Uchiwa is a simple dashboard for the Sensu monitoring framework.

root@ubuntu1404-5:~# cat /etc/apt/sources.list.d/sensu.list
# This file is managed by Puppet. DO NOT EDIT.
# sensu
deb http://repositories.sensuapp.org/apt sensu main

root@master:/etc/puppet# grep -A2 uchiwa Puppetfile
mod 'yelp/uchiwa',
  :git => 'https://github.com/yelp/puppet-uchiwa',
  :ref => '0554e1678707ddded65226fb57ebed7eef1dae3b'

```

whereas here i see the 0.22.1 package.
https://docs.uchiwa.io/getting-started/installation/

OS: ubuntu 1404

**Comment by fatal-exception** [comment]
Ah sorry, I've duplicated this in https://github.com/sensu/uchiwa/issues/648, but with some more details of specific repos

**Comment by palourde** [comment]
Hi,

The Sensu repositories structure has been modified recently so as noted, the uchiwa distribution has been deprecated and you should use the proper distribution based on your OS.

I've updated the Uchiwa documentation accordingly, thank you for reporting it to us: https://docs.uchiwa.io/getting-started/installation/

Thanks!
