### ISSUE TITLE
Feature Request: display full event output

### ISSUE THREAD

**Issue by mcbsdEU** [sensu/uchiwa#641]
## Expected Behavior
When check is configured with "auto_resolve":false, events are kept till they are resolved manually.
In between,  check might change the result output, etc. returning back to green state.
Uchiwa should keep the full event output and not redirect to the current check result.

## Current Behavior
Event is kept in event list - all good here.
Output (in column Output) is truncated according column width. And by left click on the row, Uchiwa redirects to current result of the event.
Current result might be different to result for which event was created - etc. state of check has changed in between.

## Possible Solution
Only way to see full output of the retained event is to use Sensu API.

## Steps to Reproduce (for bugs)
N/A

## Context
It is not possible to see full output of event from check with attribute auto_resolve:false.
No way to see what happened directly in Uchiwa web-gui.

## Your Environment
* Uchiwa version used: 0.22.1
* Sensu version used: 0.28
* Operating System and version (e.g. Ubuntu 14.04): CentOS7

Maybe it could work in way when left click on event to display also original output next to the current output. It would be really helpful.

Thanks for good work!

**Comment by mcbsdEU** [comment]
![screen_1](https://cloud.githubusercontent.com/assets/22918156/23454856/eee6fa76-fe6d-11e6-8d32-50a59f4aac54.jpg)
![screen_2](https://cloud.githubusercontent.com/assets/22918156/23454857/eee754a8-fe6d-11e6-8244-d30bb05cd33f.jpg)

**Comment by jpuskar** [comment]
+1

**Comment by palourde** [comment]
@mcbsdEU I was thinking about simply showing the full output within a tooltip, just like this: 
![event-tooltip](https://cloud.githubusercontent.com/assets/4105580/24373552/b34bf8e4-12ff-11e7-9291-c2384643ed46.png)

Modifying the client view to also display any corresponding event entry would require some serious work so the tooltip solution could be a quick win. Any thoughts?

**Comment by mcbsdEU** [comment]
Hi,
many thanks for your reply.
Tooltip is really a quick win - this could be easily implemented in next release I guess.

In addition to that, from mid term perspective, my idea was:
-from events view, when you click on check(check name) you are redirected same as it is working now -> client info on left side, actual check info on right side
-from events view, when you click on output you would be redirected to the view in which on left side you have client info and event payload on right side.

Above is "nice to have", but tooltip is so far very good silver line option.

BTW, what I found confusing, when you navigate to whatever client, then click on whatever check, your navigation bar says "EVENTS-><client_name>-><check_name>".
Why EVENTS? I would expect "Checks" because what I currently see is actual check status and not event (at least by terminology of Sensu's API point of view).

Thanks a lot

**Comment by palourde** [comment]
Thanks for the feedback!

The dashboard will get a major overhaul so we will definitively take these suggestions into consideration when doing so.

For now, I'll go ahead and push a simple patch to add the tooltip.

Thank you

**Comment by bejelith** [comment]
Any update on this?
