### ISSUE TITLE
[Uchiwa] Datacenter Sensu Server returned: Connection error. Is the Sensu API running?

### ISSUE THREAD

**Issue by keeshqs** [sensu/uchiwa#642]
Hi,

We are experiencing an issue in Uchiwa: "Datacenter Sensu Server returned: Connection error. Is the Sensu API running?"
We are currently blocked and I was hoping you can give us some advice and detailed guide on the action that needs to be taken. I've copied our configuration below for reference. Thank you in advance and we would really appreciate your help!

We found out that there is a connection error while looking into the logs in /var/log/sensu/sensu-api.log:
{"timestamp":"2017-03-02T13:52:30.269037+0000","level":"info","message":"api response","request":{"remote_address":"127.0.0.1","user_agent":"Go-http-client/1.1","method":"GET","uri":"/stashes","query_string":null,"body":""},"status":500,"content_length":59}
{"timestamp":"2017-03-02T13:52:40.268106+0000","level":"info","message":"api response","request":{"remote_address":"127.0.0.1","user_agent":"Go-http-client/1.1","method":"GET","uri":"/stashes","query_string":null,"body":""},"status":500,"content_length":59}
{"timestamp":"2017-03-02T13:52:42.937693+0000","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}

**/etc/rabbitmq/rabbitmq.config**
[
    {rabbit, [
     {ssl_listeners, [5671]},
     {ssl_options, [{cacertfile,"/etc/rabbitmq/ssl/cacert.pem"},
                    {certfile,"/etc/rabbitmq/ssl/cert.pem"},
                    {keyfile,"/etc/rabbitmq/ssl/key.pem"},
                    {versions, ['tlsv1.2']},
                    {ciphers,  [{rsa,aes_256_cbc,sha256}]},
                    {verify,verify_peer},
                    {fail_if_no_peer_cert,true}]},
     {tcp_listeners, [{"192.168.30.187", 5672}]}
    ]},
    {rabbitmq_management, [{listener, [{port, 15672}]}]}
].

**/etc/sensu/conf.d/api.json:**

{
  "api": {
    "host": "127.0.0.1",
    "port": 4567
  }
}

**/etc/sensu/conf.d/rabbitmq.json:**

{
  "rabbitmq": {
    "host": "127.0.0.1",
    "port": 5672,
    "user": "admin",
    "password": "admin",
    "vhost": "/sensu",
    "ssl": {
    "cert_chain_file": "/etc/sensu/ssl/cert.pem",
    "private_key_file": "/etc/sensu/ssl/key.pem"}
  }
}

**Comment by envintus** [comment]
Usually a means there's an issue with authenticating with RabbitMQ and the information configured in Sensu to build the DSN for RabbitMQ does not match what RabbitMQ actual knows.

* Ensure your username and password for the user match: `rabbitmqctl authenticate_user {username} {password}`
* Check permissions for the user on the vhost: `rabbitmqctl list_user_permissions {username}`
* If you're including that leading slash in your `rabbitmq.json` configuration, then you need to URL encode it: `%2Fsensu`

A bit about the last bullet. When creating the vhost in RabbitMQ you do not need to include the forwarding slash. If you do, then the vhost name is literally `/sensu`. Hence my suggestion for URL encoding the forward slash. That being said the vhost name could simply be `sensu` and then you avoid needing to include a url encoded forward slash in your `rabbitmq.json` stanza.

**Comment by palourde** [comment]
Hi @keeshqs,

I think @envintus provided really useful information and it should help you solve this issue.

If you are still facing any problem, I would recommend to drop by the #sensu channel on Freenode (IRC) or the [sensu-users mailing list](https://groups.google.com/forum/#!forum/sensu-users) as this issue seems to be related to RabbitMQ and therefore, not much can be done on Uchiwa side.

Thanks!
