### ISSUE TITLE
Patched Uchiwa not available in all deb repositories

### ISSUE THREAD

**Issue by fatal-exception** [sensu/uchiwa#648]
We are trying to install Uchiwa 0.22.1 via our internal deb mirrors.

I've noticed that the patched uchiwa is not available via http://sensu.global.ssl.fastly.net/apt/pool/sensu/main/u/uchiwa/, (latest version there is 0.22.0) but is available at http://sensu.global.ssl.fastly.net/apt/pool/trusty/main/u/uchiwa/. 

Is this intentional, or is this an accident? It strikes me that these 2 repos should be in sync, but maybe I'm wrong. We only mirror sensu/main internally, not trusty/main, so we still have the bulk_actions bug in our Uchiwa, which was fixed in 0.22.1.

## Expected Behavior
I expect the above repos to both have the same versions of packages available

## Current Behavior
The above 2 repos have different sets of Uchiwa packages available

## Possible Solution
Keep the 2 in sync? Not sure if this is the desired outcome

## Steps to Reproduce (for bugs)
Compare http://sensu.global.ssl.fastly.net/apt/pool/sensu/main/u/uchiwa/ with http://sensu.global.ssl.fastly.net/apt/pool/trusty/main/u/uchiwa/, note that only the latter contains uchiwa 0.22.1.

## Context
Internally, due to our Sensu repo mirroring setup, we cannot update Uchiwa to the latest version. As a result, we are suffering from the bulk_actions bug.

## Your Environment
* Uchiwa version used: 0.22.0
* Sensu version used: 0.26.5
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 14.04

**Comment by fatal-exception** [comment]
Sorry this is basically a duplicate of https://github.com/sensu/uchiwa/issues/640 but with repo-urls

**Comment by palourde** [comment]
Hi,

The Sensu repositories structure has been modified recently so as noted, the `uchiwa` distribution has been deprecated and you should use the proper distribution based on your OS.

I've updated the Uchiwa documentation accordingly, thank you for reporting it to us: https://docs.uchiwa.io/getting-started/installation/

Thanks!
