### ISSUE TITLE
Uchiwa Release on Github

### ISSUE THREAD

**Issue by sstarcher** [sensu/uchiwa#655]
## Expected Behavior
curl -s https://api.github.com/repos/sensu/uchiwa/releases/latest
Should return the latest release, but is returning 0.5.1

## Current Behavior
Rreturns 0.5.1

## Steps to Reproduce (for bugs)
curl -s https://api.github.com/repos/sensu/uchiwa/releases/latest

## Context
I was trying to automate the fetching of the latest release info from github.

**Comment by palourde** [comment]
Hi @sstarcher 

Github releases are not used anymore, which explains the old version returned. I went ahead and removed all Github releases to avoid any confusion.

Could you use [Bintray API](https://api.bintray.com/packages/palourde/uchiwa/uchiwa/versions/_latest) to fetch the latest package version available or use the [Github API](https://api.github.com/repos/sensu/uchiwa/tags) and use the most recent tag.

Thanks
