### ISSUE TITLE
[Security]Uchiwa 0.22.2: SecureFlag missing in AuthenticationToken and XSRF-Token cookie

### ISSUE THREAD

**Issue by itsDaksha** [sensu/uchiwa#656]
## Expected Behavior
From security point of view, it is required that SecureFlag must be set in all sensitive cookies.

## Current Behavior
Currently, there is no SecureFlag in AuthenticationToken and XSRF-Token cookie

## Possible Solution
SecureFlag can be added in HTTP response to avoid any security vulnerability.

Reference: https://www.owasp.org/index.php/SecureFlag

**Comment by palourde** [comment]
Note: We should only set the Secure flag if the connection is encrypted over HTTPS therefore the backend server. It should be relatively easy to do [here](https://github.com/sensu/uchiwa/blob/master/uchiwa/authentication/services.go#L49)

**Comment by itsDaksha** [comment]
Any possibility of getting this fix in 0.22.x?
