### ISSUE TITLE
Using Sensu with Uchiwa config error

### ISSUE THREAD

**Issue by arianf** [sensu/uchiwa#659]
When using these version of Sensu and Uchiwa, I have a weird configuration syntax issue.

 - sensu-0.28.4-1.el6.x86_64.rpm
 - uchiwa-0.22.2-1.x86_64.rpm

The problem occurs inside of `/etc/sensu/uchiwa.json`

```json
{
  "sensu": [
    {
      "name": "Sensu",
      "host": "127.0.0.1",
      "ssl": false,
      "port": 4567,
      "user": "admin",
      "pass": "*********"
    }
  ],
  "uchiwa": {
    "user": "",
    "pass": "",
    "port": 3000,
    "refresh": 10000
  }
}
```

Sensu will give me this error: 

```json
configuration is invalid
{
  "errors":[
    {
      "object":[
        {
          "name":"Sensu",
          "host":"127.0.0.1",
          "ssl":false,
          "port":4567,
          "user":"admin",
          "pass":"*********"
        }
      ],
      "message":"sensu must be a hash"
    }
  ]
}
```

Then, if I change Sensu to be a hash...

```json
{
  "sensu": {
    "name": "Sensu",
    "host": "127.0.0.1",
    "ssl": false,
    "port": 4567,
    "user": "admin",
    "pass": "*********"
  },
  "uchiwa": {
    "user": "",
    "pass": "",
    "port": 3000,
    "refresh": 10000
  }
}
```

I get the following error from Uchiwa.

```json
{
  "timestamp":"2017-03-22T17:56:59.287845584-07:00",
  "level":"fatal",
  "message":"Error decoding file /etc/sensu/uchiwa.json: json: cannot unmarshal object into Go struct field Config.Sensu of type []config.SensuConfig"
}
```

Who is right? Can I downgrade my Sensu version to one that works with Uchiwa?

## Your Environment
* Uchiwa version used: uchiwa-0.22.2-1.x86_64.rpm
* Sensu version used: sensu-0.28.4-1.el6.x86_64.rpm
* Operating System and version (e.g. Ubuntu 14.04): Oracle Linux Server release 6.4

**Comment by cwjohnston** [comment]
Hi @arianf, it seems like your Sensu installation is loading Uchiwa configuration and that's not supported by Sensu. Uchiwa and Sensu both use a `sensu` configuration key, but have different expectations about its value.

Sensu packages ship with service management scripts which are configured to load configuration from the `/etc/sensu/config.json` file and recursively load configuration from `/etc/sensu/conf.d`. 

Uchiwa, on the other hand, loads configuration from the `/etc/sensu/uchiwa.json` file and recursively from `/etc/sensu/dashboard.d` directory.

When using these defaults Sensu should not be evaluating `/etc/sensu/uchiwa.json` during configuration loading. Is it possible that you've reconfigured Sensu's configuration directory path from `/etc/sensu/conf.d` to `/etc/sensu` ?

**Comment by arianf** [comment]
You're right... I understand now...

My `/etc/sensu/uchiwa.json` was a sym link to `/etc/sensu/conf.d/conf.d/uchiwa.json`

Thanks for your help!
