### ISSUE TITLE
"Issued" and "Last OK" timestamp show 47 years ago

### ISSUE THREAD

**Issue by jothoma1** [sensu/uchiwa#665]
With the last update of Uchiwa (0.23.0-1), the timestamps of "Last Ok" and "Issued" shows "47 years ago"

## Expected Behavior

Last Ok & Issued must display the correct timestamps

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Uchiwa version used: 0.23.0-1
* Sensu version used: 0.26.5
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by jothoma1** [comment]
![uchiwa-bug](https://cloud.githubusercontent.com/assets/19167503/24399633/a88c704c-13ad-11e7-8370-f7585277a395.png)

**Comment by brumle80** [comment]
having excact same issue, same os same versions.

**Comment by palourde** [comment]
Hi @jothoma1 

Could you try to clear your browser cache or even try with a second browser? Some libs related to the date manipulation have been upgraded and somehow the browser still uses outdated files.

It seems we still have an issue with assets caching so I created an issue for this problem: https://github.com/sensu/uchiwa/issues/666.

Thanks

**Comment by jothoma1** [comment]
Hi @palourde 

You are right, i tried with another browser and it's ok !
Thanks a lot 
Johan

**Comment by palourde** [comment]
Thank you for the update. I'm sorry about that, I thought we had nailed this caching issue. We'll use the issue https://github.com/sensu/uchiwa/issues/666 to track this problem and I hope to be able to release a permanent fix within the next few days.
