### ISSUE TITLE
Silenced Reason Not Being Submitted To API

### ISSUE THREAD

**Issue by Evesy** [sensu/uchiwa#667]
When silencing multiple checks from the Events page, the 'Reason' field is not being included in the request payload to Sensu API

## Expected Behavior
I select multiple events in Uchiwa (For one, or multiple datacentres) & then select Silence from the Bulk Actions menu.
I set to expire on resolve and populate the reason field with some text. The silenced entries should then be created with all the relevant context, including the reason.

## Current Behavior
When silencing multiple events at once in Uchiwa the 'Reason' field is seemingly not being included in the request payload to the API. See the two below API entries for two different scenarios:

**Event that was silenced as a bulk action with multiple other events**
('Create the following silenced entries' interface)

```
{"timestamp":"2017-03-28T15:45:24.174040+0000","level":"info","message":"api response","request":{"remote_address":"REDACTED","user_agent":"Go-http-client/1.1","method":"POST","uri":"/silenced","query_string":null,"body":"{\"id\":\"\",\"dc\":\"Staging DC1\",\"subscription\":\"client:REDACTED\",\"check\":\"system_io_metrics\",\"creator\":\"admin\",\"expire_on_resolve\":true}\n\n"},"status":201,"content_length":0}
```

**Event that was silenced on its own**
('Create a silencing entry' interface)
```
{"timestamp":"2017-03-28T15:59:55.448207+0000","level":"info","message":"api response","request":{"remote_address":"REDACTED","user_agent":"Go-http-client/1.1","method":"POST","uri":"/silenced","query_string":null,"body":"{\"id\":\"\",\"dc\":\"Staging DC1\",\"subscription\":\"client:REDACTED\",\"check\":\"system_io_metrics\",\"reason\":\"Test reason\",\"creator\":\"admin\",\"expire_on_resolve\":true}\n\n"},"status":201,"content_length":0}
```

I was not able to see in the Uchiwa logs exactly what it was requesting to the Sensu API, even with debug logs, however hopefully the API logs above are sufficient.

## Steps to Reproduce (for bugs)
1. Select multiple events in Uchiwa
2. Select 'Silence/Unsilence' from the Bulk Actions dropdown
3. Input your reason via the 'Create the following silenced entries' interface
4. Once submitted view Silenced entries in Uchiwa or via the API.
5. The 'reason' field should be blank

## Your Environment

* Uchiwa version used: 0.23
* Sensu version used: 0.2804
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7.3

**Comment by Evesy** [comment]
Had a look in the console log on my browser (Chrome Version 57.0.2987.110) and I can see that the API request payload does not include the 'reason' either when silencing multiple entries at once:
```
Request URL: http://sensu.atcloud.io/silenced
```
```
Request Payload
{"dc":"Production DC2","check":"elastic_elasticsearch_index_threshold_check_infrastructurelogs","subscription":"client:elastic-elasticsearch","expire_on_resolve":true}
```

Also replicated on Firefox 51.0.1 (32-bit).

**Comment by palourde** [comment]
Hi @Evesy 

Thanks for reporting this issue, I was able to successfully reproduce it. A patch has just been pushed, it will be included within the next patch release of Uchiwa, which we hope to be able to release before the end of the week. I apologize for the inconvenience.

Thank you!
