### ISSUE TITLE
Provide Indication For Flapping Checks

### ISSUE THREAD

**Issue by Evesy** [sensu/uchiwa#673]
A small change that I think could prove to be beneficial is to provide some sort of indication for a user when a check is in a flapping state (Particularly for when the event is currently in an OK state), rather than simply displaying the event with the current status

## Expected Behavior
When an event is in a flapping state there is a visual indicator to inform the user of this, rather than them having to know about the behavior of flapping events in Sensu

## Current Behavior
A flapping event is displayed just like any other event, with a visual icon (Green tick, red cross etc.) to tell the user the current state of the check.
Nothing currently says that an event is flapping, which can lead to confusion for people who see 'OK' checks in the events view (As typically an event would/should not exist for an OK result)

## Possible Solution

- Update the status icons to include an additional icon for a flapping check
- If the event 'action' is flapping, display this in the check output status

## Context
This initially threw me off when I saw an OK check in the events view of Uchiwa and took me a few minutes to realize that the check was flapping (After checking the API) -- Given we only make use of flap thresholds in one or two checks it was not something I had come across before.

For someone less familiar with Sensu this is likely to cause some confusion and wasted time trying to figure why such an event is displayed. Granted, this then needs the user to have some awareness of flapping, however it at least points them in the right direction.

**Comment by palourde** [comment]
Hi @Evesy 

I've just submitted https://github.com/sensu/uchiwa-web/pull/162, which adds an icon in the output of an event in the events view to indicate flapping events as suggested.

It will be included in the next release of Uchiwa.

Thanks!
