### ISSUE TITLE
Search on custom filed not working

### ISSUE THREAD

**Issue by yakirgb** [sensu/uchiwa#674]
I created custom filed for event with key=env and value=environment name (env:production)
I see the filed in Sensu API and in uchiwa, for example:
~$ curl -s http://sensu-api.service.consul.tbl.com:4567/events/70e34.tbl.com/check_process | jq '.check.env'
"production"
but query of env:production in uchiwa search bar ( http://uchiwa:8080/#/events?q=env:production ) return **0 items** 

## Expected Behavior
Query all events with key:value of env:production

## Current Behavior
Query of env:production via search bar ( http://uchiwa:8080/#/events?q=env:production )
return 0 rows

## Steps to Reproduce (for bugs)
1. Create event with custom field
2. Query on your field with  http://uchiwa:8080/#/events?q=field:value
## Context
We have multiple teams, and every team want to query and custom fields, for example: team name, env, OS,  etc.

## Your Environment
* Uchiwa version used: 0.23.1
* Sensu version used: 0.26.1
* Operating System and version: CentOS 6.7

**Comment by cabecada** [comment]
same here.
it does not work for us, although it was working in 0.22

**Comment by palourde** [comment]
Looks like this bug was introduced with https://github.com/sensu/uchiwa-web/pull/147 and only affects fields within `check` or `client`.

**Comment by yakirgb** [comment]
@palourde but my version is 0.23.1, with your commit and it's still not working.

Our main problem is that we have many teams and a lot of events, each team want to see just alerts that related to itself, without alerts of other teams, i created filed with key of team and value of team name: DevOps / IT / R&D /  DBA etc.
and it's not working well because **i cannot query on team: devops** .
Please advice.

**Comment by palourde** [comment]
@yakirgb I just pushed the patch with https://github.com/sensu/uchiwa-web/pull/156. It will be available within the next release, which I hope to be able to release by tomorrow.
