### ISSUE TITLE
Feature Request: Make links actual links

### ISSUE THREAD

**Issue by Gillingham** [sensu/uchiwa#682]
It would be really nice if all the javascript based navigation also set links on the elements so we had the option to open them in a new tab or window. I often find myself trying to open multiple things from a given view in a tab or window and am disappointed when only one thing opens in the current context.
Some of the links like the main navigation least work via right click but this is not universal for things like the actual table elements in those main pages.

## Expected Behavior
Any link in the uchiwa GUI would allow me to ctrl/command+click or right click open in to function as a normal webpage does.

## Current Behavior
Ctrl clicking any linked element simply opens the view in the current window/tab

**Comment by palourde** [comment]
Hi @Gillingham 

Thank you for your suggestion. We already have an issue for this feature: https://github.com/sensu/uchiwa/issues/381 so I'll go ahead and close this one to prevent any duplication.

Unfortunately there's no easy way to implement this with Angular 1 that I'm aware of. If anyone have a suggestion, I'm listening!

Thanks
