### ISSUE TITLE
Pagination for clients view

### ISSUE THREAD

**Issue by exeral** [sensu/uchiwa#683]
There is no pagination at top or bottom when you have more client than the display limit

## Expected Behavior
be able to navigate between set of clients when limit is exceeded

## Current Behavior
to see the rest of clients you must increase the limit

## Possible Solution
buttons or arrows or numbers at top and/or bottom of page to navigate
like this:
![tiny-bootstrap-style-pagination-component-with-jquery-blade-pagination](https://user-images.githubusercontent.com/14330725/36801563-c2fc9eb6-1cb2-11e8-8aeb-76e24f45211b.jpg)

## Steps to Reproduce (for bugs)
Have 75 clients
Go to clients view
With the default 50 limit, the first 50 clients are shown
You can't see the next 25 clients without increasing the view limit

![image](https://cloud.githubusercontent.com/assets/14330725/25906368/c1df1662-35a4-11e7-9bed-ba2089b54328.png)

## Context
Let's say you have 1000 hosts
You want to navigate through your clients by bunch of 50
You don't want to increase the limit to: ALL and display the whole 1000 clients in 1 page

I bet the same issue exists for the checks view

## Your Environment
Sensu 0.29.0
Uchiwa 0.24
Google Chrome 58.0.3029.96

**Comment by annaplotkin** [comment]
This is impacting Sony and other users.

**Comment by annaplotkin** [comment]
This has been addressed in Sensu Go's web UI and we will be investing our development resources to continually enhance the experience there. Sensu Classic is now in Maintenance Mode and as such, we will be addressing this and future enhancements in Sensu Go. Please let us know if we can help with migration.
