### ISSUE TITLE
Cipher suites configuration

### ISSUE THREAD

**Issue by itsDaksha** [sensu/uchiwa#688]
Could you recommend us any method to configure specific Cipher Suites which can be used while communicating with Uchiwa over a secure channel?

**Comment by palourde** [comment]
Customizing the cipher suites would require a small modification to the codebase, more specifically [here](https://github.com/sensu/uchiwa/blob/master/uchiwa/server.go#L1384).

Here's an example on how to define specific suites: https://github.com/golang/go/issues/11047

**Comment by itsDaksha** [comment]
Can you provide a tentative timeline/release when can this feature be expected in Uchiwa? Thank you.

**Comment by palourde** [comment]
Hi @itsDaksha 

There's no plan on my side to work on this feature in the short term since I consider the default ciphers to be an appropriate balance between security and compatibility.

That being said, I would gladly accept a pull request that implements this feature if anyone is interested!
