### ISSUE TITLE
Silencing by subscription not working correctly

### ISSUE THREAD

**Issue by bodgit** [sensu/uchiwa#689]
I have the following scenario, four machines; A, B, C, D:

* A & C run Red Hat
* B & D run CentOS
* A & B are in the production environment
* C & D are in the test environment

Each machine has a Sensu subscription derived from their OS name (via Puppet and lower-cased for simplicity) and another subscription named after their environment.

I have a Sensu check (`yum`) that runs on any subscribers of either `redhat` or `centos`, (it's checking pending package updates), and as patches are only done at a specific time of the month based on the environment I wanted to create a silence entry that expires when the patching should have completed per environment, so I created a silence entry for that one check for any client with a subscription based on their environment, (i.e. `test:yum`, or `production:yum`) with a fixed date in the future when patching should have run.

## Expected Behavior

Any non-OK events should be shown as silenced in Uchiwa. Looking at the Sensu server logs shows that Sensu thinks the event is silenced, (i.e. I get something like `...,"silenced":true,"silenced_by":["test:yum"]}}`).

## Current Behavior

Uchiwa doesn't show the events as silenced. Also, if I instead create a silence entry based on the OS subscription & check name, (i.e. `centos:yum`) then it silences the events for both machines subscribed to `centos` and the machines with the `redhat` subscription as well.

## Steps to Reproduce (for bugs)

See above.

## Context

I thought this was possibly a Sensu bug until I manually hit the Sensu API and picked through the Server logs and it seems to me Sensu is doing the right thing. Uchiwa seems to be misinterpreting the Sensu API and either not applying silences to events or mis-applying the silences to the wrong events.

## Your Environment

* Uchiwa version used: 0.25.2
* Sensu version used: 0.29.0
* Operating System and version (e.g. Ubuntu 14.04): Red Hat 7.3

**Comment by palourde** [comment]
Hi @bodgit,

Could you provide us the output of the events from both Sensu (e.g. http://127.0.0.1:4567/events) and Uchiwa (e.g. http://127.0.0.1:3000/events) APIs?

If you have authentication enabled on Uchiwa, it might be useful to setup an access token (see https://docs.uchiwa.io/api/authentication/).

Thanks!

**Comment by bodgit** [comment]
Sure @palourde . Here's an example host from the Sensu API:
```json
[
  {                                                                                                                                                                                                                                    
    "client": {
      "name": "prod-a-host",
      "address": "192.0.2.1",
      "subscriptions": [
        "production",
        "redhat",
        "client:prod-a-host"
      ],
      "redact": [
        "password"
      ],
      "socket": {
        "bind": "127.0.0.1",
        "port": 3030
      },
      "safe_mode": false,
      "keepalive": {},
      "version": "0.29.0",
      "timestamp": 1498130009
    },
    "check": {
      "command": "/usr/lib64/nagios/plugins/check_updates -t 60",
      "interval": 3600,
      "subscribers": [
        "redhat",
        "centos"
      ],
      "standalone": false,
      "aggregate": "updates",
      "handle": false,
      "name": "yum",
      "api_requested": {
        "reason": null,
        "creator": null
      },
      "issued": 1498130002,
      "executed": 1498130002,
      "duration": 6.836,
      "output": "<snipped>",
      "status": 2,
      "type": "standard",
      "history": [
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2"
      ],
      "total_state_change": 0
    },
    "occurrences": 80,
    "occurrences_watermark": 80,
    "action": "create",
    "timestamp": 1498130009,
    "id": "f4964172-919d-4fba-a001-90d410f1f6aa",
    "last_state_change": 1497692784,
    "last_ok": 1497692784,
    "silenced": true,
    "silenced_by": [
      "production:yum"
    ]
  }
]
```
And here's the same host from the Uchiwa API:
```json
[
  {                                                                                                                                                                                                                                
    "_id": "sensu/p-slo-vl003.aspectcapital.com/yum",
    "action": "create",
    "check": {
      "aggregate": "updates",
      "api_requested": {
        "creator": null,
        "reason": null
      },
      "command": "/usr/lib64/nagios/plugins/check_updates -t 60",
      "duration": 6.836,
      "executed": 1498130002,
      "handle": false,
      "history": [
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2",
        "2"
      ],
      "interval": 3600,
      "issued": 1498130002,
      "name": "yum",
      "output": "<snipped>",
      "standalone": false,
      "status": 2,
      "subscribers": [
        "redhat",
        "centos"
      ],
      "total_state_change": 0,
      "type": "standard"
    },
    "client": {
      "address": "192.0.2.1",
      "keepalive": {},
      "name": "prod-a-host",
      "redact": [
        "password"
      ],
      "safe_mode": false,
      "silenced": false,
      "socket": {
        "bind": "127.0.0.1",
        "port": 3030
      },
      "subscriptions": [
        "production",
        "redhat",
        "client:prod-a-host"
      ],
      "timestamp": 1498130009,
      "version": "0.29.0"
    },
    "dc": "sensu",
    "id": "f4964172-919d-4fba-a001-90d410f1f6aa",
    "last_ok": 1497692784,
    "last_state_change": 1497692784,
    "occurrences": 80,
    "occurrences_watermark": 80,
    "silenced": false,
    "silenced_by": null,
    "timestamp": 1498130009
  }
]
```

**Comment by palourde** [comment]
Thanks for providing this information, I'm looking at it now!
