### ISSUE TITLE
URL Shortening Wrapping Several Lines

### ISSUE THREAD

**Issue by Evesy** [sensu/uchiwa#690]
URL's are being shortened in the Client view however hyphens within the URL are causing it to be wrapped over several lines.

## Expected Behavior
A URL should be displayed on a single line, shortened if necessary.

## Current Behavior
URL is shortened up until a hyphen in the URL, in which the text is then wrapped onto the following line.

<img width="377" alt="screen shot 2017-06-09 at 18 51 08" src="https://user-images.githubusercontent.com/17579850/26988142-11a4d714-4d46-11e7-9124-9a97ebbe1fa0.png">

## Your Environment

* Uchiwa version used: 0.25.2
* Sensu version used: 0.29
* Operating System and version (e.g. Ubuntu 14.04): Centos 7.3
* Browser: Google Chrome 58.0.3029.110 (Same in other browsers)

**Comment by jothoma1** [comment]
:+1:
