### ISSUE TITLE
Contributing page broken in uchiwa-docs

### ISSUE THREAD

**Issue by br0ch0n** [sensu/uchiwa#691]
## Expected Behavior

Shows pretty instructions, kinda like in https://github.com/palourde/uchiwa-docs/blob/master/content/contributing/index.md

## Current Behavior

Shows unformatted mess: https://docs.uchiwa.io/contributing/
Confirmed that it's messy on local hugo as well.

**Comment by palourde** [comment]
@br0ch0n Thank you for reporting this issue. It has been fixed with https://github.com/palourde/uchiwa-docs/commit/19bad2dbafbb5cd02053a6c063a33286be573203!
