### ISSUE TITLE
Uchiwa LDAP Configuration

### ISSUE THREAD

**Issue by makaveli0129** [sensu/uchiwa#695]
Under the API for info on Uchiwa there shows an LDAP json (https://pasteboard.co/21ZDb0anf.png)
Is there any documentation that outlines how to use LDAP for authentication with Uchiwa? There is Go modules in the code and everything like that but i can't seem to find any documentation on it. I don't need anything special just simple bind and authentication into LDAP with RBAC from LDAP to Uchiwa roles.

Thanks for all the help and insights.

**Comment by palourde** [comment]
Hi @makaveli0129 

LDAP authentication is only part of Sensu Enterprise (https://sensuapp.org/enterprise). 

You could however easily fork this project and add your own LDAP driver, as long it satisfies [this function](https://github.com/sensu/uchiwa/blob/master/uchiwa/authentication/models.go#L11).

Thanks
