### ISSUE TITLE
Inconsistencies with compound filters

### ISSUE THREAD

**Issue by bodgit** [sensu/uchiwa#697]
## Expected Behavior
I was trying to work out if it was possible to filter hosts in Uchiwa by more than one attribute value (although I was specifically using subscription names). I eventually worked out that `subscription1,subscription2` seems to mostly work.

## Current Behavior
Order seems to matter though. If I have a host that I know has at least two subscriptions, `subscription1,subscription2` will result in no hosts yet `subscription2,subscription1` will filter to the host in question. It's not alphabetical order of the filter values, it seems random. Sometimes though it doesn't filter to any/all matching hosts if I know more than one host should match the filter.

## Steps to Reproduce (for bugs)
1. Have multiple hosts with multiple subscriptions
2. Try filtering with `subscription1,subscription2` and `subscription2,subscription1`
3. (Hopefully) observe the different results

## Context
Not sure if it's something that is supposed to work? I stumbled on it after trying various `foo AND bar`, `foo & bar`, etc. combinations.

## Your Environment
* Uchiwa version used: 0.25.2
* Sensu version used: 0.29.0
* Operating System and version (e.g. Ubuntu 14.04): RHEL 7.3

**Comment by palourde** [comment]
Thanks for opening this issue!

The search queries in Uchiwa were not designed to work with multiple values, which might explain the observed behavior. We'll have to put more work to support the expected behavior.
