### ISSUE TITLE
uchiwa UI does not show up after using rpm package

### ISSUE THREAD

**Issue by herrryan** [sensu/uchiwa#700]
The uchiwa UI does not show up after installed with yum install uchiwa.rpm. Only 404 page not found is displaying on the browser.

## Expected Behavior

The uchiwa UI should show up.
## Current Behavior

Only 404 page not found is displaying on the browser.

## Possible Solution

check rpm package if it is any steps missing?

## Your Environment

* Uchiwa version used: 0.25.2-1.x86_64
* Sensu version used: 0.29.0-11.el7.x86_64
* Operating System and version (e.g. Ubuntu 14.04): RHEL 7.3

**Comment by pgporada** [comment]
Can you successfully curl the endpoint `curl -ILk http://${yourip}/${uchiwa_port}`?

**Comment by palourde** [comment]
I'm closing this issue since we didn't received any responses.

If you are still facing this problem, please let us know with a comment and we'll be happy to reopen the issue.

Thanks!
