### ISSUE TITLE
Sort by silenced/unsilenced checks

### ISSUE THREAD

**Issue by pgporada** [sensu/uchiwa#702]
Being able to sort all the checks and have silenced checks be at the bottom of the list would be useful for us. We have a ton of standalone checks defined, but quite a few are silenced at any given time due to various work items. 

## Your Environment
* Uchiwa version used: uchiwa-0.25.2-1.x86_64
* Sensu version used: sensu-0.29.0-11.el7.x86_64
* Centos7

**Comment by palourde** [comment]
Hi @pgporada,

We have filters under the `Hide` menu to hide silenced clients and/or silenced checks in the events view. Could that work for you?

**Comment by pgporada** [comment]
That works, I didn't consider using those options to see what I wanted to
see. Thanks!

On Jul 17, 2017 13:43, "Simon Plourde" <notifications@github.com> wrote:

Hi @pgporada <https://github.com/pgporada>,

We have filters under the Hide menu to hide silenced clients and/or
silenced checks in the events view. Could that work for you?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sensu/uchiwa/issues/702#issuecomment-315827521>, or mute
the thread
