### ISSUE TITLE
Bug: "Invalid date" for [created] field - Stashes

### ISSUE THREAD

**Issue by mcbsdEU** [sensu/uchiwa#705]
## Expected Behavior
Field "created" inside a stash should display the same as same field in the list of stashes.

## Current Behavior
When stash is created with "timestamp" field and opened in Uchiwa, "created" field says "invalid date". When same stash is displayed in the list, "created" field display correct value.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Create stash with timestamp
2. Open stash and check "created" field
3. List all stashes, including desired one, and check "created" field

## Context
Limited user experience.

![stash_ok](https://user-images.githubusercontent.com/22918156/28670721-45834f84-72da-11e7-87a2-7be298423107.jpg)

![stash_nok](https://user-images.githubusercontent.com/22918156/28670724-474042d2-72da-11e7-9fd6-bbaaa7a00a94.jpg)

## Your Environment
* Uchiwa version used: 0.25.2
* Sensu version used: 0.29
* Operating System and version (e.g. Ubuntu 14.04): RHEL 7

**Comment by mcbsdEU** [comment]
It is weird but I did nothing special and it is displayed correctly now.
I think only action performed in between was restart of sensu services (excluding uchiwa).
Fortunately I captured screenshot so it simply happened....
If someone can reproduce - would be nice. If not, I think this can be closed.

**Comment by palourde** [comment]
Hi @mcbsdEU, sorry for the delayed response, I was in vacation for the past few weeks!

I'll go ahead and close this issue but do not hesitate to let us know if you are able to reproduce this issue.

Thanks
