### ISSUE TITLE
uchiwa shows multi-line 'check' output as single line

### ISSUE THREAD

**Issue by mbramwel** [sensu/uchiwa#708]
since the 0.25.3 update, checks that were displaying multi-line output are now showing everything on a single line.

I have checked the log and can see the embedded \n in the data being sent to uchiwa.

Some of our checks display output that is meant to be viewed multi-lined.

## Expected Behavior

Example:  If the log has  One\nTwo\nThree
I would expect to see:
One
Two
Three

## Current Behavior

What I do see is in uchiwa:
One Two Three

## Your Environment

* Uchiwa version used: 
Name        : uchiwa
Epoch       : 1
Version     : 0.25.3
Release     : 1

* Sensu version used: 
Name        : sensu
Epoch       : 1
Version     : 1.0.2
Release     : 1.el7

* Operating System and version (e.g. Ubuntu 14.04):
centos 7.3  (yum updated nightly)

**Comment by pietervogelaar** [comment]
I experience the same

**Comment by palourde** [comment]
Hi @mbramwel, sorry for the delayed response, I was in vacation for the past few weeks!

Can you tell me which version you were using before this upgrade? I just tried quickly to rollback to 0.24.0 and I still see the same behavior.

Thanks!

**Comment by mcbsdEU** [comment]
I have the same issue on that.

**Comment by mcbsdEU** [comment]
@palourde 
I did downgrade to 0.25.2 and the issue is not there (had to hard refresh page in browser).

**Comment by nmccollum** [comment]
I can confirm on my version of uchiwa, 0.26.1, the issue persists.

**Comment by majormoses** [comment]
Confirm this affects `0.25.3`

**Comment by VLZZZ** [comment]
0.26.3 still here.....

**Comment by XDestination** [comment]
Seems to have been introduced here: https://github.com/sensu/uchiwa-web/commit/2b6cc2a025a4a655473d21e548658df70687f076
Actually https://github.com/sensu/uchiwa-web/pull/9 would have fixed it for me, not sure what it breaks though.

**Comment by doulakis** [comment]
+1
