### ISSUE TITLE
Feature request - Update counts based on applied filter

### ISSUE THREAD

**Issue by bodgit** [sensu/uchiwa#709]
## Expected Behavior
I've had a request from users that it would be nice if the counts on the left side respected any applied filter. i.e. if there are 5 alerts in total and I apply a filter which shows no alerts, it would be nice if the counts then show 0. Similar for clients too.

## Current Behavior
Currently the counts don't change and always show the totals. I've found #435 which is in a similar vein.

## Steps to Reproduce (for bugs)
See above.

## Your Environment
* Uchiwa version used: 0.25.3
* Sensu version used: 0.29.0
* Operating System and version (e.g. Ubuntu 14.04): CentOS/RHEL 7

**Comment by arthurlogilab** [comment]
@bodgit is this closed as in "wontfix" or "fixed" ?

**Comment by bodgit** [comment]
Closed as "wontfix", given Uchiwa seems to be in maintenance mode now.

**Comment by arthurlogilab** [comment]
Thanks for the context.
