### ISSUE TITLE
wrong DELETE url generated for clients starting with '.'

### ISSUE THREAD

**Issue by IoanaStanescu** [sensu/uchiwa#710]
When having a client who's name starts with **.**, at deletion a wrong url is generated. 

- Generated url:
   _localhost:3000/clients.mongo?dc=France_  where **.mongo** is the name of the client

- Correct url for deletion:
  _localhost:3000/clients/.mongo?dc=France_  

I assume this is a consequence of character escaping.

Environment:
Uchiwa: 0.25.3-1 
Sensu: 1.0.0-1
Ubuntu: 14.04.4

**Comment by palourde** [comment]
Hello @IoanaStanescu, sorry for the delayed response, I was in vacation for the past few weeks!

I was able to reproduce this problem, thank you for reporting it.

Note for myself: it seems that using `.client` cause this issue but `.sensu-client` works.
