### ISSUE TITLE
Display keepalives under Events page

### ISSUE THREAD

**Issue by Blue0ctober** [sensu/uchiwa#714]
Under the Events page, there currently is no way to filter hosts with only keepalives. 

## Expected Behavior
From Events page, filter for keepalives should show hosts with only keepalives.

## Current Behavior
Currently there is no way to display hosts that do not have other subscriptions under the Events page. 

## Possible Solution
Add a filter for Keepalives

## Context
Not having dead hosts showup on the event board can be an issue if someone is monitoring just the Events page

**Comment by palourde** [comment]
@Blue0ctober Just to make sure I understand properly the requirement, we basically need a way to only display clients with the basic `client:client_name` subscription?
