### ISSUE TITLE
Add a Login Page to Protect Uchiwa Dashboard

### ISSUE THREAD

**Issue by sjkeerthi** [sensu/uchiwa#716]
Hi 

It will be great that if you could Add a Login page to protect the Dashboard rather than seeing them directly.

If the uchiwa was exposed to Public there is a chance to anyone can scan the port and can access through browser and can put all the machine to silent mode.

**Comment by palourde** [comment]
Hi @sjkeerthi,

See the Uchiwa documentation, you can define a [single user](https://docs.uchiwa.io/getting-started/configuration/#uchiwa-configuration) with the `user` and `pass` attributes or [multiple users](https://docs.uchiwa.io/getting-started/configuration/#uchiwa-configuration).

Thanks
