### ISSUE TITLE
Can't logout 

### ISSUE THREAD

**Issue by arthurlogilab** [sensu/uchiwa#722]
## Expected Behavior
Click logout, go back to seeing nothing and having login screen. 

## Current Behavior

Click logout, User icon disappears, still seeing all the pages/checks/hosts, etc.

## Your Environment

* Uchiwa version used:0.26.3-1
* Sensu version used:1.1.1-1
* Operating System and version (e.g. Ubuntu 14.04):debian jessie

**Comment by arthurlogilab** [comment]
Oh, and from then on, I can't login into uchiwa.

**Comment by palourde** [comment]
Hi @arthurlogilab,

Have you tried to open your browser console to see if there's any JS errors? Also, did you find anything relevant in the Uchiwa logs?

Thanks!

**Comment by majormoses** [comment]
I upgraded yesterday and have not seen that problem. Is there anything special about your setup? Can you replicate with a minimal setup (no bells and whistles)?

**Comment by palourde** [comment]
I'm closing this issue since we didn't received any responses.

If you are still facing this problem, please let us know with a comment and we'll be happy to reopen the issue.

Thanks!
