### ISSUE TITLE
Dockerfile did not compile unless moving to golang 1.8

### ISSUE THREAD

**Issue by jpoizat** [sensu/uchiwa#731]
Tried to compile the docker image using Dockerfile... I had to modify it to golang 1.8

## Expected Behavior

docker build works

## Current Behavior

Sending build context to Docker daemon  43.49MB
Step 1/7 : FROM golang:1.6.3-alpine
 ---> 8c6e04805d43
Step 2/7 : COPY . /go/src/github.com/sensu/uchiwa
 ---> Using cache
 ---> 31aedffbf582
Step 3/7 : WORKDIR /go/src/github.com/sensu/uchiwa
 ---> Using cache
 ---> b1fb2dc9b5ed
Step 4/7 : RUN apk add --no-cache nodejs git &&     go install -v &&     npm install --production --unsafe-perm &&     npm dedupe &&     apk del --no-cache git nodejs &&     rm -rf /go/src/github.com/sensu/uchiwa/node_modules
 ---> Running in 431737f3dc89
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/9) Installing libssh2 (1.7.0-r0)
(2/9) Installing libcurl (7.55.0-r2)
(3/9) Installing expat (2.2.0-r1)
(4/9) Installing pcre (8.38-r1)
(5/9) Installing git (2.8.6-r0)
(6/9) Installing libgcc (5.3.0-r0)
(7/9) Installing libstdc++ (5.3.0-r0)
(8/9) Installing libuv (1.9.1-r0)
(9/9) Installing nodejs (6.7.0-r1)
Executing busybox-1.24.2-r11.trigger
OK: 57 MiB in 21 packages
uchiwa/sensu/request.go:8:2: cannot find package "net/http/httptrace" in any of:
        /go/src/github.com/sensu/uchiwa/vendor/net/http/httptrace (vendor tree)
        /usr/local/go/src/net/http/httptrace (from $GOROOT)
        /go/src/net/http/httptrace (from $GOPATH)
The command '/bin/sh -c apk add --no-cache nodejs git &&     go install -v &&     npm install --production --unsafe-perm &&     npm dedupe &&     apk del --no-cache git nodejs &&     rm -rf /go/src/github.com/sensu/uchiwa/node_modules' returned a non-zero code: 1

## Possible Solution

Worked if I update the Dockerfile with :
FROM golang:1.8-alpine

## Steps to Reproduce (for bugs)

Just build docker file

## Context

any
## Your Environment

* Uchiwa version used:
* Sensu version used:
* Operating System and version (e.g. Ubuntu 14.04):
ubuntu 16.04

**Comment by palourde** [comment]
Thank you for reporting this issue, it seems like even the builds on the Docker Hub are broken too. We will definitively upgrade the base image version!
