### ISSUE TITLE
Service status is "active (exited)"; website not working

### ISSUE THREAD

**Issue by RavDanny** [sensu/uchiwa#732]
After using Uchiwa successfully for a long time, the current service status is:
```
● uchiwa.service - LSB: Uchiwa, a Sensu dashboard.
   Loaded: loaded (/etc/init.d/uchiwa; bad; vendor preset: enabled)
   Active: active (exited) since Fri 2017-11-17 00:18:17 UTC; 4s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 16059 ExecStop=/etc/init.d/uchiwa stop (code=exited, status=0/SUCCESS)
  Process: 16101 ExecStart=/etc/init.d/uchiwa start (code=exited, status=0/SUCCESS)

Nov 17 00:18:17 sensu-server systemd[1]: Starting LSB: Uchiwa, a Sensu dashboard....
Nov 17 00:18:17 sensu-server uchiwa[16101]: uchiwa started.
Nov 17 00:18:17 sensu-server su[16104]: Successful su for uchiwa by root
Nov 17 00:18:17 sensu-server systemd[1]: Started LSB: Uchiwa, a Sensu dashboard..
Nov 17 00:18:17 sensu-server su[16104]: + ??? root:uchiwa
Nov 17 00:18:17 sensu-server su[16104]: pam_unix(su:session): session opened for user uchiwa by (uid=0)
```

I looked at the `man` page above, but wasn't sure what needed to be done

## Your Environment

* Uchiwa version used: 0.25.2-1
* Sensu version used: 0.29.0-11
* Operating System and version: Ubuntu 16.04 LTS

**Comment by palourde** [comment]
Hi @RavDanny,

Have you verified the log files (`/var/log/uchiwa.log` & `/var/log/uchiwa.err`)? That should provide us with more insight on what's going on.

Thanks

**Comment by RavDanny** [comment]
Hi @palourde,

Not much help, unfortunately. `/var/log/uchiwa.err` is empty and `/var/log/uchiwa.log` just contains lines like this: `{"timestamp":"2017-11-30T22:08:17.129966543Z","level":"info","message":"Updating the datacenter Sensu"}`.

Thanks

**Comment by palourde** [comment]
@RavDanny This log entry tells me that Uchiwa is still running and continues to query the Sensu APIs. Are you still unable to access the dashboard? And if you restart the service, does it work?

**Comment by palourde** [comment]
I'm closing this issue since we didn't received any responses.

If you are still facing this problem, please let us know with a comment and we'll be happy to reopen the issue.

Thanks!

**Comment by RavDanny** [comment]
Hi,
Sorry. I was away and got sidetracked.
The log is still saying the same thing, even after restarting the service, but I can't access the dashboard.
This is what I get with `curl http://130.56.248.135:3000` on the server:
```
...
<body>

  <div id="error" style="display: none;">
    <div class="error-code mb15 mt25">Oops!</div>
    <h3 class="font-bold">We couldn't load Uchiwa configuration.</h3>

    <div class="error-desc">
      Try refreshing the page and check your connectivity.<br/>
      If the issue persists, please refer to this
      <a href="https://docs.uchiwa.io/guides/troubleshooting/#errors">documentation</a> page.
    </div>
  </div>
...
```

**Comment by shajithravi** [comment]
Im facing the same issue. Any updates, @palourde ??

**Comment by Koxx3** [comment]
same problem :(
