### ISSUE TITLE
Alignment Issue in URI Events.

### ISSUE THREAD

**Issue by praveen9354** [sensu/uchiwa#740]
When clicking on the tab events, I was able to login. But the issue is with the alignment of data displayed. This behaviour is observed in default theme. 
* Uchiwa Version uchiwa-1.0.0-1.x86_64
* Sensu Version sensu-1.1.2-1.el6.x86_64
When I choose other theme (Uchiwa-Dark), It has no alignment issues. 
This behaviour is observed in Google chrome (Version 62.0.3202.94 (Official Build) (64-bit)).
Note:-
Where in Safari, Everything looks normal at default theme.

**Comment by praveen9354** [comment]
![image](https://user-images.githubusercontent.com/20865063/33521588-1727d2b6-d78b-11e7-81e4-aaf361c883c6.png)

**Comment by palourde** [comment]
Hi @praveen9354,

Have you tried to clear your cache and possibly Chrome with incognito mode?

Thanks

**Comment by palourde** [comment]
I'm closing this issue since we didn't received any responses.

If you are still facing this problem, please let us know with a comment and we'll be happy to reopen the issue.

Thanks!
