### ISSUE TITLE
UI Not loading

### ISSUE THREAD

**Issue by tb582** [sensu/uchiwa#741]
Browser console shows: 
```
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: http://<IP>:3000/bower_components/jsoneditor/dist/jsoneditor.min.js?rel=1512069388332
Source Map URL: jsoneditor.map
```

**Comment by cwjohnston** [comment]
Hi @tb582, this error looks like it has something to do with network communications between your browser and the API. Are you still having this problem? I believe that you were looking for help in our community slack instance the other day. If you are still debugging this, will you please ping me in slack as this doesn't seem to be an issue with Uchiwa itself?

**Comment by palourde** [comment]
I'm closing this issue since we didn't received any responses.

If you are still facing this problem, please let us know with a comment and we'll be happy to reopen the issue.

Thanks!
