### ISSUE TITLE
Docker hub build failing

### ISSUE THREAD

**Issue by donnex** [sensu/uchiwa#742]
The [uchiwa/uchiwa Docker hub image](https://hub.docker.com/r/uchiwa/uchiwa/) building seems to be failing at the moment. It's still referenced in the docs so I guess this still is the official image?

## Expected Behavior
The image should build and be in line with the current stable Uchiwa version.

## Current Behavior
The image build is failing.

## Possible Solution
I played around with the `Dockerfile` from the Github repo and found that it seems to be missing the `nodejs-npm` package. I'm not entirely sure if anything else is needed.

## Context
https://hub.docker.com/r/uchiwa/uchiwa/builds/

**Comment by try2codesecure** [comment]
pull #743
