### ISSUE TITLE
I want to stop sensu alert/notification while build and deployment

### ISSUE THREAD

**Issue by prabhakarsultane** [sensu/uchiwa#748]
I want to stop sensu alert/notification while build and deployment.
i am using below api to stop it but its not working.

curl -s -i -X POST -H 'Content-Type: application/json' -d '{"subscription": "client:<client>", "expire": 60 }' http://<server_ip>:4567/silenced

can anybody help me to resolved it?

**Comment by exeral** [comment]
I believe you are at the wrong place. You are in the Uchiwa project which is the sensu GUI.
you'll probably get more help at:
- https://sensucommunity.slack.com
- https://groups.google.com/forum/#!forum/sensu-users

hint: post the HTTP response you get.

I bet the problem is in the subscription

**Comment by palourde** [comment]
Closing this issue since it's the not the right place and more appropriate support channels have been suggested.
