### ISSUE TITLE
Dark theme causes Silence options to show Blank options

### ISSUE THREAD

**Issue by Shahjaved** [sensu/uchiwa#763]
When using White theme (Default theme) you are able to see the TEXT in the Silence/Unsilence options. 
## Current Behavior
When using "Dark" theme you are NOT able to see the TEXT in the Silence/Unsilence options.
 Expected Behavior - Should be able to see TEXT in  Silence/Unsilence options. 

## Possible Solution
Text color should change to White when selecting the Dark Theme

## Steps to Reproduce (for bugs)

1. Change Theme to "Dark" Theme 
2. Go to Alerts, select alerts to silence. 
3. Choose the text in  Silence/Unsilence Options.
4.Unable to see text until you mouse over and highlight the options in the drop down. 

## Context
Unable to see Text using Dark theme. We only use Dark theme and now are hindered in using it. 

## Your Environment

* Uchiwa version used: 1.1.3-2
* Sensu version used: 1.2.1-2
* Operating System and version: CentOS release 6.7

<img width="861" alt="uchiwa theme issue" src="https://user-images.githubusercontent.com/36871923/36709949-a18883f0-1b2f-11e8-8b54-b5bcee9226a5.png">

**Comment by palourde** [comment]
Hi @Shahjaved,

Thank you for reporting this issue. Unfortunately I was unable to reproduce with Chrome or Firefox.

Chrome 64:
![chrome](https://user-images.githubusercontent.com/4105580/36736960-df9e2744-1ba7-11e8-8c6c-d13b3587c0ba.png)

Firefox 58:
![firefox](https://user-images.githubusercontent.com/4105580/36736972-e8e3b4cc-1ba7-11e8-936d-58886ae78d06.png)

Can you let us know which browser and version you are using? Also, were you able to reproduce that problem on a different machine and/or browser?

Thanks

**Comment by exeral** [comment]
Hello, I confirm

![blankuchiwa](https://user-images.githubusercontent.com/14330725/36743895-b54264c6-1beb-11e8-8a4d-984ceb46fe8d.png)

Linux Fedora 27
Google Chrome
Version 64.0.3282.167 (Build officiel) (64 bits)

Uchiwa 0.26.3

**Comment by palourde** [comment]
So far the only common thing I see if that you both are running Linux. I don't have access to a linux machine with a GUI right now, so I'll need to setup something.

**Comment by Shahjaved** [comment]
@palourde  Sorry for the delayed response, i was on vacation and forgot about this. 
The browser i was using is Chrome - Version 65.0.3325.181 (Official Build) (64-bit)

I tried reproducing on IE and FireFox. Firefox showed a white background still but i was able to see black text just fine (kind of ugly though but usable). 

**Firefox - 57.0.2 (64-bit)** - Able to see text but has white background 

![image](https://user-images.githubusercontent.com/36871923/38908786-c1b8c7ac-4276-11e8-9276-24733e79dec0.png)

Internet Explorer is giving me a completely different issue where it won't even show the menu for silencing, so we'll leave that out of this specific Bug.

**Comment by palourde** [comment]
@Shahjaved I was finally able to reproduce that issue on Microsoft Edge 41 and submitted a PR for this issue. Hopefully it will be solved for all browser/operating systems concerned.
