### ISSUE TITLE
Uchiwa RPM does not have correct permissions for Logrotate definition file

### ISSUE THREAD

**Issue by adubnik** [sensu/uchiwa#765]
Uchiwa RPM does not seem to have correct permissions for Logrotate /etc/logrotate.d/uchiwa and it is setting one up to 
`
-rw-r--r--. 1 uchiwa uchiwa  144 Feb 15 16:48 uchiwa
`
 
## Expected Behavior
Uchiwa logs to rotate accordingly the Logrotate policy

## Current Behavior
Uchiwa logs do not rotate

## Possible Solution
change permissions post RPM deployment

## Steps to Reproduce (for bugs)
logrotate -d -f /etc/logrotate.d/uchiwa

## Context
Have to workaround by changing the permissions post installation

## Your Environment
* Uchiwa version used: 1.1.3
* Sensu version used: 1.2.1
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by palourde** [comment]
Hi @adubnik,

It should now be fixed with Uchiwa `1.1.3-2`. I believe upgrading should fix this issue, otherwise let us know.

Thank you
