### ISSUE TITLE
connecting to sensu-api with basic auth returns 401 unauthorized when correct credentials are used

### ISSUE THREAD

**Issue by etfeet** [sensu/uchiwa#768]
## Current Behavior
When I try to connect to the sensu-api I get a 401 unauthorized error even when using the correct credentials. However, connecting to the api via curl, etc works fine.

## Steps to Reproduce (for bugs)
api.json:

`
{
  "api": {
    "host": "localhost",
    "port": 4567,
    "user": "sensu",
    "password": "secret"
  }
}
`

uchiwa.json:
`
{
      "sensu": [
            {
          "name": "test",
          "host": "127.0.0.1",
          "user": "sensu",
          "password": "secret",
          "port": 4567,
          "timeout": 10
            }
          ],
          "uchiwa": {
            "loglevel": "debug",
            "host": "0.0.0.0",
            "port": 3000,
            "refresh": 10
          }
}
`

uchiwa.log
`
{"timestamp":"2018-03-27T17:25:10.455690494Z","level":"info","src":{"func":"github.com/sensu/uchiwa/uchiwa/daemon.(*Daemon).fetchData","line":74},"message":"Updating the datacenter test"}
{"timestamp":"2018-03-27T17:25:10.45582162Z","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getSlice","line":54},"message":"GET http://127.0.0.1:4567/stashes"}
{"timestamp":"2018-03-27T17:25:10.457397835Z","level":"warn","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).getSlice","line":59},"message":"GET http://127.0.0.1:4567/stashes returned: 401 Unauthorized"}
{"timestamp":"2018-03-27T17:25:10.457497607Z","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/daemon.(*Daemon).fetchData","line":83},"message":"401 Unauthorized"}
{"timestamp":"2018-03-27T17:25:10.45754475Z","level":"warn","src":{"func":"github.com/sensu/uchiwa/uchiwa/daemon.(*Daemon).fetchData","line":84},"message":"Connection failed to the datacenter test"}
{"timestamp":"2018-03-27T17:25:12.340157328Z","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/authorization.isReadOnly","line":47},"message":"No JWT found in context"}
{"timestamp":"2018-03-27T17:25:12.344742898Z","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/authorization.isReadOnly","line":47},"message":"No JWT found in context"}
{"timestamp":"2018-03-27T17:25:12.449642759Z","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/authorization.isReadOnly","line":47},"message":"No JWT found in context"}
`

using curl works fine
`
root@sensu-3:/etc/sensu# curl -sku 'sensu:secret' http://localhost:4567/stashes
[]
`

## Your Environment
uchiwa version: 1.1.3-2
sensu version: 1.2.1-2
OS: ubuntu server 16.04

**Comment by chaseconey** [comment]
We seem to be experiencing the same issue. Any ideas?

**Comment by palourde** [comment]
Hi @etfeet & @chaseconey,

As indicated on https://docs.uchiwa.io/getting-started/configuration/#datacenters-configuration-sensu, the attribute in Uchiwa configuration holding an API password is `pass` and not `password`.

Do not hesitate to let us now if there's anything else!
