### ISSUE TITLE
Only one silenced entry per DC is displayed

### ISSUE THREAD

**Issue by hanzhinstas** [sensu/uchiwa#785]
Only one silenced entry per DC is displayed in uchiwa. sensu API returns multiple entries for /silenced, but only one (last in list) is displayed in uchiwa.

* Uchiwa version used: 1.3.0-2
* Sensu version used: 0.26.5
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by allantalver** [comment]
Same issue with Uchiwa 1.3.0-2 on Sensu 1.3.3-1 / Ubtuntu 16.04.

**Comment by stevenviola** [comment]
Same issue for me. Upgrading to `Sensu Server 1.4.2` in one datacenter didn't fix the issue (although I still had other datacenters on older versions), and the only solution was to downgrade to `Uchiwa 1.2.0`. Creating new silenced entries were being created on the sensu server, but would not show up in Uchiwa after being created if there were already a sclienced entry for other servers in the same datacenter.

**Comment by amdprophet** [comment]
Uchiwa 1.3.1 has been released with a fix for this issue.
