### ISSUE TITLE
Docker builds failing for latest release

### ISSUE THREAD

**Issue by etrikp** [sensu/uchiwa#789]
## Expected Behavior
Docker image is available for latest release 

## Current Behavior
Builds are failing for latest release https://hub.docker.com/r/uchiwa/uchiwa/builds/

**Comment by gregorkistler** [comment]
Could someone please trigger the build job again?

https://hub.docker.com/r/uchiwa/uchiwa/builds/b7paq6hynw89kbhtzyv6rvv :
````
> uchiwa@0.0.1 postinstall /go/src/github.com/sensu/uchiwa
> bower --allow-root install


bower uchiwa-web#1.3.1      not-cached https://github.com/sensu/uchiwa-web.git#1.3.1

bower uchiwa-web#1.3.1         resolve https://github.com/sensu/uchiwa-web.git#1.3.1

[91mbower uchiwa-web#1.3.1    ENORESTARGET No tag found that was able to satisfy 1.3.1
````

**Comment by palourde** [comment]
Hi!

I manually created and triggered jobs for the 1.3.1-1 release and the images have been successfully created. I can't tell why it didn't work with the automated jobs, might be a caching issue of some sort.

Thanks for reporting it!

**Comment by gregorkistler** [comment]
Thanks dude!
