### ISSUE TITLE
Support for Sensu 2 (Go)

### ISSUE THREAD

**Issue by MrSaints** [sensu/uchiwa#796]
The latest version of Uchiwa for Docker does not appear to work nicely with Sensu 2.0.0-beta.3.

## Expected Behavior

Sensu dashboard to show up in Uchiwa when configured like so:

```
{
  "sensu": [
    {
      "name": "Testing",
      "host": "<omitted>",
      "port": 8080
    }
  ],
  "uchiwa": {
    "host": "0.0.0.0",
    "port": 3000
  }
}
```

## Current Behavior

![2018-08-27-234921_243x97_scrot](https://user-images.githubusercontent.com/68859/44690818-22a4ca80-aa54-11e8-9a32-25e221cb376f.png)

No dashboards.

## Possible Solution

I believe this is possibly because it is still configured for the previous version where Redis was being used instead of etcd ?

## Steps to Reproduce (for bugs)
1. Start Sensu
```
docker run -d --name sensu-backend \                                                   
-p 2380:2380 -p 8080:8080 -p 8081:8081 \
sensu/sensu:2.0.0-beta.3 sensu-backend start
```
2. Start Uchiwa
```
docker run -d -p 3000:3000 -v ~/uchiwa.json:/config/config.json uchiwa/uchiwa
```

## Context

N/A

## Your Environment

* Uchiwa version used: 1.3.1-1
* Sensu version used: 2.0.0-beta.3
* Operating System and version (e.g. Ubuntu 14.04): 

```
  Operating System: Arch Linux
  Kernel: Linux 4.18.4-arch1-1-ARCH
  Architecture: x86-64
```

**Comment by cwjohnston** [comment]
Hi @MrSaints, thanks for your request. Although it's not well-documented at this time, Sensu 2.0 provides a built-in web UI. As a result, there are no plans to implement support for Sensu 2.0 in Uchiwa.

Like you've come to expect from Uchiwa, Sensu 2.0 built-in web UI listens on port 3000 by default. I believe you can simply add `-p 3000:3000` to your existing `docker run`  command for sensu-backend and you'll be able to access the new web UI in your browser.
