### ISSUE TITLE
Uchiwa packages include spurious files under bower_components directory

### ISSUE THREAD

**Issue by cwjohnston** [sensu/uchiwa#804]
## Expected Behavior

Uchiwa packages include minimal content from upstream dependencies

## Current Behavior

Uchiwa packages some unnecessary files (markdown documents, shell scripts, etc) under bower_components directory

## Possible Solution

Revisit packaging scripts to prevent spurious files from being included in Uchiwa packages.

## Context

Presence of shell scripts, email addresses and other content in markdown documents causes false positives in automated security scans.

Examples:

/bower_components/jasmine/grunt/templates/licenseBanner.js.jst
/bower_components/jasmine/traviscore­script.sh
/bower_components/ua­parserjs/package.json
/bower_components/momentpicker/README.md

## Your Environment

* Uchiwa version used: 1.3.1
* Sensu version used:
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by annaplotkin** [comment]
False positive. Closing.
