### ISSUE TITLE
Uchiwa Datacenter config 

### ISSUE THREAD

**Issue by rhoml** [sensu/uchiwa#84]
I am trying to setup the datacenter variable, and correct me if I am wrong but managing the datacenter from https://github.com/sensu/uchiwa/blob/master/config.json.example#L4 imho is not the best way once we have custom data configured on each node. 

Is it possible to Open an issue to get it from the custom variables?

**Comment by jkhelil** [comment]
Hi,
Is there a way to filter servers on uchiwa based on custom variables

**Comment by patrickatomic** [comment]
the request from hkhelil would be nice indeedddd
