### ISSUE TITLE
Rich data output in UI

### ISSUE THREAD

**Issue by jaxxstorm** [sensu/uchiwa#86]
I'm opening this mainly as a placeholder/discussion topic after a chat with @palourde in IRC.

It would be interesting to be able to display rich data in the UI, including images, HTML links and potentially even data from graphite. I'll refer again to nagios-herald:

https://github.com/etsy/nagios-herald

This would be extremely useful to make the dashboard more dynamic and useful on an initial glance.

**Comment by kobayaashi** [comment]
Is there a way to image-ify relative links "/render..." so we have a way to reference resources on the same server in a cluster?
